### ISSUE TITLE
royalflush.yml

### ISSUE THREAD

**Issue by royalflushcr** [RoyaleAPI/cr-api-ux#101]
name: RoyalFlush™
key: RoyalFlush
color: black
track: true
emblem: flag_j_03
feature: true
vip: true
info:
  logo: https://imgur.com/a/19DN3QW
  description: >
    **RoyalFlush™ eSports Organisation**
    Welcome to the RoyalFlush Family! We are an Internationally based group of clans with members from all over the world. We have a fun and relaxed atmosphere that values maturity and discourages toxic behaviour. We are growing everyday and are looking for awesome Clashers to join our growing, competitive RF family. Our goal is to become a top Ladder and Clan Wars Clan, also to dominate the eSports scene. We take part in Clan Leagues, 2v2 tournaments, Draft Royale, and other Clash related events. Our clan also hosts daily Tournaments and many Gem Events. All our clans compete daily in Clan Wars with the main clans best ranking being #1 Global. So whether you are looking for a competitive clan, or just a casual atmosphere for active players, you’ll find it here at RoyalFlush!
  social:
    - twitter: http://twitter.com/RoyalFlush_CR
    - discord: http://discord.gg/3MBAD7c
    - email: mailto_cyclops@royalflushcr.com
    - instagram: http://instagram.com/RoyalFlush.CR
    - website: http://royalflushcr.com
clans:
  - name: RoyalFlush™
    tag: 89UJ8J2J
  - name: RF™ eSports
    tag: 8UP08G2Y
  - name: RoyalFlush
    tag: Y0JPU9Y
  - name: RoyalFlush II
    tag: CPVV9QJ
  - name: RoyalFlush III
    tag: CJLUGRG
  - name: RoyalFlush IV
    tag: GVYRY2G
  - name: RoyalFlush V
    tag: 98J2RPUU
  - name: RoyalFlush USA
    tag: 8GY0L0LU
  - name: RoyalFlush CA
    tag: 9PYG0QL0
  - name: RoyalFlush PER
    tag: 92L0RPRU
  - name: RoyalFlush IND
    tag: 8Q0YPP0C
  - name: RoyalFlush Neo
    tag: P9JL908L
  - name: RoyalFlush UK
    tag: 8GVPLCUY
  - name: RoyalFlush SA
    tag: P92G0JQ8   
  - name: RoyalFlush AUS
    tag: 8LV0GRRR

**Comment by smlbiobot** [comment]
```yaml
name: RoyalFlush™
key: royalflush
color: black
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/royalflush.jpg
  description: >
    **RoyalFlush™ eSports Organisation**
    Welcome to the RoyalFlush Family! We are an Internationally based group of clans with members from all over the world. We have a fun and relaxed atmosphere that values maturity and discourages toxic behaviour. We are growing everyday and are looking for awesome Clashers to join our growing, competitive RF family. Our goal is to become a top Ladder and Clan Wars Clan, also to dominate the eSports scene. We take part in Clan Leagues, 2v2 tournaments, Draft Royale, and other Clash related events. Our clan also hosts daily Tournaments and many Gem Events. All our clans compete daily in Clan Wars with the main clans best ranking being #1 Global. So whether you are looking for a competitive clan, or just a casual atmosphere for active players, you’ll find it here at RoyalFlush!
  social:
    - twitter: http://twitter.com/RoyalFlush_CR
    - discord: http://discord.gg/3MBAD7c
    - email: mailto_cyclops@royalflushcr.com
    - instagram: http://instagram.com/RoyalFlush.CR
    - website: http://royalflushcr.com
clans:
  - name: RoyalFlush™
    tag: 89UJ8J2J
  - name: RF™ eSports
    tag: 8UP08G2Y
  - name: RoyalFlush
    tag: Y0JPU9Y
  - name: RoyalFlush II
    tag: CPVV9QJ
  - name: RoyalFlush III
    tag: CJLUGRG
  - name: RoyalFlush IV
    tag: GVYRY2G
  - name: RoyalFlush V
    tag: 98J2RPUU
  - name: RoyalFlush USA
    tag: 8GY0L0LU
  - name: RoyalFlush CA
    tag: 9PYG0QL0
  - name: RoyalFlush PER
    tag: 92L0RPRU
  - name: RoyalFlush IND
    tag: 8Q0YPP0C
  - name: RoyalFlush Neo
    tag: P9JL908L
  - name: RoyalFlush UK
    tag: 8GVPLCUY
  - name: RoyalFlush SA
    tag: P92G0JQ8
  - name: RoyalFlush AUS
    tag: 8LV0GRRR
```
