### ISSUE TITLE
Add x6tence club family

### ISSUE THREAD

**Issue by txedo** [RoyaleAPI/cr-api-ux#104]
```yaml
name: x6tence Club
key: x6tence
color: black
emblem: Skull_06
sort: trophy
info:
  social:
    - twitter: https://twitter.com/x6tence_
    - discord: https://discord.gg/CN34ZUS
    - website: https://x6tence.com/
clans:
  - name: x6tence Club
    tag: 9P2VJL9G
  - name: x6tence Club 2
    tag: 92U8QGCV
  - name: x6tence Club 3
    tag: 8L8UR9Y0
  - name: x6tence Club 4
    tag: P2V9QGP0
  - name: x6tence Club Pink
    tag: 8Q8P00YU
  - name: x6tence Club Green
    tag: 9Q0C0G2Q
  - name: x6tence Club Blue
    tag: 8RY2Q92R
  - name: x6tence Club Red
    tag: 8YUYP02J
  - name: x6tence Club White
    tag: 8VJ92LCR
```
