### ISSUE TITLE
The HK Empire

### ISSUE THREAD

**Issue by PMofHK** [RoyaleAPI/cr-api-ux#105]
name: The HK Empire
key: HKE
color: Purple
track: true
emblem: A_Char_King_01
feature: true
vip: true
info:
  logo: 
  description: >
The HK Empire is a Hong Kong-based Clan with members from all around the globe. We have three clans at the moment, both of them serve for different purposes. 
The main clan welcomes skilled and active players with no least than 3800 trophies as we aim to be the top 50 clan in Hong Kong. The second and third clan are less demanding and only require members to be active and the required trophies are now 2000 and 0 respectively. 
The HK Empire family try to connect members from all clans and therefore we have a joint Telegram chat group for members all three clans. Moreover, joint clan tournament is held regularly in order to provide a perform for members to improve their skills and have fun together. 
The HK Empire have a supportive environment and from the leader to normal members are all friendly and willing to help each other with the game. We believe The HK Empire is the clan to make your Clash Royale gaming experience to reach a whole new level
Join the Empire and make Hong Kong great again today!

The HK Empire扎根香港，但成員遍佈全球多國。The HK Empire目前有三個部落，各有不同定位。
主部落目標是全港頭50名，因此我們邀請3800盃以上，有技術且活躍的玩家。二會和三會定位較為輕鬆，只要求成員活躍，目前分別邀請2000盃以上和0盃以上的活躍玩家。
The HK Empire致力連繫三個部落的會員共同進步，因此我們設有共同的Telegram群組作交流之用。另外，我們會定期舉行部落聯賽，讓三個會的成員以武會友，交流切磋技術，提升整體水平。
The HK Empire擁有良好的支援和交流環境，由上而下的所有成員都樂意為其他成員提供意見和技術支援。我們深信The HK Empire必定能夠令你的遊戲體驗更上一層樓。
Join the Empire and make Hong Kong great again today!
  
social:
   
clans:
  - name: The HK Empire
    tag: 8LVY2YQ8
  - name: The HK Empire²
    tag: 98R80LGJ
  - name: The HK Empire³
    tag: 9UUY99G8

**Comment by smlbiobot** [comment]
```yaml
name: The HK Empire
key: hke
color: Purple
emblem: A_Char_King_01
info:
  logo:
  description: >
    The HK Empire is a Hong Kong-based Clan with members from all around the globe. We have three clans at the moment, both of them serve for different purposes.
    The main clan welcomes skilled and active players with no least than 3800 trophies as we aim to be the top 50 clan in Hong Kong. The second and third clan are less demanding and only require members to be active and the required trophies are now 2000 and 0 respectively.
    The HK Empire family try to connect members from all clans and therefore we have a joint Telegram chat group for members all three clans. Moreover, joint clan tournament is held regularly in order to provide a perform for members to improve their skills and have fun together.
    The HK Empire have a supportive environment and from the leader to normal members are all friendly and willing to help each other with the game. We believe The HK Empire is the clan to make your Clash Royale gaming experience to reach a whole new level
    Join the Empire and make Hong Kong great again today!


    The HK Empire扎根香港，但成員遍佈全球多國。The HK Empire目前有三個部落，各有不同定位。
    主部落目標是全港頭50名，因此我們邀請3800盃以上，有技術且活躍的玩家。二會和三會定位較為輕鬆，只要求成員活躍，目前分別邀請2000盃以上和0盃以上的活躍玩家。
    The HK Empire致力連繫三個部落的會員共同進步，因此我們設有共同的Telegram群組作交流之用。另外，我們會定期舉行部落聯賽，讓三個會的成員以武會友，交流切磋技術，提升整體水平。
    The HK Empire擁有良好的支援和交流環境，由上而下的所有成員都樂意為其他成員提供意見和技術支援。我們深信The HK Empire必定能夠令你的遊戲體驗更上一層樓。
    Join the Empire and make Hong Kong great again today!
clans:
  - name: The HK Empire
    tag: 8LVY2YQ8
  - name: The HK Empire²
    tag: 98R80LGJ
  - name: The HK Empire³
    tag: 9UUY99G8

```
