### ISSUE TITLE
NeoGAF Clan Family

### ISSUE THREAD

**Issue by SUBZERO-08** [RoyaleAPI/cr-api-ux#109]
```yaml
name: NeoGAF Clan Family
key: GAF
color: black
track: true
emblem: Skull_01
feature: true
info:
  description: >
    NeoGAF is a family of clans which have been around since launch.
    We are extremely active and friendly, having players from all around the globe.
    All ages and skill levels welcome. Donate, be active, have fun!
clans:
  - name: NeoGAF
    tag: 20Y9PQ
  - name: GAF
    tag: QYYQCQ
  - name: Neogaf
    tag: Y8CGRR
  - name: GAF Royale
    tag: Q8C9CY
  - name: neogaf
    tag: 80J8RU9
```
