### ISSUE TITLE
Clan

### ISSUE THREAD

**Issue by ClashCanada** [RoyaleAPI/cr-api-ux#110]
```yaml
name: Clash Canada
key: ClashCan
color: red
emblem: flag_f_02

clans:
  - name: Clash Canada
    tag: JGYJV9Y
…
```
