### ISSUE TITLE
Alpha Family

### ISSUE THREAD

**Issue by paulorvj** [RoyaleAPI/cr-api-ux#112]
```yaml
name: Alpha Family
key: alphafamily
color: blue
track: true
emblem: Flame_02
feature: true
vip: true
info:
  description: >
    **A chama se mantém acesa.**
    Clã fundado em 21/03/2016. Clã de amigos. Venha fazer parte da família.
clans:
  - name: Alpha Sports BR
    tag: JGQ882U
  - name: Alpha Sports 2
    tag: 9PYPG2LJ
```
