### ISSUE TITLE
[Family] GiantCR

### ISSUE THREAD

**Issue by GiantCR** [RoyaleAPI/cr-api-ux#115]
```yaml
name: 巨人我要
key: GiantCR
color: Black
track: true
emblem: A_Char_Barbarian_03
feature: true
info:
  logo: https://imgur.com/cyeVAkg
  description: >
    **巨人我要**  
    歡迎Hongkonger加入巨人大家庭, Enjoy~
    設有WhatsApp群 - 18+Only
social:
    - facebook: https://www.facebook.com/groups/1405894502798560/
clans:
  - name: 巨人我要
    tag: JPG9RGC
  - name: 巨人我又要
    tag: 2JR9GLCP
  


…
```
