### ISSUE TITLE
[Family] Active

### ISSUE THREAD

**Issue by random-dpk** [RoyaleAPI/cr-api-ux#116]
``` yaml
name: Active family
key: Active
color: Black
track: true
emblem: Skull_03
feature: true
info: 
  logo: na
  description: >
    Active family in clash royale, just a chill clan growing stronger together, we're active af - 18+Only
social:
    - Instagram: https://www.instagram.com/active_dannypk
clans:
  - name: active
    tag: GGQLOQR
  - name: active warriors
    tag: 8C8QPU9R

```

**Comment by random-dpk** [comment]
How long does it take to be in royaleapi.com

**Comment by fourjr** [comment]
It will be on the website when the developers have time to add it, please be patient.

**Comment by fourjr** [comment]
We also don't provide family listing for single clans.

**Comment by random-dpk** [comment]
I have 3 but atm I just listed 2

**Comment by random-dpk** [comment]
What's the invalid label for

**Comment by fourjr** [comment]
Oops, saw it wrongly, please add all of your clans that you want to appear on the site. Sorry!

**Comment by smlbiobot** [comment]
```yaml
name: Active family
key: active
color: Black
emblem: Skull_03
info:
  description: >
    Active family in clash royale, just a chill clan growing stronger together, we're active af - 18+Only
  social:
    - Instagram: https://www.instagram.com/active_dannypk
clans:
  - name: active
    tag: GGQL0QR
  - name: active warriors
    tag: 8C8QPU9R

```

Tags shouldn’t have letter O in them
