### ISSUE TITLE
[Family] Reddit Ascenders

### ISSUE THREAD

**Issue by munsterlander** [RoyaleAPI/cr-api-ux#117]
```yaml
name: Reddit Ascenders
key: ascenders
color: red
track: false
emblem: Fugi_04
feature: true
info:
  description: >
**Reddit Ascenders**
    We may be new to the RCS however our main clan has been round since the global launch, at our peak we reached top 10 UK and now we are back, growing stronger by the day and looking to embark on our journey to the top! With regular tournaments and tons of experienced players we are looking to create a family like no other. As Official RCS members we are entitled to a great community where we expand our skill set and make new friends. With a Discord server that has over 200 members you will never be alone. Our clans are aggressive to complete war and climb to the top! However, the most important thing is, you get to be part of a family where you are heard and wanted.
  social:
    - discord: https://discord.gg/tCCFypW
    - website: http://www,RedditAscenders.com
    - twitter: https://twitter.com/redditascenders?lang=en
clans:
  - name: Reddit Ascension
    tag: 9JULYGJV
  - name: Reddit UpRising
    tag: 289RYYGU
  - name: Reddit Rising
    tag: 29RUQP8L
```
