### ISSUE TITLE
Family: Columbia

### ISSUE THREAD

**Issue by JoohnF** [RoyaleAPI/cr-api-ux#122]
```yaml
name: #COLOMBIA#
key: colombia
color: teal
track: false
emblem: flag_h_02
feature: true
info:
  logo: 
![colombialogo](https://user-images.githubusercontent.com/26281508/40952373-a5a56ef4-6840-11e8-9714-d8fcdecb0263.png)


  description: `>`
    #COLOMBIA# es una familia ubicada en el top local, conformada por los clanes #COLOMBIA#, #COLOMBIA# 2 y #colombia# 3. Frecuentemente realizamos "domingo épico". Es opcional participar en la guerra de clanes, sin embargo, si decides participar debes jugar todas las batallas de colección y guerra. Poseemos equipo competitivo. Se exige un mínimo de donaciones o peticiones.
  social:
    - twitter: https://twitter.com/colombia_cr
clans:
  - name: #COLOMBIA#
    tag: GVG2C0P
  - name: #COLOMBIA# 2
    tag: 208VYYUL
  - name: #colombia# 3
    tag: 8CL9PR9V
```

**Comment by smlbiobot** [comment]
can’t have special characters in family name

https://royaleapi.com/clan/family/colombia

```yaml
name: COLOMBIA
key: colombia
color: teal
track: false
emblem: flag_h_02
feature: true
info:
  logo: /static/img/brands/logo/columbia.png
  description: >
    #COLOMBIA# es una familia ubicada en el top local, conformada por los clanes #COLOMBIA#, #COLOMBIA# 2 y #colombia# 3. Frecuentemente realizamos "domingo épico". Es opcional participar en la guerra de clanes, sin embargo, si decides participar debes jugar todas las batallas de colección y guerra. Poseemos equipo competitivo. Se exige un mínimo de donaciones o peticiones.
  social:
    - twitter: https://twitter.com/colombia_cr
clans:
  - name: '#COLOMBIA#'
    tag: GVG2C0P
  - name: '#COLOMBIA# 2'
    tag: 208VYYUL
  - name: '#colombia# 3'
    tag: 8CL9PR9V
```
