### ISSUE TITLE
Sang Royale (yml)

### ISSUE THREAD

**Issue by PawlakCamille** [RoyaleAPI/cr-api-ux#124]
```
name: Sang Royale Family
key: SR
color: black
track: true
emblem: A_Char_King_02
feature: true
info:
  logo: https://image.noelshack.com/fichiers/2018/23/2/1528210470-logo.png
  description:
  **Sang Royale** is a french family of 5 clans founded from the begining of the game. SR1 & SR2 are competitive clans who have the objectives to reach the french top on trophees classement and also on clan war classement.
  social:
    - discord: https://discordapp.com/invite/kgNDsht
    - facebook: https://www.facebook.com/SangRoyaleCR/
    - twitter: https://twitter.com/SangRoyaleCR
    - youtube: https://www.youtube.com/channel/UCXYTLMngj2Xo2tn7yaFgdHQ
clans:
  - name: Sang Royale
    tag: CJQLP2
  - name: Sang Royale II
    tag: 2LUU0R0L
  - name: Sang Royale III
    tag: 8CPG2YU
  - name: Sang Royale IV
    tag: 8GQL980P
  - name: Sang Royale V
    tag: 8VVGJPCR
```

**Comment by smlbiobot** [comment]
```yaml
name: Sang Royale Family
key: sr
color: black
emblem: A_Char_King_02
info:
  logo: /static/img/brands/logo/sangroyale.png
  description: >
    **Sang Royale** is a french family of 5 clans founded from the begining of the game.
    SR1 & SR2 are competitive clans who have the objectives to reach the french
    top on trophees classement and also on clan war classement.
  social:
    - discord: https://discordapp.com/invite/kgNDsht
    - facebook: https://www.facebook.com/SangRoyaleCR/
    - twitter: https://twitter.com/SangRoyaleCR
    - youtube: https://www.youtube.com/channel/UCXYTLMngj2Xo2tn7yaFgdHQ
clans:
  - name: Sang Royale
    tag: CJQLP2
  - name: Sang Royale II
    tag: 2LUU0R0L
  - name: Sang Royale III
    tag: 8CPG2YU
  - name: Sang Royale IV
    tag: 8GQL980P
  - name: Sang Royale V
    tag: 8VVGJPCR
```
