### ISSUE TITLE
堅.香港人 clan family

### ISSUE THREAD

**Issue by yatyatling** [RoyaleAPI/cr-api-ux#127]
```yaml
name: 堅.香港人
key: realhk
color: red
track: false
emblem: Cherry_Blossom_03
feature: true
info:
  description: >
  歡迎香港人加入, 設有Whatsapp Group, 會定期邀約其他公會進行友誼賽. 入會必須先入wtsapp group
  social:
   - twitch: https://www.twitch.tv/simon1018
clans:
  - name: 堅.香港人
    tag: LPYQQLU
  - name: 堅.香港人#1
    tag: 8LYRPUJ0
  - name: 堅.香港人#2
    tag: RGJ8Y0P
  - name: 堅.香港人#3
    tag: 20GGU98L
```
