### ISSUE TITLE
万里学院家族 wanli clan family

### ISSUE THREAD

**Issue by Darklighture** [RoyaleAPI/cr-api-ux#132]
```yaml
name: 万里学院家族
key: wanli
color: orange
emblem: Orange_02
info:
  description: >
    万里学院家族欢迎大家加入，一起来打部落战~休闲请加附中附小，战斗请加训练营。请加微信: kongfuzi_
  social:
    - email: 975454015@qq.com
clans:
  - name: 万里学院
    tag: 82J08RR
  - name: 万里学院 训练营
    tag: 9URJ292U
  - name: 万里学院 附中
    tag: C0URCCV
  - name: 万里学院 附小
    tag: UUP9RYR
```
