### ISSUE TITLE
Reliqua Clanfamilie

### ISSUE THREAD

**Issue by ReliquaClan** [RoyaleAPI/cr-api-ux#135]
```yaml
name: Reliqua Clanfamilie
key: reliqua
color: yellow
emblem: flag_j_03
info:
  logo:  /static/img/brands/logo/reliqua.png
  description: >
    *Clanfamilie Reliqua* Wir bieten eine aktive, reife und freundliche Community + Monatliches Clanübergreifendes 1vs1 Turnier im K.O Modus. Wir erwarten, geistige Reife, Aktivität und Kriegsteilnahme
    Interesse die Clanfamilie weiter zu entwickeln sollte vorhanden sein. Wer beim Clankrieg den Sammeltag mit macht, spielt auch bitte den Finalkampf. Das Kampfdeck wenn möglich
    Testen!


    Die Clans Gamma und Delta nutzen wir als Aufbauclans (u lvl 8 Spieler)
    Ziel ist es unsere Clanfamilie stets zu erweitern.
  social:
    - twitter: http://twitter.com/CrReliqua
    - discord: http://discord.gg/MAj7eRe
    - youtube: https://www.youtube.com/channel/
    - website: http://www.clan-reliqua.de
    - facebook: https://facebook.com/ReliquaClan
    - youtube: https://www.youtube.com/channel/UC_6SIMCkaVe4oilFnsmldZQ
    - email: mailto:clan.reliqua@gmail.com
clans:
  - name: Reliqua Alpha
    tag: 8QVY9YCL
  - name: Reliqua Beta
    tag: 8GLYUCQ9
  - name: Reliqua Gamma
    tag: 9GVVVP0C
  - name: Reliqua Delta
    tag: 9C00PCC0
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/reliqua

**Comment by ReliquaClan** [comment]
```yaml
name: Reliqua Clanfamilie
key: reliqua
color: yellow
emblem: flag_j_03
info:
  logo:  /static/img/brands/logo/reliqua.png
  description: >
    *Clanfamilie Reliqua* Wir bieten eine aktive, reife und freundliche Community + Monatliches Clanübergreifendes 1vs1 Turnier im K.O Modus. Wir erwarten, geistige Reife, Aktivität und Kriegsteilnahme
    Interesse die Clanfamilie weiter zu entwickeln sollte vorhanden sein. Wer beim Clankrieg den Sammeltag mit macht, spielt auch bitte den Finalkampf. Das Kampfdeck wenn möglich
    Testen!
    Ziel ist es unsere Clanfamilie stets zu erweitern.
  social:
    - twitter: http://twitter.com/CrReliqua
    - discord: http://discord.gg/gQqpnqu
    - website: http://www.clan-reliqua.de
    - youtube: https://www.youtube.com/channel/UC_6SIMCkaVe4oilFnsmldZQ
    - email: mailto:clan.reliqua@gmail.com
clans:
  - name: Reliqua Alpha
    tag: 8QVY9YCL
  - name: Reliqua Beta
    tag: 9JPJGLJ9
```
