### ISSUE TITLE
Aloha

### ISSUE THREAD

**Issue by MC-Friedolin** [RoyaleAPI/cr-api-ux#137]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Die Aloharaner
key: aloha
color: violet
emblem: A_Char_Pekka_02
info:
  description:  **Aloha**
                       °Wir, die Familie der Aloharaner, sind ein Verbund aus deutschsprachigen Spielern.
                       °Als verwaltungsoffene Gemeinschaft haben unsere Mitgliederinnen und Mitglieder
                        die Möglichkeit, den Clan durch ihre Ideen mitzugestalten.
                       °Also, wenn du Interesse an uns gefunden hast, dann tritt uns doch bei!

clans:
  - name: Aloha
    tag: 8Q8L9R2V
```
