### ISSUE TITLE
Team Liquid NA - Clan Family

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#138]
```yaml
name: Team Liquid Mobile NA
key: TLNA
color: blue
track: true
emblem: flag_d_04
feature: true
info:
  logo: https://drive.google.com/file/d/1tVKxB_59KiGR-htAXw9Jbah06MzjeZ4-/view?usp=drivesdk
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 1000 members** spread over NA, EU and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - twitter: http://twitter.com/TeamLiquid
    - discord: http://TL.GG/MOBILE
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - reddit: https://www.reddit.com/r/Team_Liquid/
    - youtube: https://www.youtube.com/teamliquid
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
clans:
  - name: Team Liquid
    tag: 9YU2PQRV
  - name: Team Liquid 2
    tag: V8GRLCQ
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL Smash Elite
    tag: 820QC80V
  - name: TL Nitro
    tag: 9YYLQ99L
    ```

**Comment by smlbiobot** [comment]
```yaml
name: Team Liquid Mobile NA
key: tlna
color: blue
track: true
emblem: flag_d_04
feature: true
info:
  logo: /static/img/brands/logo/teamliquid.png
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 1000 members** spread over NA, EU and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - twitter: http://twitter.com/TeamLiquid
    - discord: http://TL.GG/MOBILE
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - reddit: https://www.reddit.com/r/Team_Liquid/
    - youtube: https://www.youtube.com/teamliquid
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
clans:
  - name: Team Liquid
    tag: 9YU2PQRV
  - name: Team Liquid 2
    tag: V8GRLCQ
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL Smash Elite
    tag: 820QC80V
  - name: TL Nitro
    tag: 9YYLQ99L
```
