### ISSUE TITLE
Team Liquid EU - Clan Family

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#139]
```yaml
name: Team Liquid Mobile EU
key: TLEU
color: blue
track: true
emblem: flag_d_04
feature: true
info:
  logo: https://drive.google.com/file/d/1tVKxB_59KiGR-htAXw9Jbah06MzjeZ4-/view?usp=drivesdk
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 1000 members** spread over NA, EU and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - twitter: http://twitter.com/TeamLiquid
    - discord: http://TL.GG/MOBILE
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - reddit: https://www.reddit.com/r/Team_Liquid/
    - youtube: https://www.youtube.com/teamliquid
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
clans:
  - name: TeamLiquid GER
    tag: 98R22PLY
  - name: TeamLiquid FR
    tag: 98PYR0VJ
  - name: TL Fluor FR
    tag: 9UP2JY2P
  - name: TeamLiquid BL
    tag: P0YJ0P2V
  - name: TeamLiquid SRB
    tag: 8J0J2RQC
  - name: TeamLiquid ITA
    tag: 9QRUO2GR
  - name: TL Solid
    tag: P888QQQ9
    ```

**Comment by smlbiobot** [comment]
```yaml
name: Team Liquid Mobile EU
key: tleu
color: blue
track: true
emblem: flag_d_04
feature: true
info:
  logo: /static/img/brands/logo/teamliquid.pngk
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 1000 members** spread over NA, EU and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - twitter: http://twitter.com/TeamLiquid
    - discord: http://TL.GG/MOBILE
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - reddit: https://www.reddit.com/r/Team_Liquid/
    - youtube: https://www.youtube.com/teamliquid
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
clans:
  - name: TeamLiquid GER
    tag: 98R22PLY
  - name: TeamLiquid FR
    tag: 98PYR0VJ
  - name: TL Fluor FR
    tag: 9UP2JY2P
  - name: TeamLiquid BL
    tag: P0YJ0P2V
  - name: TeamLiquid SRB
    tag: 8J0J2RQC
  - name: TeamLiquid ITA
    tag: 9QRU02GR
  - name: TL Solid
    tag: P888QQQ9
```

Please note the clan tag for ITA is `9QRU02GR` and not `9QRUO2GR`
