### ISSUE TITLE
Team Liquid LATAM - Clan Family

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#140]
```yaml
name: Team Liquid Mobile LATAM
key: TLLA
color: blue
track: true
emblem: flag_d_04
feature: true
info:
  logo: https://drive.google.com/file/d/1tVKxB_59KiGR-htAXw9Jbah06MzjeZ4-/view?usp=drivesdk
  description: >
    Establecido en el 2016 **Team Liquid** es una de las familias de clanes más prominentes en Clash Royale con **más de 1000 miembros** distribuidos en NA, EU y LATAM. Únete a nuestro discord: **TL.GG/MOBILE** para más información, así como una gran variedad de torneos y eventos!
  social:
    - twitter: http://twitter.com/TeamLiquid
    - discord: http://TL.GG/MOBILE
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - reddit: https://www.reddit.com/r/Team_Liquid/
    - youtube: https://www.youtube.com/teamliquid
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
clans:
  - name: TeamLiquid MX
    tag: 8URY28UC
  - name: TeamLiquid MX2
    tag: 92J9RY9C
  - name: TeamLiquid MX R
    tag: 9PPJJVLQ
  - name: TeamLiquid MX Z
    tag: 9Q88CP22
  - name: TeamLiquid HN
    tag: 9GLV822C
  - name: TeamLiquid SV
    tag: 8JG8Y20R
  - name: TeamLiquid SV2
    tag: 99UL0CRJ
  - name: TeamLiquid VE
    tag: VOGL8C8
  - name: TeamLiquid VE2
    tag: 889CQU88
  - name: TeamLiquid VE Z
    tag: 8L98R2JV
  - name: TeamLiquid VE A
    tag: 8R8LJYU2
  - name: TeamLiquid VE R
    tag: 8J8UVQL0
  - name: TeamLiquid PE X
    tag: 9YR8L8R8
  - name: TeamLiquid PE
    tag: 8JROLQ8U
  - name: TeamLiquid PE2
    tag: 98LJJLR9
  - name: TeamLiquid PE3
    tag: 8CPJV28G
  - name: TeamLiquid PE4
    tag: 8G90Y22R
  - name: TeamLiquid PEI
    tag: 980VLVOJ
  - name: TeamLiquid PE Y
    tag: 9JL98G9J
  - name: TeamLiquid PE Z
    tag: P80J882L
    ```
