### ISSUE TITLE
The Prata Family - Clan Family

### ISSUE THREAD

**Issue by Alphoz** [RoyaleAPI/cr-api-ux#141]
```yaml
name: Prata Family
key: Prata
color: Grey
track: true
emblem: Bolt_03
info:
  logo: /static/img/brands/logo/Bolt_03
  description: >
    **The Pratas** Founded by a group of legend. Members be active, participate in clan wars, make more donations and be nice to each other. 8 wars; 7 TOP finishes! RoyaleAPI.com
  social:
    -  discord: https://discord.gg/6vvxvGN
clans:
  - name: The Prata Heroes
    tag: PP8RYPP0
```
