### ISSUE TITLE
Famille Karmes PDF

### ISSUE THREAD

**Issue by diegotercero** [RoyaleAPI/cr-api-ux#142]
```yaml
name: Karmes PDF
key: karmespdf
color: blue
emblem: Skull_06
feature: true
track : true
info: 
  description: >
    **Karmes PDF** est un famille orientée RUSH/GDC. Objectif clan 1 -> TOP GDC /
    Objectif clans 2, 3 et 4 -> TOP RUSH. Famille mature et stable. Allers/Retours interdits.
    Pour infos contacter **karon69120** ou **lapinmalin** app mobile LINE
  social:
    facebook: https://www.facebook.com/Karmespdf/
    line: karon69120, lapinmalin
clans:
  - name: Karmes PDF
    tag: 8L8C2VJQ
  - name: Karmes PDF 2
    tag: 8Y0LRR92
  - name: Kamres PDF 3
    tag: 2C8L2299
  - name: Karmes PDF 4
    tag: 900LYVVU
```
