### ISSUE TITLE
Vanguard Family

### ISSUE THREAD

**Issue by milan252525** [RoyaleAPI/cr-api-ux#149]
```yaml
name: Vanguard Family
key: vanguard
color: violet
emblem: flag_n_04
info: 
  logo: https://i.imgur.com/Ig7mZHB.png
  description: >
    **Vanguard™** is a grass roots organization. We are striving to compete with the best on a daily basis, with heavy emphasis in esports we provide a environment for players to learn, laugh and compete at all levels for the casual players and the pros. Please join us at *discord.io/vanguardteam* to apply for a clan or tryout for a team.
  social:
    - discord: http://discord.gg/vanguardteam
    - website: https://vanguardesports.org/ 
    - twitter: https://twitter.com/VanguardTeamCR
    - twitch: https://twitch.tv/ohryantv
    - youtube: https://www.youtube.com/GamingwithNeph
clans:
  - name: Vanguard Team
    tag: 8YQ8UCGV
  - name: Vanguard™ Alpha
    tag: 9RQ2UPRG
  - name: Vanguard™ Light
    tag: 920YJ20P
  - name: Vanguard™ Chaos
    tag: 9UP8RPGG
  - name: Vanguard Matrix
    tag: 9UVCLLUG
  - name: Vanguard™ Void
    tag: 9VQL8YCU
  - name: Vanguard™ Dawn
    tag: 9JYPP0UC
  - name: Vanguard™️ NL
    tag: 99LRCLR0
  - name: Vanguard APAC
    tag: PPYLCYUR
  - name: Vanguard Titans
    tag: 9PQQ98L9
  - name: Vanguard™️ Dark
    tag: 982V2GRL
  - name: Vanguard™ Agoge
    tag: 9QU8QVYQ
  - name: Vanguard Plasma
    tag: 9UCG0RU9
  - name: Vanguard™️ Dusk
    tag: 9JLP9C20
  - name: Vanguard Voodoo
    tag: PY98LY0J
  - name: Vanguard Rogue
    tag: 9QG8QUC8
  - name: Vanguard Legacy
    tag: 9RJ8CPRV
sort: trophy
```
