### ISSUE TITLE
Autonomos Family

### ISSUE THREAD

**Issue by Alphoz** [RoyaleAPI/cr-api-ux#150]
```yaml
name: Autonomos is Awesome
key: Autonomos
color: Grey
track: true
emblem: Bolt_03
info:
  logo: https://www.dropbox.com/s/b736s1w7tk5dkyj/Autonomos.png?dl=0
  description: >
Welcome to the family of clans of Autonomos! We’re a growing family dedicated to Clash Royale who are looking for new members! Interested members can join our various branches of clan. RoyaleAPI.com
  social:
    -  discord: https://discord.gg/6vvxvGN - Prata Heroes
    -  discord: https://discord.gg/uD56E5w - BROTHERHOOD
    -  discord: https://discord.gg/YQzRjea - Rebels Elite
    -  discord: https://discord.gg/Xe5FmYC - Alteria
    -  discord: https://discord.gg/hNAEDyb - Apocalypse
    -  discord: https://discord.gg/DGnjSqv - Defense Grid
clans:
  - name: Prata Heroes
    tag: PP8RYPP0
  - name: BROTHERHOOD
    tag: JYUC9
  - name: The Hogwarts
    tag: P008P08V
  - name: Rebels United
    tag: 9GGVQPVC
  - name: Rebels Elite
    tag: 9RJQGYUL
  - name: Alteria
    tag: 2YL2VQQ
  - name: Apocalypse
    tag: 8PRCG0VY 
  - name: Defense Grid
    tag: 2PUYGP
  - name: House Stark
    tag: 2R22YLP
  - name: Gryffindor
    tag: 982V282U
```

**Comment by smlbiobot** [comment]
```yaml
name: Autonomos is Awesome
key: autonomos
color: Grey
emblem: Bolt_03
info:
  logo: /static/img/brands/logo/autonomos.png
  description: >
    Welcome to the family of clans of Autonomos! We’re a growing family dedicated to Clash Royale who are looking for new members! Interested members can join our various branches of clan. RoyaleAPI.com
  social:
    -  discord: https://discord.gg/6vvxvGN
    -  discord: https://discord.gg/uD56E5w
    -  discord: https://discord.gg/YQzRjea
    -  discord: https://discord.gg/Xe5FmYC
    -  discord: https://discord.gg/hNAEDyb
    -  discord: https://discord.gg/DGnjSqv
clans:
  - name: Prata Heroes
    tag: PP8RYPP0
  - name: BROTHERHOOD
    tag: JYUC9
  - name: The Hogwarts
    tag: P008P08V
  - name: Rebels United
    tag: 9GGVQPVC
  - name: Rebels Elite
    tag: 9RJQGYUL
  - name: Alteria
    tag: 2YL2VQQ
  - name: Apocalypse
    tag: 8PRCG0VY
  - name: Defense Grid
    tag: 2PUYGP
  - name: House Stark
    tag: 2R22YLP
  - name: Gryffindor
    tag: 982V282U
```
It’s not possible to have separate discord for different clans

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/autonomos

**Comment by Alphoz** [comment]
apologies, please use this discord link:
https://discord.gg/KhGktHc

**Comment by fourjr** [comment]
replace all of them with that?

**Comment by Alphoz** [comment]
```yaml
name: Autonomos is Awesome
key: Autonomos
color: Grey
track: true
emblem: Bolt_03
info:
  logo: https://www.dropbox.com/s/c3wd57ye9lorzsx/autonomous.png?dl=0
  description: >
Welcome to the family of clans of Autonomos! We’re a growing family dedicated to Clash Royale who are looking for new members! Interested members can join our various branches of clan. RoyaleAPI.com
  social:
    -  discord: https://discord.gg/KhGktHc
  - name: Prata Heroes
    tag: PP8RYPP0
  - name: BROTHERHOOD
    tag: JYUC9
  - name: The Hogwarts
    tag: P008P08V
  - name: Rebels United
    tag: 9GGVQPVC
  - name: Rebels Elite
    tag: 9RJQGYUL
  - name: Alteria
    tag: 2YL2VQQ
  - name: Apocalypse
    tag: 8PRCG0VY 
  - name: Defense Grid
    tag: 2PUYGP
  - name: House Stark
    tag: 2R22YLP
  - name: Gryffindor
    tag: 982V282U
![autonomous](https://user-images.githubusercontent.com/40230855/41630950-6755a814-7464-11e8-95d1-f275ecd620cd.png)
```
