### ISSUE TITLE
Adding the Legends Clan Family

### ISSUE THREAD

**Issue by laneylad** [RoyaleAPI/cr-api-ux#152]
```yaml
name: Legends Clan Family
key: Legends
color: Blue
track: true
emblem: Flame_04
feature: true
info:
  logo: https://i.groupme.com/1024x1024.png.dc795809b1db49bba8c46a71aac8208a
  description: >
    **Legends** are a group of legendary people who have mostly descended on the arena from dizzy heights of Top Battle Nations Clans. We are all friends, family in fact who are respectful active & kick some serious ass!
We are also very welcoming to new joiners who have a passion for the game and want to become **Legends** themselves.


  social:
    - discord: https://discord.gg/bzvX2Uw
clans:
  - name: Legends
    tag: 8P9UUP
  - name: Legends 2
    tag: JUQC2V
```

**Comment by smlbiobot** [comment]
```yaml
name: Legends Clan Family
key: legends
color: Blue
track: true
emblem: Flame_04
info:
  logo: /static/img/brands/logo/legends.png
  description: >
    **Legends** are a group of legendary people who have mostly descended on the arena from dizzy heights of Top Battle Nations Clans. We are all friends, family in fact who are respectful active & kick some serious ass!
    We are also very welcoming to new joiners who have a passion for the game and want to become **Legends** themselves.
  social:
    - discord: https://discord.gg/bzvX2Uw
clans:
  - name: Legends
    tag: 8P9UUP
  - name: Legends 2
    tag: JUQC2V
```
