### ISSUE TITLE
Bad Rabbits Family 

### ISSUE THREAD

**Issue by Robemonster** [RoyaleAPI/cr-api-ux#154]
```yaml

name: Bad Rabbits Family
key: Bad Rabbits
color: Gold
emblem: flag_j_03
  description: >
The Bad Rabbits are an adult's only gaming community that all come together in a family.
We have over 1000 members among all the different clans within Clash of Clans, Clash Royale, Boom Beach, Dominations, C.A.T.S. and more.
Our Primary Focus is in Clash Royale and Clash of Clans, where we have many clans with different skill sets to fit everyone's needs.
**All our clans are 25+ with some exceptions to select clans.**
If you apply, please include age in your request
  
  social:
    - discord: http://discord.gg/dEAPEKY
    - website: http://badrabbitsclan.net
    - twitch: https://twitch.tv/Amarokk
clans:
  - name: Bad Rabbits X
    tag: CP82YPG
  - name: Bad Rabbits
    tag: 2CPRUG
  - name: Bad Rabbits 42
    tag: 2PR2QU0
  - name: Bad Rabbits EDR
    tag: QL2LPY
  - name: Bad Rabbits Ops
    tag: 9R2VG8Q2
  - name: Bad Rabbits RR
    tag: QVLRJJP
  - name: Bad Rabbits ZOO
    tag: UUCY0Y

```

**Comment by smlbiobot** [comment]
```yaml
name: Bad Rabbits Family
key: bad_rabbits
color: Gold
emblem: flag_j_03
info:
  description: >
    The Bad Rabbits are an adult's only gaming community that all come together in a family.
    We have over 1000 members among all the different clans within Clash of Clans, Clash Royale, Boom Beach, Dominations, C.A.T.S. and more.
    Our Primary Focus is in Clash Royale and Clash of Clans, where we have many clans with different skill sets to fit everyone's needs.
    **All our clans are 25+ with some exceptions to select clans.**
    If you apply, please include age in your request

  social:
    - discord: http://discord.gg/dEAPEKY
    - website: http://badrabbitsclan.net
    - twitch: https://twitch.tv/Amarokk
clans:
  - name: Bad Rabbits X
    tag: CP82YPG
  - name: Bad Rabbits
    tag: 2CPRUG
  - name: Bad Rabbits 42
    tag: 2PR2QU0
  - name: Bad Rabbits EDR
    tag: QL2LPY
  - name: Bad Rabbits Ops
    tag: 9R2VG8Q2
  - name: Bad Rabbits RR
    tag: QVLRJJP
  - name: Bad Rabbits ZOO
    tag: UUCY0Y
```
