### ISSUE TITLE
Ocean's Fifty (Add Clan Family)

### ISSUE THREAD

**Issue by CarlosPuigGC** [RoyaleAPI/cr-api-ux#156]
```yaml
name: Ocean's
key: Ocean's Fifty
color: black
emblem: A_Char_Prince_03
info: Active player? Looking for a family? Join our clan in Clash Royale. Let's grow stronger together!
  logo: ![ocean s fifty facebook 1](https://user-images.githubusercontent.com/24650978/41674342-057e40c2-74c0-11e8-9cbb-b55ee13394f0.png)

  description: >
    **Ocean's Fifty** is a community team competing in the European region of Clash Royale League.
    The clan were created by the Sabadell brothers (Pol, Albert and Marc) in 2017. The brothers soon set 
    out to sign friends and acquaintances to expand the family. Nowadays Ocean's Fifty is one of the EU 
    Top 200 clans.
    The clan is a place for everyone, specially for active, young and competitive players.
    We all share a fellow passion for the game, are friendly, always donate, help each other out with the 
    same goal: to always improve our skills and have a great time!
    **Join Ocean's Fifty. Enjoy the game.**
  social:
    - instagram: https://www.instagram.com/oceansfifty/
    - facebook: https://facebook.com/OceansFifty/
    - email: mailto:oceansfiftyclan@gmail.com
clans:
  - name: Ocean's Fifty
    tag: 2J0LGV2J
```
