### ISSUE TITLE
cholocos.yml

### ISSUE THREAD

**Issue by chascarrillo** [RoyaleAPI/cr-api-ux#158]
```yaml
name: Cholos Locos
key: cholocos
color: pink
emblem: Bamboo_04
clans:
  - name: Cholos Locos
    tag: 9G0LJLP
```
