### ISSUE TITLE
Büschel-Familie

### ISSUE THREAD

**Issue by Baddy24** [RoyaleAPI/cr-api-ux#159]
```yaml
name: Büschel-Familie
key: b-f
color: blue
emblem: Lotus_01
info:
  logo: /static/img/brands/logo/bueschel.png
  description: >
    Die Büschel-Familie ist eine deutsche Clanfamilie, die 5 Clans vereint. Unser Anführer ist Haifischjäger aus Head of Büschel. Egal wie viele Pokale du hast, einer unserer Clans passt perfekt zu dir. eSports Team: Deluxe eSports 


 
clans:
  - name: Head of Büschel
    tag: 8UVGQ8UQ
  - name: Büschel-Clan DX
    tag: 2ULPUJVV
  - name: Büschel-Clan XI
    tag: 88JOUG2U
  - name: Büschel-Clan I
    tag: 2G8LVG2V
  - name: Büschel-Clan LX
    tag: 88COGGOQ
```

**Comment by smlbiobot** [comment]
Please upload your family logo here and provide a link.

**Comment by smlbiobot** [comment]
```yaml
name: Büschel-Familie
key: b-f
color: blue
emblem: Lotus_01
info:
  description: >
    Die Büschel-Familie ist eine deutsche Clanfamilie, die 5 Clans vereint. Unser Anführer ist Haifischjäger aus Head of Büschel. Egal wie viele Pokale du hast, einer unserer Clans passt perfekt zu dir. eSports Team: Deluxe eSports
clans:
  - name: Head of Büschel
    tag: 8UVGQ8UQ
  - name: Büschel-Clan DX
    tag: 2ULPUJVV
  - name: Büschel-Clan XI
    tag: 88J0UG2U
  - name: Büschel-Clan I
    tag: 2G8LVG2V
  - name: Büschel-Clan LX
    tag: 88C0GG0Q
```

Clan tags are always number 0 and not letter O
