### ISSUE TITLE
REBIRTH Family

### ISSUE THREAD

**Issue by xseniorchiefx** [RoyaleAPI/cr-api-ux#161]
```yaml
name: REBIRTH Family
key: Rebirth
color: yellow
emblem: Skull_01
feature: true
sort: trophy
  description: >

    **Talent Wins Games, but Teamwork and Intelligence wins Wars!**
    Our team has the belief that we are defined by our compassion and kindness towards others.  

social:
    - discord: https://discord.gg/mx4AhrU
clans:
  - name: REBIRTH
    tag: 28JR0UUL
  - name: Revival
    tag: 92L9cr98
```

**Comment by smlbiobot** [comment]
```yaml
name: REBIRTH Family
key: rebirth
color: yellow
emblem: Skull_01
feature: true
sort: trophy
info:
  description: >
    **Talent Wins Games, but Teamwork and Intelligence wins Wars!**
    Our team has the belief that we are defined by our compassion and kindness towards others.

social:
    - discord: https://discord.gg/mx4AhrU
clans:
  - name: REBIRTH
    tag: 28JR0UUL
  - name: Revival
    tag: 92L9cr98
```
