### ISSUE TITLE
xQlusive Family

### ISSUE THREAD

**Issue by heinvolks** [RoyaleAPI/cr-api-ux#169]
```yaml
name: xQlusive
key: xq
color: purple
emblem: flag_h_03.png
info:
  logo: N/A
  description: >
   **xQlusive** is the result of a bold move to abandon the clan ARS United in favour of a new family of clans with one specific goal in mind: **each clan is tailored for a specific Clan War Readiness.** 
   This way a whole clan operates on a similar Card Level advantage and are equally ready for War Battles. And by levelling up your Card Levels, you advance to a higher Clan! 


  social: N/A
clans:
  - name: xQlusive Gold
    tag: P0UUL80C
  - name: xQlusive Silver
    tag: 9JQC8GVQ
  - name: xQlusive Bronze
    tag: 9R0UCQYJ
  - name: xQlusive Casual
    tag: PL08R8JY
```

**Comment by smlbiobot** [comment]
Added sorry for the delay: https://royaleapi.com/f/xq

**Comment by heinvolks** [comment]
@smlbiobot I'd like to update our family:

```yaml
  description: >
   **xQlusive** is een clanfamilie met een aantal interessante kenmerken:
   - Elk Clan War Season worden er 1600 Gems per clan verdeeld, dat is ruim **10.000 Gems per maand**
   - De clanstructuur is er op gericht om Clan Wars zo effectief mogelijk te maken, doordat er ingedeeld wordt op basis van RoyaleAPI's **Clan War Readiness**
   - Goede spelers die simpelweg de kaartlevels nog niet zo hoog hebben, hoeven bij ons niet gestraft/gekickt te worden, vanwege deze unieke indeling

   Je leest er alles over op onze Discord server. Welkom in xQlusive!


  social: 
    - discord: https://discord.me/xqlusive
```

**Comment by smlbiobot** [comment]
```yml
name: xQlusive
key: xq
color: purple
emblem: flag_h_03
info:
  description: >
    **xQlusive** is een clanfamilie met een aantal interessante kenmerken:


    - Elk Clan War Season worden er 1600 Gems per clan verdeeld, dat is ruim **10.000 Gems per maand**<br>


    - De clanstructuur is er op gericht om Clan Wars zo effectief mogelijk te maken, doordat er ingedeeld wordt op basis van RoyaleAPI's **Clan War Readiness**<br>


    - Goede spelers die simpelweg de kaartlevels nog niet zo hoog hebben, hoeven bij ons niet gestraft/gekickt te worden, vanwege deze unieke indeling<br>


    Je leest er alles over op onze Discord server. Welkom in xQlusiveclans:

  social:
    - discord: https://discord.me/xqlusive
clans:
  - name: xQlusive Gold
    tag: P0UUL80C
  - name: xQlusive Silver
    tag: 9JQC8GVQ
  - name: xQlusive Bronze
    tag: 9R0UCQYJ
  - name: xQlusive Casual
    tag: PL08R8JY
```

Will be updated in a few hours.
