### ISSUE TITLE
WoT Family

### ISSUE THREAD

**Issue by Romaindbs** [RoyaleAPI/cr-api-ux#174]
```yaml
name: WoT
key: wot
color: purple
emblem: Bolt_1
Feature: true
Vip: true
info: 
  logo: 
  description:
WoT est un clan Français qui existe depuis le lancement de Clash Royale. Il regroupe 200 membres dans 4 clans avec différents niveaux. 
Nous sommes un clan adulte, convivial et performant. Top FR en ladder et GDC. Rejoignez-nous sur notre discord pour plus d'informations : http://discord.gg/rUDp3E5.


 
  social:
    - discord: http://discord.gg/rUDp3E5

clans:
  - name: WoT
    tag: #29LPY
  - name: WoT II
    tag: #8GGY2RPP
  - name: WoT III
    tag: #PU8J09G
  - name: WoT IV
    tag: #JRV2P2L
```

**Comment by smlbiobot** [comment]
```yaml
name: WoT
key: wot
color: purple
emblem: Bolt_01
info:
  description: >
    WoT est un clan Français qui existe depuis le lancement de Clash Royale. Il regroupe 200 membres dans 4 clans avec différents niveaux.
    Nous sommes un clan adulte, convivial et performant. Top FR en ladder et GDC.
    Rejoignez-nous sur notre discord pour plus d'informations: discord.gg/rUDp3E5
  social:
    - discord: http://discord.gg/rUDp3E5
clans:
  - name: WoT
    tag: 29LPY
  - name: WoT II
    tag: 8GGY2RPP
  - name: WoT III
    tag: PU8J09G
  - name: WoT IV
    tag: JRV2P2L
```
