### ISSUE TITLE
WoT Family

### ISSUE THREAD

**Issue by mercowot1** [RoyaleAPI/cr-api-ux#175]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:WoT Family
key:WoT
color:purple
emblem:Bolt_01
info:
  logo:
  description: >
    Et je parle bien DU clan WoT. Pour nous WoT c’est 1 clan de 200 membres et pas 4 clans de 50 membres. Cette différence est très importante. L’objectif de chaque joueur entrant chez WoT est de faire un jour partie du clan I. Tous nos efforts sont faits dans le but de propulser le clan I le plus haut possible sur la scène FR. Cela profitera bien entendu aux autres clans WoT car plus le niveau augmentera dans le I plus il sera élevé dans les autre

    Add new line with 2 line breaks as above.
  social:
    - discord: http://discord.gg/rUDp3E5
clans:
  - name: WoT
    tag: 29LPY
  - name: WoT II
    tag: 8GGY2RPP
  - name: WoT III
    tag: PU8J09G
  - name: WoT IV
    tag: JRV2P2L
```
