### ISSUE TITLE
Mkers Family

### ISSUE THREAD

**Issue by riccardoperra** [RoyaleAPI/cr-api-ux#178]
```yaml
name: Mkers Family 
key: Mkers
color: Black
emblem: A_Char_King_01.png
Feature: true
Vip: true
sort: trophy
info:
  logo: https://mkers.gg/wp-content/uploads/2018/03/logomkerscr.png
  description: >
 Mkers is an eSport Organization based in Italy and it's formed by managers and established players, more then 10 years of experience in our country across games, events and competitions. We're in Clash Royale, FIFA, FIFA Pro Club, Moto GP, Hearthstone, Brawl Stars, Tennis World Tour. In Clash Royale, Mkers consist of an international big family with many branches and team. Mainly, it's composed of a Pro Team and a Ladder Clan supported by the branches. 

  social:
    - twitter: http://twitter.com/MkersCR
    - discord: https://discord.gg/JjW976f
    - website: https://www.mkers.gg/
    - instagram: https://instagram.com/mkersofficial
    - facebook: https://facebook.com/mkersofficial
    - email: mailto:ignazio@mkers.it

clans:
  - name: Mkers
    tag: 98QCV9CG
 -name: Mkers ITA
    tag: #9UJV0JGP
   - name: Mkers ITA 1.5
    tag: 99VCR0YP
  - name: Mkers ITA 2
    tag: 9GYCQ0J8
  - name: Mkers ITA 3
    tag: 92U08YJ2
- name: Mkers USA
    tag: P2V89JCQ
 - name: Mkers DE
    tag: 9YJ228YL
  -name: Mkers Brazil
    tag: 928JGVP2
  - name: Mkers FRA
    tag: 99V8YQQ8
  - name: Mkers IND
   tag: 92RV2CGJ
  - name: Mkers SV
    tag: 98UYCJCJ
  - name: Mkers RO
    tag: 9Q2980PR
  - name: Mkers PE
   tag: 9JL9CGU2
  - name: Mkers CRC
  tag: 9VG892Q8

```

**Comment by smlbiobot** [comment]
```yaml
name: Mkers Family
key: mkers
color: black
emblem: A_Char_King_01
sort: trophy
info:
  logo: /static/img/brands/logo/mkers.png
  description: >
    Mkers is an eSport Organization based in Italy and it's formed by managers and established players, more then 10 years of experience in our country across games, events and competitions. We're in Clash Royale, FIFA, FIFA Pro Club, Moto GP, Hearthstone, Brawl Stars, Tennis World Tour. In Clash Royale, Mkers consist of an international big family with many branches and team. Mainly, it's composed of a Pro Team and a Ladder Clan supported by the branches.
  social:
    - twitter: http://twitter.com/MkersCR
    - discord: https://discord.gg/JjW976f
    - website: https://www.mkers.gg/
    - instagram: https://instagram.com/mkersofficial
    - facebook: https://facebook.com/mkersofficial
    - email: mailto:ignazio@mkers.it
clans:
  - name: Mkers
    tag: 98QCV9CG
  - name: Mkers ITA
    tag: 9UJV0JGP
  - name: Mkers ITA 1.5
    tag: 99VCR0YP
  - name: Mkers ITA 2
    tag: 9GYCQ0J8
  - name: Mkers ITA 3
    tag: 92U08YJ2
  - name: Mkers USA
    tag: P2V89JCQ
  - name: Mkers DE
    tag: 9YJ228YL
  - name: Mkers Brazil
    tag: 928JGVP2
  - name: Mkers FRA
    tag: 99V8YQQ8
  - name: Mkers IND
    tag: 92RV2CGJ
  - name: Mkers SV
    tag: 98UYCJCJ
  - name: Mkers RO
    tag: 9Q2980PR
  - name: Mkers PE
    tag: 9JL9CGU2
  - name: Mkers CRC
    tag: 9VG892Q8
```
