### ISSUE TITLE
Update Royale Con Queso clan family

### ISSUE THREAD

**Issue by jbooruiz** [RoyaleAPI/cr-api-ux#180]
Hi!
I've just seen Royale Con Queso's family (https://royaleapi.com/clan/family/queso/clans) isn't updated. This is the list of clans updated.

TeamQueso (#8QPU8GC9)
Arena Quesito (#8PQQ0RVP)
RoyaleConQueso (#PQJ2Y)
RoyaleSinQueso (#929092)
RoyaleConBBQ (#2802GPP9)
RoyaleConJalapeño (#8V2C0RL2)
RoyaleConHuevo (#RLU9URP)
RoyalePepinillo (#LJQLJGR)
RoyaleConBacon (#22QUCG0)
RoyaleConJamon (#CJQGQ8R)
RoyaleConPollo (#VVG99G9)

It would be really cool if the list on the clan family can be in that order.

**Comment by smlbiobot** [comment]
@jbooruiz Happy to update, but can you use the config format:

```yaml
name: Royale Con Queso
key: queso
color: blue
track: false
emblem: Crown_02
clans:
  - name: RoyaleConQueso
    tag: PQJ2Y
  - name: TeamQueso
    tag: 8QPU8GC9
  - name: RoyaleSinQueso
    tag: 929092
  - name: RoyaleConBBQ
    tag: 2802GPP9
  - name: RoyaleConHuevo
    tag: RLU9URP
  - name: RoyalePepinillo
    tag: LJQLJGR
  - name: RoyaleConBacon
    tag: 22QUCG0
  - name: RoyaleConJamon
    tag: CJQGQ8R
  - name: RoyaleConPollo
    tag: VVG99G9
```
and send back the file? thanks!

**Comment by jbooruiz** [comment]
I'm sorry I just remembered :sweat_smile:

**Comment by jbooruiz** [comment]
name: Royale Con Queso
key: queso
color: blue
emblem: Crown_02
info:
  description: >
    **Royale Con Queso** was created by Alvaro845 in January 2016.
    It started just as a ladder family, but the family went into eSports too.
    TeamQueso and Arena Quesito are the competitive clans, competing at the best Clash Royale leagues.
social:
  - twitter: https://twitter.com/RoyaleQueso
  - discord: https://discord.gg/rcq
  - website: http://royaleconqueso.com
clans:
  - name: TeamQueso
    tag: 8QPU8GC9
  - name: Arena Quesito
    tag: 8PQQ0RVP
  - name: RoyaleConQueso
    tag: PQJ2Y
  - name: RoyaleSinQueso
    tag: 929092
  - name: RoyaleConBBQ
    tag: 2802GPP9
  - name: RoyaleJalapeño
    tag: 8V2C0RL2
  - name: RoyaleConHuevo
    tag: RLU9URP
  - name: RoyalePepinillo
    tag: LJQLJGR
  - name: RoyaleConBacon
    tag: 22QUCG0
  - name: RoyaleConJamon
    tag: CJQGQ8R
  - name: RoyaleConPollo
    tag: VVG99G9

**Comment by jbooruiz** [comment]
[rcq.txt](https://github.com/RoyaleAPI/cr-api-ux/files/2164205/rcq.txt)

**Comment by smlbiobot** [comment]
```yaml
name: Royale Con Queso
key: queso
color: blue
emblem: Crown_02
info:
  description: >
    **Royale Con Queso** was created by Alvaro845 in January 2016.
    It started just as a ladder family, but the family went into eSports too.
    TeamQueso and Arena Quesito are the competitive clans, competing at the best Clash Royale leagues.
social:
  - twitter: https://twitter.com/RoyaleQueso
  - discord: https://discord.gg/rcq
  - website: http://royaleconqueso.com
clans:
  - name: TeamQueso
    tag: 8QPU8GC9
  - name: Arena Quesito
    tag: 8PQQ0RVP
  - name: RoyaleConQueso
    tag: PQJ2Y
  - name: RoyaleSinQueso
    tag: 929092
  - name: RoyaleConBBQ
    tag: 2802GPP9
  - name: RoyaleJalapeño
    tag: 8V2C0RL2
  - name: RoyaleConHuevo
    tag: RLU9URP
  - name: RoyalePepinillo
    tag: LJQLJGR
  - name: RoyaleConBacon
    tag: 22QUCG0
  - name: RoyaleConJamon
    tag: CJQGQ8R
  - name: RoyaleConPollo
    tag: VVG99G9
```
is fine — but the clan description… do you have authority to write for them? Are you part of Team Queso?
