### ISSUE TITLE
Family: DVAS

### ISSUE THREAD

**Issue by Mister-Welldone** [RoyaleAPI/cr-api-ux#181]
```yaml
name: Deadly Viper Assassination Squad
key: DVAS
color: yellow
emblem: flag_j_03
info:
  logo: https://i.imgur.com/hvWnAPn.png
  description: >
D.V.A.S. - Deadly Viper Assassination Squad is comprised of 4 vigorous gold clans and in record timing of 3 months. Black Mamba is the tip of the D.V.A.S. spear by holding down the top 15 spot on the war trophy leaderboards (international) and in the top 25 of the clan leaderboards (international). Our other 3 clans, Cottonmouth, Snake Charmer and Sidewinder are fast on the heels of Black Mamba and can also be found on the Top 200 leaderboards. The four clans below make up the D.V.A.S. Clan Family, which is what our many active, solid and experienced, trophy-pushers and tournament competitors call home. The clans were created as a result of a mass exodus from the devil’s den and a reunion in the snake pit. Established April 2018.
  social:
    - discord: https://discord.gg/GWrCfNt
clans:
  - name: Black Mamba
    tag: 9YC80UQ9
  - name: Cottonmouth
    tag: 9JJQLVU8
  - name: Sidewinder
    tag: 9RGGY0PR
  - name: Snake Charmer
    tag: 99VPJ29G
```

**Comment by smlbiobot** [comment]
```yaml
name: Deadly Viper Assassination Squad
key: dvas
color: yellow
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/dvas.png
  description: >
    D.V.A.S. - Deadly Viper Assassination Squad is comprised of 4 vigorous gold clans and in record timing of 3 months. Black Mamba is the tip of the D.V.A.S. spear by holding down the top 15 spot on the war trophy leaderboards (international) and in the top 25 of the clan leaderboards (international). Our other 3 clans, Cottonmouth, Snake Charmer and Sidewinder are fast on the heels of Black Mamba and can also be found on the Top 200 leaderboards. The four clans below make up the D.V.A.S. Clan Family, which is what our many active, solid and experienced, trophy-pushers and tournament competitors call home. The clans were created as a result of a mass exodus from the devil’s den and a reunion in the snake pit. Established April 2018.
  social:
    - discord: https://discord.gg/GWrCfNt
clans:
  - name: Black Mamba
    tag: 9YC80UQ9
  - name: Cottonmouth
    tag: 9JJQLVU8
  - name: Sidewinder
    tag: 9RGGY0PR
  - name: Snake Charmer
    tag: 99VPJ29G
```
