### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by C00ls0ul** [RoyaleAPI/cr-api-ux#184]
```yaml
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: https://cdn.discordapp.com/attachments/296493772383191040/466261620742684682/Undefined_Logo.gif
  description: >
🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟
⭐Discord⭐Invite Code: X55XZHD⭐
⭐twitch.tv/sepp317⭐Sister Clans: Undefined & Defined⭐
🌠4#1
  social:
    - discord: https://discord.me/undefined
    - twitch: https://www.twitch.tv/sepp317
    - youtube: https://youtube.com/channel%2FUCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: 9RU2V2U9
```

**Comment by smlbiobot** [comment]
```yaml
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/undefined.gif
  description: >
    🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟
    ⭐Discord⭐Invite Code: X55XZHD⭐
    ⭐twitch.tv/sepp317⭐Sister Clans: Undefined & Defined⭐
    🌠4#1
  social:
    - discord: https://discord.me/undefined
    - twitch: https://www.twitch.tv/sepp317
    - youtube: https://youtube.com/channel%2FUCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: 9RU2V2U9
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/undefined

**Comment by C00ls0ul** [comment]
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/undefined.gif
  description: >
    🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟<br>
    ⭐Discord⭐Invite Code: X55XZHD⭐<br>
    ⭐twitch.tv/sepp317⭐Sister Clans: Undefined & Defined⭐<br>
    🌠4#1
  social:
    - discord: https://discord.me/undefined
    - twitch: https://www.twitch.tv/sepp317
    - youtube: https://youtube.com/channel%2FUCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: 9RU2V2U9

**Comment by C00ls0ul** [comment]
Note:
On the page, the description is as follows...

🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟 ⭐Discord⭐Invite Code: X55XZHD⭐ ⭐twitch.tv/sepp317⭐Sister Clans: Undefined & Defined⭐ 🌠4#1

However, I would like to have it like this...

:star2::star2::star2:Active, Loyal, & Respectful:star2::star2::star2:
:star:Discord:star:Invite Code: X55XZHD:star:
:star:twitch.tv/sepp317:star:Sister Clans: Undefined & Defined:star:
:stars:4#1

**Comment by smlbiobot** [comment]
```yaml
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/undefined.gif
  description: >
    🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟<br/>

    ⭐️Discord⭐️Invite Code: X55XZHD⭐️<br/>

    ⭐️twitch.tv/sepp317⭐️Sister Clans: Undefined & Defined⭐️<br/>

    🌠4#1<br/>
  social:
    - discord: https://discord.me/undefined
    - twitch: https://www.twitch.tv/sepp317
    - youtube: https://youtube.com/channel%2FUCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: 9RU2V2U9
```
