### ISSUE TITLE
Family: Ericsson

### ISSUE THREAD

**Issue by lutyz** [RoyaleAPI/cr-api-ux#187]
```yaml
name: Ericsson
key: e///
color: blue
emblem: Skull_01
sort: trophy
info:
  description: >
    Welcome to Ericsson family! facebook group:EricssonCR learn&laugh&compete
clans:
  - name: Ericsson
    tag: PPP2U0
```
