### ISSUE TITLE
Clan family request: DBZ Family

### ISSUE THREAD

**Issue by aaronaqua** [RoyaleAPI/cr-api-ux#188]
```yaml
name: DBZ Family
key: dbz
color: purple
emblem: Elixir_01
info:
  logo: https://imgur.com/ee5IGgq
  description: >
   The DBZ Family -  **Home to #1 Local clan DBZ Saiyans.** Our family consists of 6 active clans. Please join our discord server using the link below if you are interested in joining us.
  social:
    - discord: http://discord.me/dbz
clans:
  - name: DBZ Saiyans
    tag: 89YVRV
  - name: DBZ HTC
    tag: Q29UJ0Y
  - name: DBZ Fusion
    tag: 82G9C220
  - name: DBZ Genesis
    tag: 9CUUPGCC
  - name: DBZ Uprising
    tag: 8C00C92R
  - name: DBZ Ares
    tag: 9V0URJR9
…
```

**Comment by smlbiobot** [comment]
```yaml
name: DBZ Family
key: dbz
color: purple
emblem: Elixir_01
info:
  logo: /static/img/badge/Elixir_01.png
  description: >
    The DBZ Family -  **Home to #1 Local clan DBZ Saiyans.** Our family consists of 6 active clans. Please join our discord server using the link below if you are interested in joining us.
  social:
    - discord: http://discord.me/dbz
clans:
  - name: DBZ Saiyans
    tag: 89YVRV
  - name: DBZ HTC
    tag: Q29UJ0Y
  - name: DBZ Fusion
    tag: 82G9C220
  - name: DBZ Genesis
    tag: 9CUUPGCC
  - name: DBZ Uprising
    tag: 8C00C92R
  - name: DBZ Ares
    tag: 9V0URJR9
```
