### ISSUE TITLE
Kasalla Family

### ISSUE THREAD

**Issue by TheHalem** [RoyaleAPI/cr-api-ux#189]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02.png
info:
  logo: https://prnt.sc/k58x48
  description: Deutsche, ständig wachsende, Clash Royale Family. Wir haben ein eSport Team, bei dem auch neue sich beweisen können und veranstalten regelmäßig Turniere. Außerdem haben wir einen gut organisierten Discord Server, der täglich Mitglieder aus unseren Clans an sich zieht. Aufgrund unserer vielen Clans ist ein jedermann bei uns gut aufgehoben. Was willst du mehr? JOIN NOW!>
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://instagram.com/kasallacr
    - line: mo_ka


clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: Kasalla Squad
    tag: 9JUU2YQG
  - name: Kasalla Gala™
    tag: 9G0YRQGG
  - name: Kasalla Castle
    tag: P9G0R8G0
  - name: Kasalla Seebs
    tag: 9R99Y29L
  - name: Kasalla War
    tag: P0Q220PY
```

**Comment by smlbiobot** [comment]
We don’t support line as it is not a URL link

```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/kasalla.jpg
  description: Deutsche, ständig wachsende, Clash Royale Family. Wir haben ein eSport Team, bei dem auch neue sich beweisen können und veranstalten regelmäßig Turniere. Außerdem haben wir einen gut organisierten Discord Server, der täglich Mitglieder aus unseren Clans an sich zieht. Aufgrund unserer vielen Clans ist ein jedermann bei uns gut aufgehoben. Was willst du mehr? JOIN NOW!>
  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://instagram.com/kasallacr
clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: Kasalla Squad
    tag: 9JUU2YQG
  - name: Kasalla Gala™
    tag: 9G0YRQGG
  - name: Kasalla Castle
    tag: P9G0R8G0
  - name: Kasalla Seebs
    tag: 9R99Y29L
  - name: Kasalla War
    tag: P0Q220PY
```
