### ISSUE TITLE
BS Esport Team

### ISSUE THREAD

**Issue by Spikehead** [RoyaleAPI/cr-api-ux#190]
```yaml
name: BS ESPORT TEAM
key: BS
color: purple
track: true
emblem: Elixir_01
feature: true
info:
  logo: http://www.bsesport.eu/wp-content/uploads/2018/07/avatar.jpg
  description: >
    BS Esport Team est une équipe Esport Francophone sur Clash Royale.
    15 clans actuellement, répartis dans 5 pays différents (France, Suisse, Canada, Luxembourg, Belgique)
  social:
    - twitter: http://twitter.com/bsesportteam
    - facebook: https://www.facebook.com/BS-Esport-Team-230159587760659/
    - instagram : https://www.instagram.com/bsesport/
clans:
  - name: BS Esport PRO
    tag: P22VP929
  - name: BS Esport
    tag: 9GGLPGL2
  - name: BS Esport SWISS
    tag: P29QLPGP
  - name: BS Esport LUX
    tag: PPUV80QJ
  - name: BS Esport BE
    tag: 9L99UYVR
  - name: BS Esport CAN
    tag: 9GPQQC82
  - name: BS Kings
    tag: P0YVURGY
  - name: BS Assembly
    tag: 9V89UQGL
  - name: BS Braves
    tag: 9L20UUYJ
  - name: BS Myths
    tag: 99LG89L8
  - name: BS Knights
    tag: 9GV8G0GY
  - name: BS Masters
    tag: 98R20QV2
  - name: BS Heroes
    tag: 99GVGJJG
  - name: BS C4taclysm
    tag: 9JU8JYGQ
  - name: BS Brotherhood
    tag: 9GRJRCP2
```

**Comment by smlbiobot** [comment]
```yaml
name: BS ESPORT TEAM
key: bs
color: purple
emblem: Elixir_01
info:
  logo: /static/img/brands/logo/bs.jpg
  description: >
    BS Esport Team est une équipe Esport Francophone sur Clash Royale.
    15 clans actuellement, répartis dans 5 pays différents (France, Suisse, Canada, Luxembourg, Belgique)
  social:
    - twitter: http://twitter.com/bsesportteam
    - facebook: https://www.facebook.com/BS-Esport-Team-230159587760659/
    - instagram: https://www.instagram.com/bsesport/
clans:
  - name: BS Esport PRO
    tag: P22VP929
  - name: BS Esport
    tag: 9GGLPGL2
  - name: BS Esport SWISS
    tag: P29QLPGP
  - name: BS Esport LUX
    tag: PPUV80QJ
  - name: BS Esport BE
    tag: 9L99UYVR
  - name: BS Esport CAN
    tag: 9GPQQC82
  - name: BS Kings
    tag: P0YVURGY
  - name: BS Assembly
    tag: 9V89UQGL
  - name: BS Braves
    tag: 9L20UUYJ
  - name: BS Myths
    tag: 99LG89L8
  - name: BS Knights
    tag: 9GV8G0GY
  - name: BS Masters
    tag: 98R20QV2
  - name: BS Heroes
    tag: 99GVGJJG
  - name: BS C4taclysm
    tag: 9JU8JYGQ
  - name: BS Brotherhood
    tag: 9GRJRCP2
```
