### ISSUE TITLE
Ako Roshi

### ISSUE THREAD

**Issue by diegoam84** [RoyaleAPI/cr-api-ux#192]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Ako Roshi
key: ako
color: red
emblem: YingYang_02
info:
  logo: https://cdn.discordapp.com/attachments/452220329126002690/461598142454956032/logo.png
  description: >
    **Ako Roshi** is an eSports organization dedicated to mobile games founded by LokkeDerBoss in January of 2018. We started in Clash Royale with a small German team but with high hopes. Since there we were growing bigger and faster until today.
  social:
    - twitter: https://twitter.com/AkoRoshiGG
    - discord: http://discord.gg/akoroshi
    - website: https://www.akoroshi.com
    - instagram: https://www.instagram.com/akoroshi/
    - email: mailto:akoroshicr@gmail.com
clans:
  - name: Ako Roshi
    tag: 9QPLCG20
  - name: 47 Ronins
    tag: 9QCVLG29
 ```

**Comment by smlbiobot** [comment]
```yaml
name: Ako Roshi
key: ako
color: red
emblem: YingYang_02
info:
  logo: /static/img/brands/logo/ako.png
  description: >
    **Ako Roshi** is an eSports organization dedicated to mobile games founded by LokkeDerBoss in January of 2018. We started in Clash Royale with a small German team but with high hopes. Since there we were growing bigger and faster until today.
  social:
    - twitter: https://twitter.com/AkoRoshiGG
    - discord: http://discord.gg/akoroshi
    - website: https://www.akoroshi.com
    - instagram: https://www.instagram.com/akoroshi/
    - email: mailto:akoroshicr@gmail.com
clans:
  - name: Ako Roshi
    tag: 9QPLCG20
  - name: 47 Ronins
    tag: 9QCVLG29
```
