### ISSUE TITLE
Please add our family BORN IN UA

### ISSUE THREAD

**Issue by coderov** [RoyaleAPI/cr-api-ux#193]
```yml
name: BORN IN UA alliance
key: born-in-ua
color: blue
emblem: Flame_02.png
info:
  logo: http://born-in-ua.site/img/logolinks.png
  description: >
    Найкраший Український альянс Clash Royale
    BORN IN UA -- BORN IN UA ½ -- BORN IN UA ¼ -- BORN IN UA ACD -- BORN IN UA RES
    http://born-in-ua.top/
    http://born-in-ua.site/
    Founded by amorphis
  social:
    - twitter: https://twitter.com/borninua_clan
    - discord: https://discordapp.com/channels/402954691849224192/402955751712096256
    - youtube: https://www.youtube.com/channel/UCAAa6TPlEJF0W6XEIvaP-Eg
    - website: http://born-in-ua.top/
    - instagram: https://www.instagram.com/borninua.alliance/
    - facebook: https://www.facebook.com/groups/borninua/
    - email: mailto:borninua.alliance@gmail.com
clans:
  - name: BORN IN UA
    tag: UQY0GJ9
  - name: BORN IN UA ½
    tag: 88JURQLJ
  - name: BORN IN UA ¼
    tag: 8229YCVV
  - name: BORN IN UA ACD
    tag: RVJCJP9
  - name: BORN IN UA RES
    tag: 9YVGVV9P
```

**Comment by smlbiobot** [comment]
```yml
name: BORN IN UA alliance
key: born-in-ua
color: blue
emblem: Flame_02.png
info:
  logo: /static/img/brands/logo/born-in-ua.png
  description: >
    Найкраший Український альянс Clash Royale<br/>
    BORN IN UA -- BORN IN UA ½ -- BORN IN UA ¼ -- BORN IN UA ACD -- BORN IN UA RES<br/>
    http://born-in-ua.top/<br/>
    http://born-in-ua.site/<br/>
    Founded by amorphis<br/>
  social:
    - twitter: https://twitter.com/borninua_clan
    - discord: https://discordapp.com/channels/402954691849224192/402955751712096256
    - youtube: https://www.youtube.com/channel/UCAAa6TPlEJF0W6XEIvaP-Eg
    - website: http://born-in-ua.top/
    - instagram: https://www.instagram.com/borninua.alliance/
    - facebook: https://www.facebook.com/groups/borninua/
    - email: mailto:borninua.alliance@gmail.com
clans:
  - name: BORN IN UA
    tag: UQY0GJ9
  - name: BORN IN UA ½
    tag: 88JURQLJ
  - name: BORN IN UA ¼
    tag: 8229YCVV
  - name: BORN IN UA ACD
    tag: RVJCJP9
  - name: BORN IN UA RES
    tag: 9YVGVV9P
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/born-in-ua

**Comment by coderov** [comment]
thx much, but can You please change our homepage to born-in-ua.site

**Comment by smlbiobot** [comment]
```yaml
name: BORN IN UA alliance
key: born-in-ua
color: blue
emblem: Flame_02.png
info:
  logo: /static/img/brands/logo/born-in-ua.png
  description: >
    Найкраший Український альянс Clash Royale<br/>
    BORN IN UA -- BORN IN UA ½ -- BORN IN UA ¼ -- BORN IN UA ACD -- BORN IN UA RES<br/>
    http://born-in-ua.top/<br/>
    http://born-in-ua.site/<br/>
    Founded by amorphis<br/>
  social:
    - twitter: https://twitter.com/borninua_clan
    - discord: https://discordapp.com/channels/402954691849224192/402955751712096256
    - youtube: https://www.youtube.com/channel/UCAAa6TPlEJF0W6XEIvaP-Eg
    - website: http://born-in-ua.site/
    - instagram: https://www.instagram.com/borninua.alliance/
    - facebook: https://www.facebook.com/groups/borninua/
    - email: mailto:borninua.alliance@gmail.com
clans:
  - name: BORN IN UA
    tag: UQY0GJ9
  - name: BORN IN UA ½
    tag: 88JURQLJ
  - name: BORN IN UA ¼
    tag: 8229YCVV
  - name: BORN IN UA ACD
    tag: RVJCJP9
  - name: BORN IN UA RES
    tag: 9YVGVV9P
```
I don’t see the bug that you mentioned

**Comment by coderov** [comment]
Hello, first of all - thanks much for such beautiful resource.
Please, renew my alliance info:

```yaml
name: BORN IN UA alliance
key: born-in-ua
color: blue
emblem: Flame_02.png
info:
  logo: /static/img/brands/logo/born-in-ua.png
  description: >
    Найкраший Український альянс Clash Royale<br/>
    BORN IN UA -- BORN IN UA ½ -- BORN IN UA ¼ -- BORN IN UA JNR -- BORN IN UA ACD -- BORN IN UA RES<br/>
    http://born-in-ua.top/<br/>
    http://bit.do/borninua/ (скорочена ссилка)<br/>
    Founded by amorphis<br/>
  social:
    - twitter: https://twitter.com/borninua_clan
    - discord: https://discordapp.com/channels/402954691849224192/402955751712096256
    - youtube: https://www.youtube.com/channel/UCAAa6TPlEJF0W6XEIvaP-Eg
    - website: http://born-in-ua.top/
    - instagram: https://www.instagram.com/borninua.alliance/
    - facebook: https://www.facebook.com/groups/borninua/
    - email: mailto:borninua.alliance@gmail.com
clans:
  - name: BORN IN UA
    tag: UQY0GJ9
  - name: BORN IN UA ½
    tag: 88JURQLJ
  - name: BORN IN UA ¼
    tag: 8229YCVV
  - name: BORN IN UA ACD
    tag: RVJCJP9
  - name: BORN IN UA JNR
    tag: 9CLOPC9U
  - name: BORN IN UA RES
    tag: 9YVGVV9P
```

**Comment by smlbiobot** [comment]
- don’t add png to emblems

```yml
name: BORN IN UA alliance
key: born-in-ua
color: blue
emblem: Flame_02
info:
  logo: /static/img/brands/logo/born-in-ua.png
  description: >
    Найкраший Український альянс Clash Royale<br/>
    BORN IN UA -- BORN IN UA ½ -- BORN IN UA ¼ -- BORN IN UA JNR -- BORN IN UA ACD -- BORN IN UA RES<br/>
    http://born-in-ua.top/<br/>
    http://bit.do/borninua/ (скорочена ссилка)<br/>
    Founded by amorphis<br/>
  social:
    - twitter: https://twitter.com/borninua_clan
    - discord: https://discordapp.com/channels/402954691849224192/402955751712096256
    - youtube: https://www.youtube.com/channel/UCAAa6TPlEJF0W6XEIvaP-Eg
    - website: http://born-in-ua.top/
    - instagram: https://www.instagram.com/borninua.alliance/
    - facebook: https://www.facebook.com/groups/borninua/
    - email: mailto:borninua.alliance@gmail.com
clans:
  - name: BORN IN UA
    tag: UQY0GJ9
  - name: BORN IN UA ½
    tag: 88JURQLJ
  - name: BORN IN UA ¼
    tag: 8229YCVV
  - name: BORN IN UA ACD
    tag: RVJCJP9
  - name: BORN IN UA JNR
    tag: 9CLOPC9U
  - name: BORN IN UA RES
    tag: 9YVGVV9P
```
