### ISSUE TITLE
Pr3sence Gaming

### ISSUE THREAD

**Issue by Sanzcr** [RoyaleAPI/cr-api-ux#194]
```yaml
name: Pr3sence Gaming
key: Pr3
color: Violet
emblem: Twin_Peaks_01
info:
  logo: Twin_Peaks_01
  description: >
Pr3sence Gaming es un equipo competitivo creado en 2017 que abarca unos 7 juegos.
  
  social:
    - twitter: https://twitter.com/Pr3senceGaming
    - discord: https://discord.gg/hbPgsFX
    - twitch: https://www.twitch.tv/pr3sencetv
    - youtube: https://www.youtube.com/channel/
    - website: https://sqonlinestore.com/collections/pr3sence-gaming
    - email: mailto: pr3sencegamingoficial@gmail.com
clans:
  - name: Pr3sence™
    tag: 8J9G9920
  - name: Pr3sence II
    tag: 8J200GUU
  - name: Pr3sence IV
    tag: 8JJP9Q9P
```

**Comment by smlbiobot** [comment]
```yml
name: Pr3sence Gaming
key: pr3
color: violet
emblem: Twin_Peaks_01
info:
  logo: /static/img/badge/Twin_Peaks_01.png
  description: >
    Pr3sence Gaming es un equipo competitivo creado en 2017 que abarca unos 7 juegos.
  social:
    - twitter: https://twitter.com/Pr3senceGaming
    - discord: https://discord.gg/hbPgsFX
    - twitch: https://www.twitch.tv/pr3sencetv
    - youtube: https://www.youtube.com/channel/
    - website: https://sqonlinestore.com/collections/pr3sence-gaming
    - email: mailto:pr3sencegamingoficial@gmail.com
clans:
  - name: Pr3sence™
    tag: 8J9G9920
  - name: Pr3sence II
    tag: 8J200GUU
  - name: Pr3sence IV
    tag: 8JJP9Q9P
```
