### ISSUE TITLE
TeamLiquid NA - Update

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#195]
``` yaml
name: Team Liquid NA
key: LiquidNA
color: blue
emblem: flag_d_04
info:
  logo: https://drive.google.com/file/d/1xyRHd7zCG1P-Ptgf6vORwbfXlP0qSx8q/view?usp=sharing
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 2000 members** spread over NA, EU, and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: Team Liquid
    tag: 9YU2PQRV
  - name: Team Liquid 2
    tag: V8GRLCQ
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL Smash Elite
    tag: 820QC80V
  - name: TL Cyclone
    tag: 9QVYYYV0
  - name: TL Nitro
    tag: 9YYLQ99L

**Comment by smlbiobot** [comment]
```yml
name: Team Liquid NA
key: LiquidNA
color: blue
emblem: flag_d_04
info:
  logo: /static/img/brands/logo/teamliquid.png
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 2000 members** spread over NA, EU, and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: Team Liquid
    tag: 9YU2PQRV
  - name: Team Liquid 2
    tag: V8GRLCQ
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL Smash Elite
    tag: 820QC80V
  - name: TL Cyclone
    tag: 9QVYYYV0
  - name: TL Nitro
    tag: 9YYLQ99L
```
