### ISSUE TITLE
TeamLiquid EU - Update

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#196]
```yaml
name: Team Liquid EU
key: LiquidEU
color: blue
emblem: flag_d_04
info:
  logo: https://drive.google.com/file/d/1xyRHd7zCG1P-Ptgf6vORwbfXlP0qSx8q/view?usp=sharing
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 2000 members** spread over NA, EU, and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid FR
    tag: 98PYR0VJ
  - name: TL Fluor FR
    tag: 9UP2JY2P
  - name: TeamLiquid BL
    tag: P0YJ0P2V
  - name: TL Solid
    tag: P888QQQ9
  - name: TeamLiquid GER
    tag: 98R22PLY
  - name: TeamLiquid HU
    tag: P09YPG9V
  - name: TeamLiquid SRB
    tag: 8J0J2RQC
  - name: TeamLiquid RO
    tag: 9JUCLVCV

**Comment by smlbiobot** [comment]
```yml
name: Team Liquid EU
key: LiquidEU
color: blue
emblem: flag_d_04
info:
  logo: /static/img/brands/logo/teamliquid-t.png
  description: >
    Established in 2016 **Team Liquid** is one of the most prominent clan families in Clash Royale with **over 2000 members** spread over NA, EU, and LATAM. Join our discord: **TL.GG/MOBILE** for more info and lots of tournaments & events!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid FR
    tag: 98PYR0VJ
  - name: TL Fluor FR
    tag: 9UP2JY2P
  - name: TeamLiquid BL
    tag: P0YJ0P2V
  - name: TL Solid
    tag: P888QQQ9
  - name: TeamLiquid GER
    tag: 98R22PLY
  - name: TeamLiquid HU
    tag: P09YPG9V
  - name: TeamLiquid SRB
    tag: 8J0J2RQC
  - name: TeamLiquid RO
    tag: 9JUCLVCV

```
