### ISSUE TITLE
Team Liquid LAN - Update (No more LATAM)

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#197]
```yaml
name: Team Liquid LAN
key: LiquidLAN
color: blue
emblem: flag_d_04
info:
  logo: https://drive.google.com/file/d/1xyRHd7zCG1P-Ptgf6vORwbfXlP0qSx8q/view?usp=sharing
  description: >
    Establecido en el 2016 **Team Liquid** es una de las familias de clanes más prominentes en Clash Royale con **más de 2000 miembros** distribuidos en NA, EU y LATAM. Únete a nuestro discord: **TL.GG/MOBILE** para más información, así como una gran variedad de torneos y eventos!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid MX
    tag: 8URY28UC
  - name: TeamLiquid MX2
    tag: 92J9RY9C
  - name: TeamLiquid MX R
    tag: 9PPJJVLQ
  - name: TeamLiquid MX Z
    tag: 9Q88CP22
  - name: TeamLiquid MX F
    tag: P2PP8L80
  - name: TeamLiquid CUBA
    tag: 9QL02L9U
  - name: TeamLiquid HN
    tag: 9LGV822C
  - name: TeamLiquid SV
    tag: 8JG8Y20R
  - name: TeamLiquid SV2
    tag: 99UL0CRJ
  - name: TeamLiquid SV3
    tag: 9LPJUVYJ

**Comment by smlbiobot** [comment]
```yml
name: Team Liquid LAN
key: LiquidLAN
color: blue
emblem: flag_d_04
info:
  logo: /static/img/brands/logo/teamliquid-t.png
  description: >
    Establecido en el 2016 **Team Liquid** es una de las familias de clanes más prominentes en Clash Royale con **más de 2000 miembros** distribuidos en NA, EU y LATAM. Únete a nuestro discord: **TL.GG/MOBILE** para más información, así como una gran variedad de torneos y eventos!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid MX
    tag: 8URY28UC
  - name: TeamLiquid MX2
    tag: 92J9RY9C
  - name: TeamLiquid MX R
    tag: 9PPJJVLQ
  - name: TeamLiquid MX Z
    tag: 9Q88CP22
  - name: TeamLiquid MX F
    tag: P2PP8L80
  - name: TeamLiquid CUBA
    tag: 9QL02L9U
  - name: TeamLiquid HN
    tag: 9LGV822C
  - name: TeamLiquid SV
    tag: 8JG8Y20R
  - name: TeamLiquid SV2
    tag: 99UL0CRJ
  - name: TeamLiquid SV3
    tag: 9LPJUVYJ
```
