### ISSUE TITLE
Team Liquid LAS - Update (No more LATAM)

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/cr-api-ux#198]
```yaml
name: Team Liquid LAS
key: LiquidLAS
color: blue
emblem: flag_d_04
info:
  logo: https://drive.google.com/file/d/1xyRHd7zCG1P-Ptgf6vORwbfXlP0qSx8q/view?usp=sharing
  description: >
    Establecido en el 2016 **Team Liquid** es una de las familias de clanes más prominentes en Clash Royale con **más de 2000 miembros** distribuidos en NA, EU y LATAM. Únete a nuestro discord: **TL.GG/MOBILE** para más información, así como una gran variedad de torneos y eventos!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid CO
    tag: 9QLLG92U
  - name: TeamLiquid VE
    tag: V0GL8C8
  - name: TeamLiquid VE2
    tag: 889CQU88
  - name: TeamLiquid VE A
    tag: 8R8LJYU2
  - name: TeamLiquid VE R
    tag: 8J8UVQL0
  - name: TeamLiquid VE Z
    tag: 8L98R2JV
  - name: TeamLiquid PE
    tag: 8JR0LQ8U
  - name: TeamLiquid PE2
    tag: 98LJJLR9
  - name: TeamLiquid PE3
    tag: 8CPJV28G
  - name: TeamLiquid PE4
    tag: 8G90Y22R
  - name: TeamLiquid PEI
    tag: 980VLV0J
  - name: TeamLiquid PE X
    tag: 9YR8L8R8
  - name: TeamLiquid PE Y
    tag: 9JL98G9J
  - name: TeamLiquid PE Z
    tag: P80J882L
  - name: TeamLiquid ARG
    tag: P22C00YR

**Comment by smlbiobot** [comment]
```yml
name: Team Liquid LAS
key: LiquidLAS
color: blue
emblem: flag_d_04
info:
  logo: /static/img/brands/logo/teamliquid-t.png
  description: >
    Establecido en el 2016 **Team Liquid** es una de las familias de clanes más prominentes en Clash Royale con **más de 2000 miembros** distribuidos en NA, EU y LATAM. Únete a nuestro discord: **TL.GG/MOBILE** para más información, así como una gran variedad de torneos y eventos!
  social:
    - website: https://www.teamliquid.com/
    - discord: http://TL.GG/MOBILE
    - twitch: https://www.twitch.tv/teamliquid
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - facebook: https://www.facebook.com/teamliquid/
    - instagram: https://www.instagram.com/teamliquid/
    - twitter: http://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid CO
    tag: 9QLLG92U
  - name: TeamLiquid VE
    tag: V0GL8C8
  - name: TeamLiquid VE2
    tag: 889CQU88
  - name: TeamLiquid VE A
    tag: 8R8LJYU2
  - name: TeamLiquid VE R
    tag: 8J8UVQL0
  - name: TeamLiquid VE Z
    tag: 8L98R2JV
  - name: TeamLiquid PE
    tag: 8JR0LQ8U
  - name: TeamLiquid PE2
    tag: 98LJJLR9
  - name: TeamLiquid PE3
    tag: 8CPJV28G
  - name: TeamLiquid PE4
    tag: 8G90Y22R
  - name: TeamLiquid PEI
    tag: 980VLV0J
  - name: TeamLiquid PE X
    tag: 9YR8L8R8
  - name: TeamLiquid PE Y
    tag: 9JL98G9J
  - name: TeamLiquid PE Z
    tag: P80J882L
  - name: TeamLiquid ARG
    tag: P22C00YR
```
