### ISSUE TITLE
Family Config - Tiquicia Force

### ISSUE THREAD

**Issue by Cristian92** [RoyaleAPI/cr-api-ux#201]
```yml
name: Tiquicia Family
key: Tiquicia
color: Yellow
track: true
emblem: A_Char_Prince_03.png
feature: true
vip: true
info:
  logo: https://gyazo.com/9fa3a5b0368f6fc021b6b15d8483dd8c
  description: >
    Clanes costarricenses en top local dedicados 100% a las guerras de clanes!
  social:
    - twitter: https://twitter.com/TiquiciaForce
clans:
  - name: Tiquicia Force
    tag: 2PRP2GJ2
  - name: Tiquicia Squad
    tag: 2909VC00
  - name: Tiquicia Chiefs
    tag: 2VCPJG8Y
```

**Comment by smlbiobot** [comment]
```yml
name: Tiquicia Family
key: tiquicia
color: yellow
emblem: A_Char_Prince_03
info:
  logo: /static/img/brands/logo/tiquicia.png
  description: >
    Clanes costarricenses en top local dedicados 100% a las guerras de clanes!
  social:
    - twitter: https://twitter.com/TiquiciaForce
clans:
  - name: Tiquicia Force
    tag: 2PRP2GJ2
  - name: Tiquicia Squad
    tag: 2909VC00
  - name: Tiquicia Chiefs
    tag: 2VCPJG8Y
```
