### ISSUE TITLE
SirTagCR Clan Family request

### ISSUE THREAD

**Issue by ChivalrousGhost** [RoyaleAPI/cr-api-ux#202]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: SirTagCR
key: sirtagcr
color: purple
emblem: Star_Shine_03
sort: trophy
info:
  logo: https://static-cdn.jtvnw.net/jtv_user_pictures/sirtagcr-profile_image-5685a7f075d718b8-300x300.png
  description: >
    Saucin' out a good luck, going hard in the paint, and that's how you assert dominance.


    Instructions to join the SirTagCR clan family on the how-to-join-clan channel on Discord.


    Link below.
  social:
    - discord: https://discord.gg/HfBdGQ6
    - twitch: https://www.twitch.tv/sirtagcr
    - youtube: https://www.youtube.com/channel/UCvje1_OaZUZVZDzxeyOFf6A
    - twitter: https://twitter.com/sirtagcr
    - instagram: https://www.instagram.com/sirtagcr/?hl=en
clans:
  - name: Twitch SirTagCR
    tag: 29YU089C
  - name: Society of Sirs
    tag: PP08RGGL
  - name: Chivalrous Sirs
    tag: 9G2PUJ8V
- name: Superior Sirs
    tag: 9J9VG8LC
```

**Comment by ChivalrousGhost** [comment]
I'm not sure if I did the logo correctly.  That link is a location that is currently hosting the logo, but I doubt if we can outside link it.  I'm attaching the logo here if that is what I was supposed to do.  Let me know if I need to fix it and resend.
![sirtagcr_logo_300x300](https://user-images.githubusercontent.com/41247589/42739980-33a4bca6-8866-11e8-83a7-f48fa79a89b9.png)

**Comment by smlbiobot** [comment]
```yml
name: SirTagCR
key: sirtagcr
color: purple
emblem: Star_Shine_03
sort: trophy
info:
  logo: /static/img/brands/logo/sirtagcr.png
  description: >
    Saucin' out a good luck, going hard in the paint, and that's how you assert dominance.


    Instructions to join the SirTagCR clan family on the how-to-join-clan channel on Discord.


    Link below.
  social:
    - discord: https://discord.gg/HfBdGQ6
    - twitch: https://www.twitch.tv/sirtagcr
    - youtube: https://www.youtube.com/channel/UCvje1_OaZUZVZDzxeyOFf6A
    - twitter: https://twitter.com/sirtagcr
    - instagram: https://www.instagram.com/sirtagcr/?hl=en
clans:
  - name: Twitch SirTagCR
    tag: 29YU089C
  - name: Society of Sirs
    tag: PP08RGGL
  - name: Chivalrous Sirs
    tag: 9G2PUJ8V
  - name: Superior Sirs
    tag: 9J9VG8LC
```
