### ISSUE TITLE
Ocean's Fifty (Add Clan Family)

### ISSUE THREAD

**Issue by CarlosPuigGC** [RoyaleAPI/cr-api-ux#205]
```yaml
name: Ocean's Clan Family
key: Ocean's Fifty
color: black
emblem: A_Char_Prince_03
info: Active player? Looking for a family? Join our clan in Clash Royale. Let's grow stronger together!
  logo: ![ocean s fifty facebook 1](https://user-images.githubusercontent.com/24650978/41674342-057e40c2-74c0-11e8-9cbb-b55ee13394f0.png)

  description: >
    **Ocean's Fifty** is a community team competing in the European region of Clash Royale League.
    The clan was created by the Sabadell brothers in 2017. Pol, Albert and Marc soon began to bring in 
    friends and acquaintances to increase the members of the team. Nowadays Ocean's Fifty is one of the 
    EU Top 200 clans.

    The clan is a place for everyone, especially for active, young and competitive players.
    We all share a fellow passion for the game, are friendly, always donate and help each other out having 
    a common goal in mind: to improve our skills and have a great time!

    **Join Ocean's Fifty. Enjoy the game.**

  social:
    - instagram: https://www.instagram.com/oceansfifty/
    - facebook: https://facebook.com/OceansFifty/
    - email: mailto:oceansfiftyclan@gmail.com

clans:
  - name: Ocean's Fifty
    tag: 2J0LGV2J
  - name: Ocean's Rookies
    tag: 9CPU8YL2
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/of

```yml
name: Ocean's Clan Family
key: of
color: black
emblem: A_Char_Prince_03
info:
  logo: /static/img/brands/logo/oceans_fifty.png

  description: >
    **Ocean's Fifty** is a community team competing in the European region of Clash Royale League.
    The clan was created by the Sabadell brothers in 2017. Pol, Albert and Marc soon began to bring in
    friends and acquaintances to increase the members of the team. Nowadays Ocean's Fifty is one of the
    EU Top 200 clans.

    The clan is a place for everyone, especially for active, young and competitive players.
    We all share a fellow passion for the game, are friendly, always donate and help each other out having
    a common goal in mind: to improve our skills and have a great time!

    **Join Ocean's Fifty. Enjoy the game.**

  social:
    - instagram: https://www.instagram.com/oceansfifty/
    - facebook: https://facebook.com/OceansFifty/
    - email: mailto:oceansfiftyclan@gmail.com

clans:
  - name: Ocean's Fifty
    tag: 2J0LGV2J
  - name: Ocean's Rookies
    tag: 9CPU8YL2
```
