### ISSUE TITLE
ohiolegends.yml

### ISSUE THREAD

**Issue by shader79** [RoyaleAPI/cr-api-ux#208]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Ohio Legends
key: ohiolegends
color: Black
track: true
emblem: Flame_02
feature: true
vip: true
info:
  description: >
The Ohio Legends family is the oldest and biggest Clash Royale family in Ohio! The family is designed to train and groom players as the ascend the ranks until they may join the glory that is Ohio Legends - a nationally ranked and world famous clan. All are welcome, but few will be up for the challenge. Active players are a must! Clan leaders comb through mountains of data ensuring our members are in top competitive shape. Join the Family. Become a Legend.
  social:
     - discord: http://discord.me/ohiolegends
- facebook: https://www.facebook.com/groups/ohiolegends/
    - reddit: http://www.reddit.com/r/OhioLegends/
 
clans:
  - name: Ohio Legends
    tag: 9L82QG8G
  - name: Ohio Legends 2
    tag: R0U08JL
  - name: Ohio Legends 3
    tag: 2PPPC9V2
  - name: Ohio Legends 4
    tag: 9CCV2QLY
  - name: OhioLegends WAR
    tag: 9RQR8RYQ

```
