### ISSUE TITLE
Siege Royale Clan Fam!

### ISSUE THREAD

**Issue by Peqqt** [RoyaleAPI/cr-api-ux#210]
```yaml
name: Siege Royale Gaming
key: SR
color: red
emblem: A_Char_Pekka_02
info: 
  logo: https://dewey.tailorbrands.com/production/brand_version_mockup_image/970/1001106970_9f6062c9-9cc7-40ad-8972-37f09dedbf81.png?cb=1531959093
  description: >
We nice, we kool, we active!  Come and join us at any of those clans!  Active and ready, we always thrive for consistent improvements and commitment.  
  social:
    - discord: https://discord.gg/N9hCCax       
clans:
  - name: Siege Royale
    tag: #8CVP8VU
  - name: Siege Royale 2
    tag: #9YC2G8G9
```

**Comment by smlbiobot** [comment]
```yml
name: Siege Royale Gaming
key: srg
color: red
emblem: A_Char_Pekka_02
info:
  logo: /static/img/brands/logo/siege_royale.png
  description: >
    We nice, we kool, we active!  Come and join us at any of those clans!  Active and ready, we always thrive for consistent improvements and commitment.
  social:
    - discord: https://discord.gg/N9hCCax
clans:
  - name: Siege Royale
    tag: 8CVP8VU
  - name: Siege Royale 2
    tag: 9YC2G8G9
```
need to use srg coz sr is already taken
