### ISSUE TITLE
SirTagCR Family Page Discord Link Update

### ISSUE THREAD

**Issue by ChivalrousGhost** [RoyaleAPI/cr-api-ux#212]
```yaml
name: SirTagCR
key: sirtagcr
color: purple
emblem: Star_Shine_03
sort: trophy
info:
  logo: /static/img/brands/logo/sirtagcr.png
  description: >
    Saucin' out a good luck, going hard in the paint, and that's how you assert dominance.


    Instructions to join the SirTagCR clan family on the how-to-join-clan channel on Discord.


    Discord.gg/SirTag or follow the link below.
  social:
    - discord: https://discord.gg/SirTag
    - twitch: https://www.twitch.tv/sirtagcr
    - youtube: https://www.youtube.com/channel/UCvje1_OaZUZVZDzxeyOFf6A
    - twitter: https://twitter.com/sirtagcr
    - instagram: https://www.instagram.com/sirtagcr/?hl=en
clans:
  - name: Twitch SirTagCR
    tag: 29YU089C
  - name: Society of Sirs
    tag: PP08RGGL
  - name: Chivalrous Sirs
    tag: 9G2PUJ8V
  - name: Superior Sirs
    tag: 9J9VG8LC
```
