### ISSUE TITLE
[Family] Finlandia

### ISSUE THREAD

**Issue by aarneng** [RoyaleAPI/cr-api-ux#213]
```yaml
name: Finlandia
key: Finlandia
color: Black
emblem: flag_d_04
info:
  logo: https://ibb.co/n0cEjJ
  description: >
    Finlandia-klaaniperhe on suomalainen peliyhteisö suunniteltu kaikenikäisille ja kaikentasoisille pelaajille. Tervetuloa mukaan!
Finlandia- clan family is a gaming community from Finland designed for players of every age and skill group. All Finnish players welcome!

  social:
    - discord: https://discordapp.com/invite/D3mfcfR
    - website: http://clashofclans.fi/clash-royale/
  - name: FINLANDIA
    tag: 9QR2
  - name: FINLANDIA II
    tag: 2LOCJ
  - name: FINLANDIA III
    tag: 809JR
  - name: FINLANDIA IV
     tag: P2R8C
  - name: FINLANDIA V
     tag: R2YOQ
  - name: FINLANDIA VI
     tag: 22LL8V
  - name: FINLANDIA VII
     tag: 209LRQV
  - name: FINLANDIA VIII
     tag: CYOGVL9
  - name: FINLANDIA IX
     tag: Y2QPPUG
  - name: FINLANDIA eläke
     tag: 9GQV8
  - name: Varhaiseläke
     tag: UL9UQ
```

**Comment by smlbiobot** [comment]
```yml
name: Finlandia
key: finlandia
color: Black
emblem: flag_d_04
info:
  logo: /static/img/brands/logo/finlandia.jpg
  description: >
    Finlandia-klaaniperhe on suomalainen peliyhteisö suunniteltu kaikenikäisille ja kaikentasoisille pelaajille. Tervetuloa mukaan!
    Finlandia- clan family is a gaming community from Finland designed for players of every age and skill group. All Finnish players welcome!

  social:
    - discord: https://discordapp.com/invite/D3mfcfR
    - website: http://clashofclans.fi/clash-royale/
clans:
  - name: FINLANDIA
    tag: 9QR2
  - name: FINLANDIA II
    tag: 2L0CJ
  - name: FINLANDIA III
    tag: 809JR
  - name: FINLANDIA IV
    tag: P2R8C
  - name: FINLANDIA V
    tag: R2Y0Q
  - name: FINLANDIA VI
    tag: 22LL8V
  - name: FINLANDIA VII
    tag: 209LRQV
  - name: FINLANDIA VIII
    tag: CY0GVL9
  - name: FINLANDIA IX
    tag: Y2QPPUG
  - name: FINLANDIA eläke
    tag: 9GQV8
  - name: Varhaiseläke
    tag: UL9UQ
```
