### ISSUE TITLE
[Family] Nights

### ISSUE THREAD

**Issue by HefestoGod** [RoyaleAPI/cr-api-ux#214]
```yaml
name: Nights Family
key: nhtf
color: blue
emblem: Traditional_Star_05
info:
  logo: N/A
  description: > Familia de 6 Clanes // Equipo Competitivo //  Torneos de 1.2 k

  social:
    - twitter: http://twitter.com/StarNights1

clans:
  - name: StarNights
    tag: 9GQ90GPV
  - name: Moonights
    tag: 98Y08YJP
  - name: SunNight's LZC
    tag: P2LP92R2
 - name: SkyNights
    tag: 9VYG0YUG
 - name: FenixNights
    tag: 9R99Y28V
 - name: GalaxyNights
    tag: P2G099G9
 ```

**Comment by smlbiobot** [comment]
```yml
name: Nights Family
key: nhtf
color: blue
emblem: Traditional_Star_05
info:
  description: Familia de 6 Clanes // Equipo Competitivo //  Torneos de 1.2 k
  social:
    - twitter: http://twitter.com/StarNights1
clans:
  - name: StarNights
    tag: 9GQ90GPV
  - name: Moonights
    tag: 98Y08YJP
  - name: SunNight's LZC
    tag: P2LP92R2
  - name: SkyNights
    tag: 9VYG0YUG
  - name: FenixNights
    tag: 9R99Y28V
  - name: GalaxyNights
    tag: P2G099G9
```
