### ISSUE TITLE
[Family] All Blacks CR - NZ's top CR clan (allblackscr.yml)

### ISSUE THREAD

**Issue by IAmAKiwiCoder** [RoyaleAPI/cr-api-ux#215]
```yaml
name: All Blacks
key: allblackscr
color: black
emblem: Flame_04
info:
  logo: https://pbs.twimg.com/profile_images/1013667138328936449/aij9FE_3_400x400.jpg
  description: >
    **All Blacks** is New Zealand's top ranked ladder and war clan. 
Home to the largest Clash Royale family with 5 active clans, the clan was driven by the success of bringing together some of New Zealand's top local clash royale talent to create a strong family and clash focused environment that found success and rose to the top of the NZ leaderboards. 
Today, 4 of the 5 sit well established in the top 20 of the NZ leaderboards with the main clan sitting firmly in 1st. We a proud to have contributed to making the New Zealand Clash Royale community as great as it currently is.


  social:
    - twitter: http://twitter.com/allblackscr

clans:
  - name: All Blacks
    tag: 2LJV00J9
  - name: All Blacks 2.0
    tag: 8LQLGQR
  - name: All Blacks 3.0
    tag: 292C0LUV
  - name: All Blacks 4.0
    tag: C0C9PQV
  - name: All Blacks 5.0
    tag: 8LUPQQLR
```

**Comment by smlbiobot** [comment]
```yml
name: All Blacks
key: allblackscr
color: black
emblem: Flame_04
info:
  logo: /static/img/brands/logo/allblacks.jpg
  description: >
    **All Blacks** is New Zealand's top ranked ladder and war clan.
    Home to the largest Clash Royale family with 5 active clans, the clan was driven by the success of bringing together some of New Zealand's top local clash royale talent to create a strong family and clash focused environment that found success and rose to the top of the NZ leaderboards.
    Today, 4 of the 5 sit well established in the top 20 of the NZ leaderboards with the main clan sitting firmly in 1st. We a proud to have contributed to making the New Zealand Clash Royale community as great as it currently is.

  social:
    - twitter: http://twitter.com/allblackscr
clans:
  - name: All Blacks
    tag: 2LJV00J9
  - name: All Blacks 2.0
    tag: 8LQLGQR
  - name: All Blacks 3.0
    tag: 292C0LUV
  - name: All Blacks 4.0
    tag: C0C9PQV
  - name: All Blacks 5.0
    tag: 8LUPQQLR
```
