### ISSUE TITLE
[Family] Legend Family

### ISSUE THREAD

**Issue by zilonglich** [RoyaleAPI/cr-api-ux#216]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:LegendUnion
key:LegendCN
color:RED
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Legend
    tag: 8LPCRPV
  - name:胸怀天下，心存仁义
    tag:8LU2Y9PL
```

**Comment by smlbiobot** [comment]
```yml
name: LegendUnion
key: LegendCN
color: red
emblem: Star_Shine_02
clans:
  - name: Legend
    tag: 8LPCRPV
  - name: 胸怀天下，心存仁义
    tag: 8LU2Y9PL
```
