### ISSUE TITLE
[Family] PANIC

### ISSUE THREAD

**Issue by SnnowRoyale** [RoyaleAPI/cr-api-ux#217]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: PANIC
key: panic
color: red
emblem: Crown_01
info:
  logo: https://i.imgur.com/meN5no7.jpg
  description: > Família **PANIC**, sempre em constante evolução.
                         _Feel the PANIC!_
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
 
clans:
  - name: PANIC
    tag: 9CLCUVLQ
  - name: PANIC United
    tag: 9JRPRVRU
```

**Comment by smlbiobot** [comment]
```yml
name: PANIC
key: panic
color: red
emblem: Crown_01
info:
  logo: /static/img/brands/logo/panic.jpg
  description: >
    Família **PANIC**, sempre em constante evolução.


    *Feel the PANIC!*
clans:
  - name: PANIC
    tag: 9CLCUVLQ
  - name: PANIC United
    tag: 9JRPRVRU
```
