### ISSUE TITLE
[Family]Family3000

### ISSUE THREAD

**Issue by fofo2313** [RoyaleAPI/cr-api-ux#219]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 三千世界
key: 3000
color: RED
emblem: flag_j_03
info:
  description: >
         九山八海, 是一世界. 千界三乘, 无坚不断! 


          欢迎四海朋友相聚畅聊. 常驻须部落战高胜率. 


           Wechat微信: 17031259. Proved Skills Required.
    
clans:
  - name: 3000 worlds
    tag: 22Y2RU9R
  - name: 3000 rivers
    tag: 9Y9QLUV9
  - name: 300
    tag: 9gp88
```

**Comment by smlbiobot** [comment]
Ran into some problems with key being only integer, so had to add “w” at end:

```yml
name: 三千世界
key: 3000w
color: red
emblem: flag_j_03
info:
  description: >
    九山八海, 是一世界. 千界三乘, 无坚不断!


    欢迎四海朋友相聚畅聊. 常驻须部落战高胜率.


    Wechat微信: 17031259. Proved Skills Required.
clans:
  - name: 3000 worlds
    tag: 22Y2RU9R
  - name: 3000 rivers
    tag: 9Y9QLUV9
  - name: 300
    tag: 9GP88
```
