### ISSUE TITLE
[Family] Canadian

### ISSUE THREAD

**Issue by Raze17** [RoyaleAPI/cr-api-ux#221]
```yaml
name: Canadian
key: canadian
color: red
emblem: flag_j_02
info:
  logo: N/A
  description: >
Discord: bit.ly/ClashCanada 💠 Family: Maple Glory, Canadian Storm 💠 Constant wars➡️Participation Optional 💠 RoyaleAPI.com
    Long paragraphs with markdown syntax.

    - discord: https://discord.gg/aDhYUDs
    - youtube: https://www.youtube.com/nellogaming
    - website: https://sites.google.com/view/clashcanada
    - email: lgoCanadian@gmail.com
clans:
  - name: Maple Glory
    tag: 28PLGGYV
```
