### ISSUE TITLE
[Family] one belt and road

### ISSUE THREAD

**Issue by fofo2313** [RoyaleAPI/cr-api-ux#222]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 一路家族
key: one road
color: red
emblem: Diamond_01
info:
  description: >
    愿每位队友有繁花相簇，星辰相伴，笙歌相随。


    诚招各路大神同行，享受生活，快乐游戏。


  （仅招华人玩家，进部落请加女首领微信541726962，群里美女如云，更有天梯前三十的大佬指导技术）

clans:
  - name: 一路繁花
    tag: 9u99q9rc
  - name: 一路星辰
    tag: 9cqpr2y2
  - name: 一路笙歌
    tag: pq2glqlc
```

**Comment by smlbiobot** [comment]
```yml
name: 一路家族
key: oneroad
color: red
emblem: Diamond_01
info:
  description: >
    愿每位队友有繁花相簇，星辰相伴，笙歌相随。


    诚招各路大神同行，享受生活，快乐游戏。


    （仅招华人玩家，进部落请加女首领微信541726962，群里美女如云，更有天梯前三十的大佬指导技术）
clans:
  - name: 一路繁花
    tag: 9U99Q9RC
  - name: 一路星辰
    tag: 9CQPR2Y2
  - name: 一路笙歌
    tag: PQ2GLQLC
```
