### ISSUE TITLE
[Family] Elitists Clan Family Update - Added New Clans 

### ISSUE THREAD

**Issue by Evofinis** [RoyaleAPI/cr-api-ux#223]
```yml
name: Elitists Clan Family
key: elitists
color: blue
emblem: Sword_01
sort: trophy
info:
  logo: https://github.com/Evofinis/royale-api/blob/master/eLogo.png
  description: >
    Elitists is an International Clan Family whose primary goal is to have fun while maintaining a strong 
    presence in the rankings.
    Our clans are both casual and competitive, so newcomers will definitely have a place to fit in!


  social:
    - website: https://elitistsclan.weebly.com
    - discord: https://discord.gg/K3gRDsD
clans:
- name: Elitists
    tag: 8CGUJ99
  - name: Elitists Royale
    tag: QJC2YL8
  - name: Elitists Inc.
    tag: R9CCGJ2
  - name: Atma Force
    tag: 8Y2URQL2
  - name: Atma Folks
    tag: P02RQCYG
```
