### ISSUE TITLE
Final Imperium Clan Family

### ISSUE THREAD

**Issue by SuitingUncle620** [RoyaleAPI/cr-api-ux#224]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Final Imperium
key: Final Imperium
color: Teal
emblem: flag_j_03
info: 
  logo: https://pbs.twimg.com/profile_images/1013582123024801792/fc1qInbw_400x400.jpg
  description: >
    **Final Imperium** - Welcome to the Final Imperium Family, Home to the top New Zealand Clan! 
    We are a New Zealand based Clan Family. Final Imperium has recently been established, having 
    merged with two of the top New Zealand clans, Final Form™ and NZ Imperium, to create one of the 
    strongest New Zealand Clan Communities out there. We welcome all kind of players to our 
    community, not just New Zealanders! We like banter and value the importance of maturity and have 
    zero-tolerance towards toxic behavior. Come on in and join the best New Zealand community out 
    there!
 social:
    - twitter: http://twitter.com/Final__Imperium
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Final Imperium
    tag: 9QR9JVJG
  - name:Final Imperial
    tag: 9GVPG8U0
  - name: Final Imperion
    tag: P0QCJJGL
```

**Comment by smlbiobot** [comment]
- Please don’t add social links that are empty
- 3rd clan tag wrong but I’ve searched for it
- key must be one word

Revised:
```yml
name: Final Imperium
key: final-imperium
color: Teal
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/final-imperium.jpg
  description: >
    **Final Imperium** - Welcome to the Final Imperium Family, Home to the top New Zealand Clan!
    We are a New Zealand based Clan Family. Final Imperium has recently been established, having
    merged with two of the top New Zealand clans, Final Form™ and NZ Imperium, to create one of the
    strongest New Zealand Clan Communities out there. We welcome all kind of players to our
    community, not just New Zealanders! We like banter and value the importance of maturity and have
    zero-tolerance towards toxic behavior. Come on in and join the best New Zealand community out
    there!
  social:
    - twitter: http://twitter.com/Final__Imperium
clans:
  - name: Final Imperium
    tag: 9QR9JVJG
  - name: Final Imperial
    tag: 9GVPG8U0
  - name: Final Imperion
    tag: P0QCJJGL
```
