### ISSUE TITLE
Stealth Family

### ISSUE THREAD

**Issue by OGKevinS** [RoyaleAPI/cr-api-ux#225]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

``` yaml 
name: Stealth
key: stealth
color: grey
emblem: Cherry_Blossom_07.png
info: Stealth is a competitive organisation on ladder and eSports. Home to lots of amazing players who share their knowledge with stealth members in order to help others achieve peak performance. 
We have 3 certainties in stealth, you’ll : Duel-Learn-Compete 
clans : 
Name: Stealth UK
Tag: 8JCURJ0Y

Name: Stealth North
Tag: 9QCVYY2Q

Name: Stealth eSports
Tag: 9QQ0LU9P0

Name: Stealth GB
Tag: 90YPVUG8

Name: Stealth USA
Tag: 9LQRC2Q2

Name: Stealth NA
Tag: 9Q99922R

Name: Stealth South
Tag: 8C8URPP0

Name: Stealth East
Tag: 8CLL228U

Name: Stealth West
Tag: 8CYPYV2R

Name: Stealth CH
Tag: 90PUVLQC

sort: trophy
```

**Comment by smlbiobot** [comment]
- format matters
- clan tags for Stealth USA and Stealth eSports were incorrect

```yml
name: Stealth
key: stealth
color: grey
emblem: Cherry_Blossom_07
sort: trophy
info:
  description: >
    Stealth is a competitive organisation on ladder and eSports. Home to lots of amazing players who share their knowledge with stealth members in order to help others achieve peak performance.
    We have 3 certainties in stealth, you’ll : Duel-Learn-Compete
clans : 
  - name: Stealth UK
    tag: 8JCURJ0Y
  - name: Stealth North
    tag: 9QCVYY2Q
  - name: Stealth eSports
    tag: 9QQ0LU90
  - name: Stealth GB
    tag: 90YPVUG8
  - name: Stealth USA
    tag: 9LQRCQ2Q
  - name: Stealth NA
    tag: 9Q99922R
  - name: Stealth South
    tag: 8C8URPP0
  - name: Stealth East
    tag: 8CLL228U
  - name: Stealth West
    tag: 8CYPYV2R
  - name: Stealth CH
    tag: 90PUVLQC

```
