### ISSUE TITLE
Futura City

### ISSUE THREAD

**Issue by xXCharleSs** [RoyaleAPI/cr-api-ux#227]
```yaml
name: Futura City
key: Familiar
color: Verde
emblem: Verdadero
info: Verdadera
  logo: https://spy.deckshop.pro/img/badges/16000043.png
  
description: >
    Futura City es un clan Familiar en donde se encuentran muy buenos jugadores tanto en ladder como en competitivo. Buscamos entrar al competitivo para seguir creciendo.

  social:
    - twitter: http://twitter.com/carloscarmigasa
    - discord: https://discord.gg/Upj2zhe
    - email: Contacto: carmigasa@outlook.com
clans:
  - name: Futura City2
    tag: 8UPGPLJC
```
