### ISSUE TITLE
Family Configuration Update Request (D.V.A.S.)

### ISSUE THREAD

**Issue by Mister-Welldone** [RoyaleAPI/cr-api-ux#231]
```yaml
name: Deadly Viper Assassination Squad
key: DVAS
color: yellow
emblem: flag_j_03
info:
  logo: https://i.imgur.com/1I8pJ78.png
  description: >
**D.V.A.S. - Deadly Viper Assassination Squad** is comprised of multiple vigorous gold clans, in record timing of three months. **Black Mamba** is the tip of the D.V.A.S. spear by holding down the *Top 25 in Local Clan leaderboards* and *Top 15 in Local Clan War leaderboards*. Our other clans: **Cottonmouth, Snake Charmer, Sidewinder** and **Copperhead**, are fast on the heels of Black Mamba. They can also be found on the *Local Top 200 leaderboards*. These clans make up the D.V.A.S. Family, which many of our active, solid and experienced, trophy-pushers and tournament competitors call home. The clans were created as a result of a mass exodus from the Devil’s Den and a reunion in the Snake Pit. *Established April 2018.*
  social:
    - discord: https://discord.gg/GWrCfNt
clans:
  - name: Black Mamba
    tag: 9YC80UQ9
  - name: Sidewinder
    tag: 9RGGY0PR
  - name: Snake Charmer
    tag: 99VPJ29G
  - name: Cottonmouth
    tag: 9JJQLVU8
  - name: Copperhead
    tag: P02YJUCU
```
