### ISSUE TITLE
#PleePot.NL

### ISSUE THREAD

**Issue by Baggio89** [RoyaleAPI/cr-api-ux#232]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:
key:
color: grey
emblem:
info:
  logo:
  description: >
    #PLeePot.NL actieve clan!


    Add new line with 2 line breaks as above.
  social:
    - email: mailto:robbert.stapel@live.nl
clans:
  - name: #PleePot.NL
    tag: PP90CQYP
```
