### ISSUE TITLE
Stealth 

### ISSUE THREAD

**Issue by OGKevinS** [RoyaleAPI/cr-api-ux#233]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Stealth
key: stealth
color: grey
emblem: Cherry_Blossom_07
sort: trophy
info:
Logo:https://ibb.co/jeEkve
  description: >
    Stealth is a competitive organisation on ladder and eSports. Home to lots of amazing players who share their knowledge with stealth members in order to help others achieve peak performance.
    We have 3 certainties in stealth, you’ll : Duel-Learn-Compete
Social:
Discord: https://discord.gg/tAqnbRg
Twitter: https://twitter.com/stealth_op
clans : 
  - name: Stealth UK
    tag: 8JCURJ0Y
  - name: Stealth North
    tag: 9QCVYY2Q
  - name: Stealth eSports
    tag: 9QQ0LU90
  - name: Stealth GB
    tag: 90YPVUG8
  - name: Stealth USA
    tag: 9LQRCQ2Q
  - name: Stealth NA
    tag: 9Q99922R
  - name: Stealth South
    tag: 8C8URPP0
  - name: Stealth East
    tag: 8CLL228U
  - name: Stealth West
    tag: 8CYPYV2R
  - name: Stealth CH
    tag: 90PUVLQC
```

**Comment by smlbiobot** [comment]
- please mention what is updated in the future
- use this as template

```yml
name: Stealth
key: stealth
color: grey
emblem: Cherry_Blossom_07
sort: trophy
info:
  logo: /static/img/brands/logo/stealth.jpg
  description: >
    Stealth is a competitive organisation on ladder and eSports. Home to lots of amazing players who share their knowledge with stealth members in order to help others achieve peak performance.
    We have 3 certainties in stealth, you’ll : Duel-Learn-Compete
  social:
    - discord: https://discord.gg/tAqnbRg
    - twitter: https://twitter.com/stealth_op
clans:
  - name: Stealth UK
    tag: 8JCURJ0Y
  - name: Stealth North
    tag: 9QCVYY2Q
  - name: Stealth eSports
    tag: 9QQ0LU90
  - name: Stealth GB
    tag: 90YPVUG8
  - name: Stealth USA
    tag: 9LQRCQ2Q
  - name: Stealth NA
    tag: 9Q99922R
  - name: Stealth South
    tag: 8C8URPP0
  - name: Stealth East
    tag: 8CLL228U
  - name: Stealth West
    tag: 8CYPYV2R
  - name: Stealth CH
    tag: 90PUVLQC

```
