### ISSUE TITLE
Gaudi family update

### ISSUE THREAD

**Issue by Kilynho** [RoyaleAPI/cr-api-ux#234]
```yaml
name: Gaudi
key: gaudi
color: blue
emblem: Twin_Peaks_01
feature: true
vip: true
info:
  logo: https://drive.google.com/open?id=135KuecDJfd65jDFE6IAX-gzJLOVKfRP-
  description: >
    Debió cazar para ser probado, arrojado a la tierra salvaje. Debió medir su ingenio y su voluntad contra la furia de la naturaleza. Esa fue su iniciación. Su tiempo en la tierra salvaje. Ya que regresaría con su gente como un espartano o no regresaría.
clans:
  - name: Gaudi Spartans
    tag: G0QLG9
  - name: Gaudi Pretorian
    tag: VVPV8LU
  - name: Gaudi Gladiator
    tag: P8RYYCQV
```

**Comment by smlbiobot** [comment]
- please use the following yml to update in the future

```yaml
name: Gaudi
key: gaudi
color: blue
emblem: Twin_Peaks_01
info:
  logo: /static/img/brands/logo/gaudi.gif
  description: >
    Debió cazar para ser probado, arrojado a la tierra salvaje. Debió medir su ingenio y su voluntad contra la furia de la naturaleza. Esa fue su iniciación. Su tiempo en la tierra salvaje. Ya que regresaría con su gente como un espartano o no regresaría.
clans:
  - name: Gaudi Spartans
    tag: G0QLG9
  - name: Gaudi Pretorian
    tag: VVPV8LU
  - name: Gaudi Gladiator
    tag: P8RYYCQV
```
