### ISSUE TITLE
Dragonites Clan Family

### ISSUE THREAD

**Issue by xandr00** [RoyaleAPI/cr-api-ux#235]
```yaml
name: Dragonites Clan Family
key: dragonites
color: blue
track: true
emblem: Flame_04
feature: true
info:
  description: >
    **Dragonites** Clan is an top war clan in the United States. Clan War focused. Discord: https://discord.gg/7qXpvxw. 25+ war day wins or 4300 trophies required. Joining discord is required before joining the clan.
    
    
  social:
    - website: https://dragonites.xyz/
    - discord: https://discord.gg/7qXpvxw
clans:
  - name: Dragonites
    tag: PVYYLY
  - name: Dragonairs
    tag: P80QYVCC
…
```

**Comment by smlbiobot** [comment]
- please don’t add old fields

```yml
name: Dragonites Clan Family
key: dragonites
color: blue
emblem: Flame_04
info:
  description: >
    **Dragonites** Clan is an top war clan in the United States. Clan War focused. Discord: https://discord.gg/7qXpvxw. 25+ war day wins or 4300 trophies required. Joining discord is required before joining the clan.
  social:
    - website: https://dragonites.xyz/
    - discord: https://discord.gg/7qXpvxw
clans:
  - name: Dragonites
    tag: PVYYLY
  - name: Dragonairs
    tag: P80QYVCC
```
