### ISSUE TITLE
Drop Card

### ISSUE THREAD

**Issue by ghost** [RoyaleAPI/cr-api-ux#236]
```yaml
name: Drop Card
key: DC
color: Blue
emblem: A_Char_King_03
info:
  logo:
  description: >
1] 일주일 지원 50 미만 또는 3회 연속 수집일/전쟁일 미참여 "추방" 2] 지원/클랜전 활동량에 따라 "승급" 3] 승급 및 추방은 일요일에 진행 We're Drop Card★
clans:
  - name: Drop Card
    tag: 89C0YQG
```
