### ISSUE TITLE
Aurora eSports Family

### ISSUE THREAD

**Issue by HocineS** [RoyaleAPI/cr-api-ux#237]
```yaml
name: Aurora eSports
key: Aurora
color: Blue
emblem: Fugi_03.png
info: 
  logo: https://imgur.com/CV3xG2G
  description: >
    **Aurora eSports** is one of the top organisations predominantly based on ClashRoyale. We are a mobile-focused,  upcoming top ranked clan  and gather top tier players from all across the globe under one name, Aurora. We were founded in April 2018 however have been around the competitive scene under different names. #AuroraStrong
    
  social:
    - twitter: https://twitter.com/AuroraTeamGG
    - discord: https://discordapp.com/invite/xpzGEjR
    - twitch: https://www.twitch.tv/rcnxelenos
    - email: mailto: auroraesports@protonmail.com
clans:
  - name: Aurora eSports
    tag: 9P2CVL20
  - name: Aurora Academy
    tag: 9CUG8GYL
```

**Comment by smlbiobot** [comment]
- please note subtle casing + structure

```yml
name: Aurora eSports
key: aurora
color: blue
emblem: Fugi_03
info:
  logo: /static/img/brands/logo/aurora.png
  description: >
    **Aurora eSports** is one of the top organisations predominantly based on ClashRoyale. We are a mobile-focused,  upcoming top ranked clan  and gather top tier players from all across the globe under one name, Aurora. We were founded in April 2018 however have been around the competitive scene under different names. #AuroraStrong
  social:
    - twitter: https://twitter.com/AuroraTeamGG
    - discord: https://discordapp.com/invite/xpzGEjR
    - twitch: https://www.twitch.tv/rcnxelenos
    - email: mailto:auroraesports@protonmail.com
clans:
  - name: Aurora eSports
    tag: 9P2CVL20
  - name: Aurora Academy
    tag: 9CUG8GYL
```
