### ISSUE TITLE
M.I.T™ Family

### ISSUE THREAD

**Issue by dingdonglu** [RoyaleAPI/cr-api-ux#238]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: M.I.T™
key:mit
color:green
emblem:Clover_02
info:
  logo: https://imgur.com/a/jsy8v1V
  description: >
    **台灣M.I.T **9大分部Clover, Elite, Ninja, Royale, Queen, Force, Bimmer, Knight, 提倡安心、開心、熱心三大價值的遊戲環境，歡迎加入超多元化大家庭，想加入請洽各部落管理員 必+ line!
    

clans:
  - name: M.I.T™
    tag: U0PL0V
  - name: M.I.T™ Clover
    tag: Q8J9PU0
  - name: M.I.T™ Elite
    tag: 2RGJJRC
  - name:  M.I.T™ Ninja
    tag: 8CUVUVP
  - name:  M.I.T™ Queen
    tag: 22QJ9RRG
  - name:  M.I.T™ Knight
    tag: Q8RGP9V
  - name:  M.I.T™ Royale
    tag: 8U080UJ
  - name:  M.I.T™ Force
    tag: PGJPC8Y
  - name:  M.I.T™ Bimmer
    tag: LPRJVLQ
```
