### ISSUE TITLE
Bully eSports clan family and Bully I NL

### ISSUE THREAD

**Issue by BullyBami** [RoyaleAPI/cr-api-ux#24]
```yaml
- name: Bully eSports Clan Family

**Comment by BullyBami** [comment]
```yaml
- name: Bully eSports Clan Family
   key: BullyeSports
   color: blue
   emblem: Lotus_02
   info: Bully eSports is a new International Mobile Game Community in Clash Royale with contracted mobile gamers!

   clans:  
- Bully eSports (Main Clan) (4300+ trophies)
-  Bully I NL (Dutch Clan) (4000+ Trophies)
-   Bully I NPP (Mature Adult Clan) (4000+ trophies)

**Comment by BullyBami** [comment]
ok?

**Comment by smlbiobot** [comment]
@BullyBami Missing clan tags

**Comment by smlbiobot** [comment]
Please read the guide thoroughly…

Let me help you, copy and edit this:

```yaml
  - name: Bully eSports Clan Family
    key: bullyesports
    color: blue
    emblem: Lotus_02
    info:
      description: >
        Bully eSports is a new International Mobile Game Community in Clash Royale with contracted mobile gamers!
    clans:
      - name: Bully eSport
        tag: XX
      - name: Bully I NL
        tag: XX
      - name: Bully I NPP
        tag: XX
```

The `clans` section does not support description. If you need to describe the clans, either put it in your clan description (in-game) or put it in the family description.
