### ISSUE TITLE
万里学院家族 (wanli clan family) infomation update

### ISSUE THREAD

**Issue by Darklighture** [RoyaleAPI/cr-api-ux#240]
name: 万里学院家族
key: Wanli
color: orange
track: true
emblem: Orange_02
feature: true
info:
  description: >
    欢迎加入万里学院大家庭。请加微信: kongfuzi_
  social:
    - email: 975454015@qq.com
clans:
  - name: 万里学院
    tag: 82J08RR
  - name: 万里学院 训练营
    tag: 9URJ292U
  - name: 万里学院 附中
    tag: C0URCCV
  - name: 万里学院 附小
    tag: UUP9RYR
  - name: 万里学院 幼儿园
    tag: 29JLVUY8

**Comment by smlbiobot** [comment]
please update this in the future:

```yml
name: 万里学院家族
key: wanli
color: orange
emblem: Orange_02
info:
  description: >
    欢迎加入万里学院大家庭。请加微信: kongfuzi_
  social:
    - email: mailto:975454015@qq.com
clans:
  - name: 万里学院
    tag: 82J08RR
  - name: 万里学院 训练营
    tag: 9URJ292U
  - name: 万里学院 附中
    tag: C0URCCV
  - name: 万里学院 附小
    tag: UUP9RYR
  - name: 万里学院 幼儿园
    tag: 29JLVUY8
```
