### ISSUE TITLE
Nova EG

### ISSUE THREAD

**Issue by smlbiobot** [RoyaleAPI/cr-api-ux#242]
```yaml
name: Nova EG
key: novaeg
color: purple
emblem: Star_Shine_03
sort: trophy
info:
  description: >
    Official Nova eSports & CWA Clan|EG|Taurus|Lyra|Phoenix|Draco|
    Corona|Pegasus|Hydra|Octans|Aquila|Cygnus
  social:
    - discord: http://discord.gg/hYAZNTF
clans:
  - name: Nova EG
    tag: 8YLJ8UL2
  - name: Nova EG Cygnus
    tag: 8CRQRVJQ
  - name: Nova EG Taurus
    tag: 8J9QP82G
  - name: Nova EG Octans
    tag: 8UPGJ8LC
  - name: Nova EG Phoenix
    tag: 8VCUJU2C
  - name: Nova EG Hydra
    tag: 9PPRR8JC
  - name: Nova EG Lyra
    tag: 8U99P0Q8
  - name: Nova EG Draco
    tag: 8VJQPUC2
  - name: Nova EG Corona
    tag: 8JV9LVUL
  - name: Nova EG Pegasus
    tag: 990V0LJ8
  - name: Nova EG Aquila
    tag: 9Q9R9VCJ
  - name: Nova EG Orion
    tag: P2YJ0QC0
```
