### ISSUE TITLE
Clan Family addition request

### ISSUE THREAD

**Issue by Herram** [RoyaleAPI/cr-api-ux#245]
```yaml
name: Code Enigma Clan Family
key: CEF
color: black
track: true
emblem: flag_b_01
sort: trophy
info:
  logo: https://cdn.discordapp.com/attachments/432725345029062666/477208359343489047/unknown.png
  description: >
    **Code Enigma** has a long history as an online community, with branches in Clash Royale, Clash of Clans, and PUBG.
    The clans below form the **Code Enigma Family**, which provides homes for the most competitive progression players and developmental and/or social players alike. All Code Enigma clans are happy to accept talented and engaged players, who understand that we win together or lose together.
    Our joined-at-the-hip communication channels ensure that we can maintain relationships across the entire family's clan rosters.


  social:
    - discord: http://discord.gg/4CxbefS
clans:
  - name: Code Enigma
    tag: UJULVJ
  - name: <Own It>
    tag: 90V8YP0
```
