### ISSUE TITLE
Lost Phoenix Clan Family

### ISSUE THREAD

**Issue by lpjason** [RoyaleAPI/cr-api-ux#249]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Lost Phoenix Family
key: LP
color: Red
emblem: Flame_03
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.

Lost Phoenix is a family of clans striving for excellence and success. We have been around since the beta of Clash Royale. We also have clans in Clash of Clans for those who are interested. Our primary mode of communication is the LINE app. We have clans meant to suit anyone’s desire, such as war clans, push clans, and casual clans.


social: 
- youtube: https://m.youtube.com/user/LostPhoenixClan
- facebook: https://m.facebook.com/lpclashroyale/
    
 
clans:
  - name: Lost Phoenix
    tag: #8UQ2
  - name: LP2 Eros
    tag: #PP2L
  - name: LP2 Chimera
    tag: #PO9GPU
  - name: LP2 Apollo
   tag: #VOV
  - name: LP3 Typhon
   tag: #9Q20L
  - name: LP3 Cyclops
   tag: #9URLJU
  - name: LP4 Manticore
   tag: #Y9YCR2
```

**Comment by lpjason** [comment]
This is for royale api’s clan family feature.

**Comment by smlbiobot** [comment]
- don’t add # signs for tags
- format matters
- tags never have letter O and always use numeric 0
- keep the config here for future updates

```yml
name: Lost Phoenix Family
key: LP
color: red
emblem: Flame_03
info:
  logo:
  description: >
    Lost Phoenix is a family of clans striving for excellence and success. We have been around since the beta of Clash Royale. We also have clans in Clash of Clans for those who are interested. Our primary mode of communication is the LINE app. We have clans meant to suit anyone’s desire, such as war clans, push clans, and casual clans.
  social:
  - youtube: https://m.youtube.com/user/LostPhoenixClan
  - facebook: https://m.facebook.com/lpclashroyale/
clans:
  - name: Lost Phoenix
    tag: 8UQ2
  - name: LP2 Eros
    tag: PP2L
  - name: LP2 Chimera
    tag: P09GPU
  - name: LP2 Apollo
    tag: V0V
  - name: LP3 Typhon
    tag: 9Q20L
  - name: LP3 Cyclops
    tag: 9URLJU
  - name: LP4 Manticore
    tag: Y9YCR2
```
