### ISSUE TITLE
Rebels⚡Family

### ISSUE THREAD

**Issue by badguy74** [RoyaleAPI/cr-api-ux#252]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Rebels⚡Family
key: sgrebels
color: yellow
emblem: flag_j_03
info:
  logo:
  description: >
    **Rebels** was established on March 16 by a group of Singapore adults.
We've grown to 4 active clans, with 3 of them in the top 200 clans in Singapore.
Our main clan **Rebels⚡叛军一营** has been consistently listed on **Top 10 leaderboards in Singapore** despite the challenging environment.
**Join us! We got a clan that meet your needs.**  
  social:
    - facebook: https://www.facebook.com/sgrebels/
clans:
  - name: Rebels⚡叛军一营
    tag: 9Q8Q0PUY
  - name: Rebels⚡叛军二营
    tag: 8UP9288U
  - name: Rebels⚡叛军三营
    tag: 8UYJYQ8L
  - name: Rebels⚡叛军四营
    tag: 9RG2C0GU
```

**Comment by smlbiobot** [comment]
```yml
name: Rebels⚡Family
key: sgrebels
color: yellow
emblem: flag_j_03
info:
  logo:
  description: >
    **Rebels** was established on March 16 by a group of Singapore adults.
    We've grown to 4 active clans, with 3 of them in the top 200 clans in Singapore.
    Our main clan **Rebels⚡叛军一营** has been consistently listed on **Top 10 leaderboards in Singapore** despite the challenging environment.
    **Join us! We got a clan that meet your needs.**
  social:
    - facebook: https://www.facebook.com/sgrebels/
clans:
  - name: Rebels⚡叛军一营
    tag: 9Q8Q0PUY
  - name: Rebels⚡叛军二营
    tag: 8UP9288U
  - name: Rebels⚡叛军三营
    tag: 8UYJYQ8L
  - name: Rebels⚡叛军四营
    tag: 9RG2C0GU
```
