### ISSUE TITLE
rocket pong - update

### ISSUE THREAD

**Issue by blueblair** [RoyaleAPI/cr-api-ux#255]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Rocket Pong
key: rocketpong
color: red
track: true
emblem: A_Char_Rocket_02
feature: true
vip: true
info:
  logo:
  description: >
    Rocket Pong, the Top Clan of Korea
  social:
    - website: https://cafe.naver.com/rocketpong
clans:
  - name: Rocket Pong #1
    tag: RRQ2UCY
  - name: Rocket Pong #2
    tag: C89L080
  - name: Rocket Pong #3
    tag: 82R8U2JP
  - name: Rocket Squad
    tag: PRP9CJUY
  - name: Rocket Arena
    tag: 9Q9202Q8
```

**Comment by blueblair** [comment]
please update 2 more fam clans to Rocket Pong
https://royaleapi.com/clan/family/rocketpong/clans

**Comment by smlbiobot** [comment]
```yml
name: Rocket Pong
key: rocketpong
color: red
emblem: A_Char_Rocket_02
info:
  logo:
  description: >
    Rocket Pong, the Top Clan of Korea
  social:
    - website: https://cafe.naver.com/rocketpong
clans:
  - name: "Rocket Pong #1"
    tag: RRQ2UCY
  - name: "Rocket Pong #2"
    tag: C89L080
  - name: "Rocket Pong #3"
    tag: 82R8U2JP
  - name: Rocket Squad
    tag: PRP9CJUY
  - name: Rocket Arena
    tag: 9Q9202Q8
```
