### ISSUE TITLE
Gaudi family update

### ISSUE THREAD

**Issue by Kilynho** [RoyaleAPI/cr-api-ux#256]
```yaml
name: Gaudi
key: gaudi
color: blue
emblem: Twin_Peaks_01
info:
  logo: /static/img/brands/logo/gaudi.gif
  description: >
    Debió cazar para ser probado, arrojado a la tierra salvaje. Debió medir su ingenio y su voluntad contra la furia de la naturaleza. Esa fue su iniciación. Su tiempo en la tierra salvaje. Ya que regresaría con su gente como un espartano o no regresaría.
  social:
    - twitter: http://twitter.com/GaudiRoyale
clans:
  - name: Gaudi Spartans
    tag: G0QLG9
  - name: Gaudi Pretorian
    tag: VVPV8LU
  - name: Gaudi Gladiator
    tag: P8RYYCQV
```

**Comment by smlbiobot** [comment]
- use https for twitter

```yaml
name: Gaudi
key: gaudi
color: blue
emblem: Twin_Peaks_01
info:
  logo: /static/img/brands/logo/gaudi.gif
  description: >
    Debió cazar para ser probado, arrojado a la tierra salvaje. Debió medir su ingenio y su voluntad contra la furia de la naturaleza. Esa fue su iniciación. Su tiempo en la tierra salvaje. Ya que regresaría con su gente como un espartano o no regresaría.
  social:
    - twitter: https://twitter.com/GaudiRoyale
clans:
  - name: Gaudi Spartans
    tag: G0QLG9
  - name: Gaudi Pretorian
    tag: VVPV8LU
  - name: Gaudi Gladiator
    tag: P8RYYCQV
```
