### ISSUE TITLE
MOJO PICÓN Family

### ISSUE THREAD

**Issue by MojoPiconCR** [RoyaleAPI/cr-api-ux#258]
```yaml
name: MOJO PICÓN
key: MP
color: red
emblem: Flame_01
info: 
  description: >
               ***MOJO PICÓN*** es una familia de clanes con origen en las Islas Canarias y con el objetivo de 
                llegar lo más alto en el TOP España de ladder, así como adentrarse cada vez más en el ámbito 
                competitivo. El staff, al igual que la mayoría de miembros del clan, son personas adultas, serias 
                y respetuosas pero entre ellas siempre reina el buen rollo. Para nosotros es indispensable que 
                cada uno de nuestros jugadores tenga Discord, ya que otro detalle que nos caracteriza es la 
                comunicación directa y el buen trato con los miembros de nuestra familia.
    


    
  social:
    - twitter: http://twitter.com/mojopiconcr
    - email: mailto:mojopiconclash@gmail.com
clans:
  - name: MOJO PICÓN
    tag: 9JCUP9JC
  - name: MOJO PICóN 2
    tag: 9900VVR8
  - name: MOJO PICÓN 3
    tag: 9PRLUUR9
```
