### ISSUE TITLE
New Family request - Gods of Death

### ISSUE THREAD

**Issue by tbkbone** [RoyaleAPI/cr-api-ux#260]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Gods of Death Family
key: GodsOfDeath
color: blue
emblem: Crown_03.png
info:
  logo: https://user-images.githubusercontent.com/42630731/44503725-37f1b180-a66e-11e8-9ca6-bc2f93ebf372.jpg
  description: >
    A família Gods of Death está no TOP dos melhores clans do Brasil! A família foi criada para treinar e preparar os jogadores para disputar na elite das guerras do Clash Royale. Todos são bem-vindos, porém poucos estarão prontos para o desafio. Jogadores ativos são obrigatórios!  Nossos líderes são bem rigorosos, garantindo que nossos membros estejam no melhor estado competitivo. Junte-se à família. Torne-se uma lenda.
  social:
    - facebook: https://www.facebook.com/cla.godsofdeath
clans:
  - name: "Gods of Death"
    tag: 800V9QUJ
  - name: "Sons of Death"
    tag: P8V9PU02
```

**Comment by smlbiobot** [comment]
```yml
name: Gods of Death Family
key: GodsOfDeath
color: blue
emblem: Crown_03
info:
  logo: /static/img/brands/logo/gods-of-death.jpg
  description: >
    A família Gods of Death está no TOP dos melhores clans do Brasil! A família foi criada para treinar e preparar os jogadores para disputar na elite das guerras do Clash Royale. Todos são bem-vindos, porém poucos estarão prontos para o desafio. Jogadores ativos são obrigatórios!  Nossos líderes são bem rigorosos, garantindo que nossos membros estejam no melhor estado competitivo. Junte-se à família. Torne-se uma lenda.
  social:
    - facebook: https://www.facebook.com/cla.godsofdeath
clans:
  - name: "Gods of Death"
    tag: 800V9QUJ
  - name: "Sons of Death"
    tag: P8V9PU02
```
