### ISSUE TITLE
Clashilaquiles

### ISSUE THREAD

**Issue by jortok** [RoyaleAPI/cr-api-ux#261]
```yaml
name: Familia Clashilaquiles
key: clashilaquiles
color: blue
emblem: flag_c_08
info:
  logo: http://clashilaquiles.com/images/content/page-logo.png
  description: Nos gusta Clash Royale y los chilaquiles, team mexicano competitivo.
  social:
    - twitter: https://twitter.com/clashilaquiles
    - facebook: https://www.facebook.com/groups/clashilaquiles/
    - discord: https://discord.gg/tZZ7mVy
    - website: http://clashilaquiles.com
clans:
  - name: Clashilaquiles
    tag: 8P20908J
  - name: Clashilakillers
    tag: 8RVY99CG
…
```

**Comment by smlbiobot** [comment]
```yaml
name: Familia Clashilaquiles
key: clashilaquiles
color: blue
emblem: flag_c_08
info:
  logo: /static/img/brands/logo/clashilaquiles.png
  description: Nos gusta Clash Royale y los chilaquiles, team mexicano competitivo.
  social:
    - twitter: https://twitter.com/clashilaquiles
    - facebook: https://www.facebook.com/groups/clashilaquiles/
    - discord: https://discord.gg/tZZ7mVy
    - website: http://clashilaquiles.com
clans:
  - name: Clashilaquiles
    tag: 8P20908J
  - name: Clashilakillers
    tag: 8RVY99CG
```
