### ISSUE TITLE
This is for an Update our Clan Family 👍 

### ISSUE THREAD

**Issue by TheZeny** [RoyaleAPI/cr-api-ux#262]
- name: Banana Family
  key: banana
  color: Yellow
  emblem: Arrow_04.png
  sort: trophy
  info:
      logo: http://fs1.directupload.net/images/180228/tg7b2v3x.png
      description: >
        Willkommen in der Banana Family.
        Eine der größten Clash Royale Familien im deutschsprachigen Raum.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        Aktivität zeichnet unsere Clans aus, worunter auch starke Clan War Leistung zählt.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - website: http://banana-family.com/
  clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Reife Bananen
        tag: 99VVJPL0
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Cobalt Bananen
        tag: P9U9RYGP
      - name: Titanit Bananen
        tag: PGV98LJJ
      - name: Betafit Bananen
        tag: P8URRP0G
      - name: Gallium Bananen
        tag: 9VYY8RLP

**Comment by smlbiobot** [comment]
- can you update this in the future:

```yml
name: Banana Family
key: banana
color: yellow
emblem: flag_j_03
sort: trophy
info:
  logo: /static/img/brands/logo/banana.png
  description: >
      Willkommen in der Banana Family.
      Eine der größten Clash Royale Familien im deutschsprachigen Raum.
      Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
      Aktivität zeichnet unsere Clans aus, worunter auch starke Clan War Leistung zählt.
  social:
    - discord: https://discord.gg/9rN9qUQ
    - twitch: https://www.twitch.tv/r3dzen
    - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
    - website: https://bananenclan.de/
clans:
  - name: Titan Bananen
    tag: 8Y9LY8CC
  - name: Reife Bananen
    tag: 99VVJPL0
  - name: Uran Bananen
    tag: 8V09Q88C
  - name: Aurum Bananen
    tag: 9900ULUC
  - name: Neodym Bananen
    tag: 8QGQGRP0
  - name: Chilli Bananen
    tag: Q9Q8QJQ
  - name: Cobalt Bananen
    tag: P9U9RYGP
  - name: Titanit Bananen
    tag: PGV98LJJ
  - name: Betafit Bananen
    tag: P8URRP0G
  - name: Gallium Bananen
    tag: 9VYY8RLP
```
