### ISSUE TITLE
[Family Update] Kasalla

### ISSUE THREAD

**Issue by lemonixxx** [RoyaleAPI/cr-api-ux#263]
```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/kasalla.jpg
  description: >
    Deutsche, ständig wachsende, Clash Royale Family.
    Wir haben ein eSport Team, bei dem sich auch Neue Mitglieder immer beweisen können!
    Durch unseren Sponsor ist es auch möglich Mitglieder im Clan zu fördern, sowie regelmäßige Turniere mit Preisgeldern zu veranstalten!
    Außerdem besitzen wir einen gut organisierten Discord Server, mit täglich wachsender Mitgliederanzahl, bestehend aus unseren Clans, sowie auch Gästen von Top 20DE Clans! 
    Aufgrund unserer vielen Clans ist ein Jedermann bei uns willkommen und gut aufgehoben. Was willst du mehr? JOIN NOW!
  social:
    - discord: http://discord.me/crkasalla
    - instagramm: https://instagram.com/kasallacr
clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: Kasalla Squad
    tag: 9JUU2YQG
  - name: Kasalla Gala™
    tag: 9G0YRQGG
  - name: Kasalla Castle
    tag: P9G0R8G0
  - name: Kasalla Seebs
    tag: 9R99Y29L
  - name: Kasalla War
    tag: P0Q220PY
  - name: provocatione™
    tag: 9Y8YVJYP
```

**Comment by smlbiobot** [comment]
- please don’t add unnecessary spaces in the future

```yml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/kasalla.jpg
  description: >
    German, ever-growing, Clash Royale Family.
    We have an eSport team, where new members can always prove themselves!
    Through our sponsor, it is also possible to promote members in the clan, as well as organize regular tournaments with prize money!
    We also have a well-organized Discord server, with a daily growing membership of our clans, as well as guests of Top 20DE clans!
    Because of our many clans, everyone is welcome and in good hands. What do you want more? JOIN NOW!

  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://instagram.com/kasallacr
clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: Kasalla Squad
    tag: 9JUU2YQG
  - name: Kasalla Gala™
    tag: 9G0YRQGG
  - name: Kasalla Castle
    tag: P9G0R8G0
  - name: Kasalla Seebs
    tag: 9R99Y29L
  - name: Kasalla War
    tag: P0Q220PY
  - name: provocatione™
    tag: 9Y8YVJYP

```
