### ISSUE TITLE
[Family Update] Immortal Alliance

### ISSUE THREAD

**Issue by Cronnie11** [RoyaleAPI/cr-api-ux#265]
Update of several areas (logo, description, removal of Phantom clan).

```yaml
name: Immortal Family
key: immortal
color: red
emblem: Skull_06
info:
  logo: https://image.ibb.co/n6iOk9/Immortal_Logo.png
  description: |
    **Immortal Family**
    Group of Clash Royale clans for players aged 18 and over, with both competitive and casual clans to fit a wide variety of playstyles and trophy ranges. 

    All of our clan members are in our 300+ strong Discord server, if we sound like the sort of family you'd like to be a part of, join our Discord for more information and to apply.
    
    - 18+ Only
    - RCS Verified
    - Active War Participation
  social:
    - discord: https://discord.gg/ynryAZU
clans:
  - name: Reddit Immortal
    tag: UJLLRVY
  - name: Reddit Eternal
    tag: 2P9G8JQP
  - name: Reddit Revenant
    tag: 2R099R92
  - name: Reddit Undead
    tag: GV09L0J
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/immortal

**Comment by Cronnie11** [comment]
Will do, appreciate it. 

Just some minor things still left (name was changed from Immortal Alliance to Immortal Family, colour was changed from Orange to Red, immortal.jpg logo in website directory needs replacing with the new higher quality transparent PNG version linked to at https://image.ibb.co/n6iOk9/Immortal_Logo.png)

```yaml
name: Immortal Family
key: immortal
color: red
track: false
emblem: Skull_06
feature: true
info:
  logo: https://image.ibb.co/n6iOk9/Immortal_Logo.png
  description: |
    **Immortal Family**


    Group of Clash Royale clans for players aged 18 and over, with both competitive and casual clans to fit a wide variety of playstyles and trophy ranges.


    All of our clan members are in our 300+ strong Discord server, if we sound like the sort of family you'd like to be a part of, join our Discord for more information and to apply.


    - 18+ Only
    - RCS Verified
    - Active War Participation
  social:
    - discord: https://discord.gg/ynryAZU
clans:
  - name: Reddit Immortal
    tag: UJLLRVY
  - name: Reddit Eternal
    tag: 2P9G8JQP
  - name: Reddit Revenant
    tag: 2R099R92
  - name: Reddit Undead
    tag: GV09L0J
```

Thank you.
