### ISSUE TITLE
[Family Clan] Alpen Heroes 

### ISSUE THREAD

**Issue by Vulcanisimo** [RoyaleAPI/cr-api-ux#266]
```yaml
name: Alpen Heroes
key: AH
color: blue
emblem: Crown_01
info:
  logo: http://www.alpenheroes.com/images/ah_logo.png
  description: >
    Die Alpen Heroes sind eine österreichische Clanfamilie, welche im Mai 2017 durch Vulcano gegründet wurden.
    Nachdem sich der erste Clan konstant unter den Top 50 in Österreich eingereiht hatte, wurde der Clan um Alpen Heroes II erweitert und somit eine Familie.
    Bei Alpen Heroes steht vor allem das Miteinander, der Spass am Spiel und die ständige Verbesserung im Vordergrund.
  social:
    - website: http://www.alpenheroes.com
    - facebook: https://www.facebook.com/groups/alpenheroes/
    - discord: https://discord.gg/xD3TXBB
    - email: mailto:office@alpenheroes.com
clans:
  - name: Alpen Heroes
    tag: 80PRLGCV
  - name: Alpen Heroes II
    tag: PG92PC9Y
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/AH

**Comment by smlbiobot** [comment]
```yml
name: Alpen Heroes
key: AH
color: blue
emblem: Crown_01
info:
  logo: /static/img/brands/logo/alpen-heroes.png
  description: >
    Die Alpen Heroes sind eine österreichische Clanfamilie, welche im Mai 2017 durch Vulcano gegründet wurden.
    Nachdem sich der erste Clan konstant unter den Top 50 in Österreich eingereiht hatte, wurde der Clan um Alpen Heroes II erweitert und somit eine Familie.
    Bei Alpen Heroes steht vor allem das Miteinander, der Spass am Spiel und die ständige Verbesserung im Vordergrund.
  social:
    - website: http://www.alpenheroes.com
    - facebook: https://www.facebook.com/groups/alpenheroes/
    - discord: https://discord.gg/xD3TXBB
    - email: mailto:office@alpenheroes.com
clans:
  - name: Alpen Heroes
    tag: 80PRLGCV
  - name: Alpen Heroes II
    tag: PG92PC9Y
```
