### ISSUE TITLE
Scorpions Family Config

### ISSUE THREAD

**Issue by ImBorisOP** [RoyaleAPI/cr-api-ux#267]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Scorpions eSports
key: Scorpions™
color: violet
emblem: Skull_05
info:
  logo: [https://drive.google.com/file/d/0ByEhqHkLrhvFY1BMUThkM3N2bHhJR1Frd3V0VmI1SUx3WUpF/view?usp=sharing](url)
  description: >
    **Scorpions™** es una de los equipos mas antiguos y sólidos de Perú. 
    Fundado en Mayo de 2017 ha logrado consolidarse como una organización donde se valora la amistad y compañerismo, _logrando en pocos meses consagrarse como campeones en una de las primeras ligas peruanas.
    Con su frase **Sigue tus instintos #WakeUpTheBeast** incentiva a las personas a seguir sus sueños y despertar el potencial que llevan dentro.
    Únete a la familia, conviértete en un escorpión **#WeAreScorpions**.


  social:
    - twitter: https://twitter.com/ScorpionsGG
    - facebook: https://facebook.com/ScorpionsGG
    - email: mailto:scorpionsesports@gmail.com
clans:
  - name: Scorpions™
    tag: #889JQ0L2
  - name: Scorpions Army™
    tag: #PQP9LUPQ
```

**Comment by smlbiobot** [comment]
```yaml
name: Scorpions eSports
key: scorpions
color: violet
emblem: Skull_05
info:
  logo: /static/img/brands/logo/scorpions.png
  description: >
    **Scorpions™** es una de los equipos mas antiguos y sólidos de Perú.
    Fundado en Mayo de 2017 ha logrado consolidarse como una organización donde se valora la amistad y compañerismo, _logrando en pocos meses consagrarse como campeones en una de las primeras ligas peruanas.
    Con su frase **Sigue tus instintos #WakeUpTheBeast** incentiva a las personas a seguir sus sueños y despertar el potencial que llevan dentro.
    Únete a la familia, conviértete en un escorpión **#WeAreScorpions**.


  social:
    - twitter: https://twitter.com/ScorpionsGG
    - facebook: https://facebook.com/ScorpionsGG
    - email: mailto:scorpionsesports@gmail.com
clans:
  - name: Scorpions™
    tag: 889JQ0L2
  - name: Scorpions Army™
    tag: PQP9LUPQ
```
