### ISSUE TITLE
1-800-Crown-Family

### ISSUE THREAD

**Issue by bhanes27** [RoyaleAPI/cr-api-ux#268]
```yaml
name: 1-800-Crown-Family
key: 1-800-Crown
color: Black/Red
emblem: flag_f_02.pnginfo:
  description: > 1-800-clan family is a competitive clan that focuses on having a family environment and player progression. We enjoy hosting our own tournaments and runnings leagues of our own between our clan organization. Each clan has their own set of goals and purpose that we strive to fulfill everyday. We have plenty of competitive players and coaches looking forward to helping everyone in our family succeed. If you are looking for an active competitive clan then look no further. 
    Long paragraphs with markdown syntax.



clans:
  - name: 1-800-3-Crown
    tag: #P2YYGRC9
  - name: 1-800-2-Crown
    tag: #9YC9JRLJ
  - name: 1-800-4-Crown
    tag: #P8JYQVJG
  - name: 1-800-1-Crown
    tag: #PYUQGVY0
```

**Comment by bhanes27** [comment]
Clan family configuration. Im not sure if i did this right

**Comment by smlbiobot** [comment]
```yml
name: 1-800-Crown-Family
key: 1-800-Crown
color: red
emblem: flag_f_02
info:
  description: >
    1-800-Crown family is a competitive clan that focuses on having a family environment and player progression. We enjoy hosting our own tournaments and runnings leagues of our own between our clan organization. Each clan has their own set of goals and purpose that we strive to fulfill everyday. We have plenty of competitive players and coaches looking forward to helping everyone in our family succeed. If you are looking for an active competitive clan then look no further.
    Long paragraphs with markdown syntax.
clans:
  - name: 1-800-3-Crown
    tag: P2YYGRC9
  - name: 1-800-2-Crown
    tag: 9YC9JRLJ
  - name: 1-800-4-Crown
    tag: P8JYQVJG
  - name: 1-800-1-Crown
    tag: PYUQGVY0
```
