### ISSUE TITLE
[Family] SRB Royal Guard Family

### ISSUE THREAD

**Issue by aleksandarmomic** [RoyaleAPI/cr-api-ux#271]
I would like just to edit my clan family as I see social stuff somehow got removed from the website.

```yaml
  - name: SRB Royal Guard Family
    key: srgcf
    color: orange
    emblem: flag_m_03
    clans:
      - name: SRB Royal Guard
        tag: 82JJPPGQ
      - name: SRB Noble Guard
        tag: 8GCQPYLJ
      - name: SRB LegionGuard
        tag: 8GRVJYR0
    info:
      logo: /static/img/brands/logo/srgcf.png
      description: >
        Well organized and long living Serbian clan family. We have been around from the beginning of Clash Royale.
        Our main clan is always on the global leaderboard top 200.
      social:
        - twitter: https://twitter.com/z4ki_tm
        - youtube: https://www.youtube.com/channel/UCB-jt0_yywOhqgcFLFxXTqA
        - facebook: https://www.facebook.com/srbroyalguard/
        - instagram: https://www.instagram.com/srb.royal.guard/
```

**Comment by smlbiobot** [comment]
Not sure what you mean? the social stuff are still there

```yml
name: SRB Royal Guard Family
key: srgcf
color: orange
emblem: flag_m_03
clans:
  - name: SRB Royal Guard
    tag: 82JJPPGQ
  - name: SRB Noble Guard
    tag: 8GCQPYLJ
  - name: SRB LegionGuard
    tag: 8GRVJYR0
info:
  logo: /static/img/brands/logo/srgcf.png
  description: >
    Well organized and long living Serbian clan family. We have been around from the beginning of Clash Royale.
    Our main clan is always on the global leaderboard top 200.
  social:
    - twitter: https://twitter.com/z4ki_tm
    - youtube: https://www.youtube.com/channel/UCB-jt0_yywOhqgcFLFxXTqA
    - facebook: https://www.facebook.com/srbroyalguard/
    - instagram: https://www.instagram.com/srb.royal.guard/
```
