### ISSUE TITLE
Gavetas 

### ISSUE THREAD

**Issue by opaidofarm** [RoyaleAPI/cr-api-ux#273]
```yaml
name: Gavetas Universe
key: gavetas
color: red
track: true
emblem: A_Char_Goblin_02
feature: true
vip: true
info:
  logo: https://ibb.co/kSb7Nz
  description: >
   **Gavetas** is a Portuguese organization focused on the community aspect of the game. We provide a home for the competitive and casual player. We have our own League, competitions and live events with prizes. 
  social:
    - twitter: https://twitter.com/GavetaseSports
    - discord: https://discord.gg/4QYZFys
clans:
  - name: Gavetas Team
    tag: 8VLRRC28
  - name: Gavetas Bravo
    tag: 9QPRPCJQ
  - name: Gavetas Charlie
    tag: 8ULQJG0G
  - name: Gavetas Delta
    tag: 8VLRRC28
  - name: Gavetas Echo
    tag: 9C9VCRUQ  
  - name: Gavetas Foxtrot
    tag: 9UPGVU8G
  - name: Gavetas Golf
    tag: 2QG8V2C9
  - name: Gavetas Hotel
    tag: 9LU2Y8LU 
  - name: Gavetas Índia
    tag: 9CGQ29LR
  - name: Gavetas X-Ray
    tag: P8JYVYGJ
  ```

**Comment by smlbiobot** [comment]
```yml
name: Gavetas Universe
key: gavetas
color: red
emblem: A_Char_Goblin_02
info:
  logo: /static/img/brands/logo/gavetas.png
  description: >
   **Gavetas** is a Portuguese organization focused on the community aspect of the game. We provide a home for the competitive and casual player. We have our own League, competitions and live events with prizes.
  social:
    - twitter: https://twitter.com/GavetaseSports
    - discord: https://discord.gg/4QYZFys
clans:
  - name: Gavetas Team
    tag: 8VLRRC28
  - name: Gavetas Bravo
    tag: 9QPRPCJQ
  - name: Gavetas Charlie
    tag: 8ULQJG0G
  - name: Gavetas Delta
    tag: 8VLRRC28
  - name: Gavetas Echo
    tag: 9C9VCRUQ
  - name: Gavetas Foxtrot
    tag: 9UPGVU8G
  - name: Gavetas Golf
    tag: 2QG8V2C9
  - name: Gavetas Hotel
    tag: 9LU2Y8LU
  - name: Gavetas Índia
    tag: 9CGQ29LR
  - name: Gavetas X-Ray
    tag: P8JYVYGJ
```
