### ISSUE TITLE
[Family] China5000

### ISSUE THREAD

**Issue by fofo2313** [RoyaleAPI/cr-api-ux#275]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 中华五千年家族
key: china5000
color: RED
emblem: Fan_04
info:
  logo: https://pic1.zhimg.com/80/v2-7b6f492ddd00ce25f4200cf5e6167875_hd.jpg
  description: >
    孤军奋战，其力有限，众志成城，坚不可摧。


    诚招热爱CR的你同行，品味生活，开心游戏。


    （仅招华人玩家，进部落请加首领微信:junjie63087，群里提供捐卡福利、锦标赛福利）
clans:
  - name: 中华五千年•盛唐
    tag: 2C8UJJJJ
  - name: 中华五千年•炎黄
    tag: 290PCGGG
  - name: 中华五千年•寰宇
    tag: 8UGQ99PJ
  - name: 中华五千年•戰國
    tag: 2RQVJJJU
  - name: 中华五千年•大明
    tag: 28GGP888
```

**Comment by smlbiobot** [comment]
```yml
name: 中华五千年家族
key: china5000
color: red
emblem: Fan_04
info:
  logo: /static/img/brands/logo/china5000.jpg
  description: >
    孤军奋战，其力有限，众志成城，坚不可摧。


    诚招热爱CR的你同行，品味生活，开心游戏。


    （仅招华人玩家，进部落请加首领微信:junjie63087，群里提供捐卡福利、锦标赛福利）
clans:
  - name: 中华五千年•盛唐
    tag: 2C8UJJJJ
  - name: 中华五千年•炎黄
    tag: 290PCGGG
  - name: 中华五千年•寰宇
    tag: 8UGQ99PJ
  - name: 中华五千年•戰國
    tag: 2RQVJJJU
  - name: 中华五千年•大明
    tag: 28GGP888
```
