### ISSUE TITLE
[Family] Gamma Companies.yaml

### ISSUE THREAD

**Issue by Mdnye64** [RoyaleAPI/cr-api-ux#277]
```yaml
name: Gamma Companies
key: GC
color: black
emblem: Bolt_02
info:
  logo:
  description: >
    **Gamma Companies** is a family of clans focused on Player well being and skill of our Members.
    Here we want to engage members in a friendly environment where Members know and help 
    each other get better.
  social:
    - discord: https://discord.gg/s4dvrSz 
clans:
  - name: Gamma Company
    tag: 2Q8GYLGU
  - name: Alpha Company
    tag: J220J80
```
