### ISSUE TITLE
"SUPERNOVA" Family

### ISSUE THREAD

**Issue by MasterXCI** [RoyaleAPI/cr-api-ux#279]
```yaml
name: "SUPERNOVA" Family
key: supernova
color: violet
emblem: cr-api-assets/badges/Star_Shine_03.png
info: 
  logo: 
  description: >
"SUPERNOVA" est un clan Français composé ( pour le moment ) de trois clans principaux, et d'un quatrième clan réservé aux seconds comptes. Nous sommes des clans actifs, donneurs et convivial! Rejoignez-nous ! 


  social:
    - discord: http://tinyurl.com/discord-sn

clans:
  - name: "SUPERNOVA"
    tag: #2LYG2VCC
  - name: "SUPERNOVA 2"
    tag: #JP8VUC
  - name: "SUPERNOVA 3"
    tag: #2R0UQVCR
  - name: "SUPERNOVA BBY"
     tag: #9VVVRVVR

```

**Comment by smlbiobot** [comment]
- don’t use hash in tag
- note spacing
- note emblem name
- don’t include empty fields
- because your name has quotes, please use this config in the future


```yml
name: >
  "SUPERNOVA" Family
key: supernova
color: violet
emblem: Star_Shine_03
info:
  description: >
    "SUPERNOVA" est un clan Français composé ( pour le moment ) de trois clans principaux, et d'un quatrième clan réservé aux seconds comptes. Nous sommes des clans actifs, donneurs et convivial! Rejoignez-nous !


  social:
    - discord: http://tinyurl.com/discord-sn

clans:
  - name: >
      "SUPERNOVA"
    tag: 2LYG2VCC
  - name: >
      "SUPERNOVA 2"
    tag: JP8VUC
  - name: >
      "SUPERNOVA 3"
    tag: 2R0UQVCR
  - name: >
      "SUPERNOVA BBY"
    tag: 9VVVRVVR
```
