### ISSUE TITLE
Acero Royale

### ISSUE THREAD

**Issue by JGP007** [RoyaleAPI/cr-api-ux#280]
```yaml
name: Acero Royale
key: XXX Royale
color: red
emblem: Flame_03
info:
  logo:
  description: >
Somos un clan español basado en el buen rollo y el respeto que busca gente activa para seguir creciendo en ladder y competir en guerra.
Estamos en el top de España de guerra de clanes y acabamos de iniciar nuestra primera cantera.
  social:
    - discord: https://discord.gg/4AjWAp8
clans:
  - name: Acero Royale
    tag: 8GC00VGR
  - name: Forja Royale
    tag: PGJQVCP0

```

**Comment by smlbiobot** [comment]
```yaml
name: Acero Royale
key: acero
color: red
emblem: Flame_03
info:
  logo:
  description: >
    Somos un clan español basado en el buen rollo y el respeto que busca gente activa para seguir creciendo en ladder y competir en guerra.
    Estamos en el top de España de guerra de clanes y acabamos de iniciar nuestra primera cantera.
  social:
    - discord: https://discord.gg/4AjWAp8
clans:
  - name: Acero Royale
    tag: 8GC00VGR
  - name: Forja Royale
    tag: PGJQVCP0
```
