### ISSUE TITLE
[Family Update] Kasalla

### ISSUE THREAD

**Issue by lemonixxx** [RoyaleAPI/cr-api-ux#281]
Update:  name: **Kasalla Seebs** ,tag: **9R99Y29L** is no part of us anymore, **please delete the clan**
and sorted Clans

```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/kasalla.jpg
  description: >
    **Kasalla** ist eine Deutsche, ständig wachsende, Clash Royale Familie.
    Wir haben ein eSport Team, bei dem sich auch Neue Mitglieder immer beweisen können!
    Durch unseren Sponsor ist es möglich Mitglieder im Clan zu fördern, sowie regelmäßige Turniere mit Preisgeldern zu veranstalten! Außerdem besitzen wir einen gut organisierten Discord Server, mit stetig wachsender Mitgliederanzahl, bestehend aus unseren Clans, sowie auch Gästen von Top 20DE Clans! 
    Aufgrund unserer vielen Clans ist ein Jedermann bei uns willkommen und gut aufgehoben. Was willst du mehr? JOIN NOW!
  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://instagram.com/kasallacr
clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: provocatione™
    tag: 9Y8YVJYP
  - name: Kasalla Squad
    tag: 9JUU2YQG
  - name: Kasalla Castle
    tag: P9G0R8G0
  - name: Kasalla War
    tag: P0Q220PY
  - name: Kasalla Gala™
    tag: 9G0YRQGG
```
