### ISSUE TITLE
OwnageFamily

### ISSUE THREAD

**Issue by Draagbaar** [RoyaleAPI/cr-api-ux#282]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Ownage Family
key: OF
color: teal
emblem: flag_l_03
info:
  logo: none
  description: >
    **Ownage Family** is currently a Dutch-only clan. Competing in their local leaderboards. 
Talent is carefully selected by our experienced leader, Burnd. We're a very helpful clan 
who is willing to teach everyone. Feel free to check out our discord! 


  social:
    - discord: http://discord.gg/Ownage
clans:
  - name: Mates of Ownage
    tag: 28RVCJ
  - name: Bros of Ownage
    tag: YR9JUUPL
```

**Comment by smlbiobot** [comment]
clan tag for bros of ownage is wrong.

```yaml
name: Ownage Family
key: OF
color: teal
emblem: flag_l_03
info:
  description: >
    **Ownage Family** is currently a Dutch-only clan. Competing in their local leaderboards.
    Talent is carefully selected by our experienced leader, Burnd. We're a very helpful clan
    who is willing to teach everyone. Feel free to check out our discord!


  social:
    - discord: http://discord.gg/Ownage
clans:
  - name: Mates of Ownage
    tag: 28RVCJ
  - name: Bros of Ownage
    tag: 9Q0LGJ20
```
