### ISSUE TITLE
OdinWinners Clan Family

### ISSUE THREAD

**Issue by jbooruiz** [RoyaleAPI/cr-api-ux#283]
Hi there, I'd like to add a new clan family.

```yaml
name: OdinWinners
key: OW
color: yellow
track: true
emblem: Skull_01
feature: true
info:
  logo: https://pbs.twimg.com/profile_images/1016033892975947776/rjyvLUIn_400x400.jpg
  social:
    - twitter: https://twitter.com/OdinWinners/
    - twitch: https://www.twitch.tv/odinwinners/
    - youtube: https://www.youtube.com/channel/UCytam4tF_fbzii449o0qdcg/
    - website: http://odinwinners.com/
clans:
    - name: OdinWinners
    - tag: 9YP2892G
```
