### ISSUE TITLE
OsDeSorte Family

### ISSUE THREAD

**Issue by RikeRodrigues** [RoyaleAPI/cr-api-ux#284]
```yaml
name: OsDeSorte
key: ODS
color: green
emblem: Clover_02
info: 
  logo: https://pbs.twimg.com/profile_images/1001117894175068161/mWnYOhQf_400x400.jpg
  description: >
    **Brazilian Top Professional and Competitive Team.**
    OsDeSorte (LuckyOnes): We are what the very best is. We are the very best we can do. 
    Eternal improvement towards full success. Luck is the result of intense work and dedication.
    Love and Passion in everything we do.
  social:
    - twitter: https://twitter.com/osdesorteteam?lang=pt
    - facebook: https://www.facebook.com/milena.anchieta.79
clans:
  - name: OsDeSorte
    tag: 2CRP0URJ
  - name: OsDeSorte 2
    tag: 8Q9CQCJL
  - name: OsDeSorte 3
    tag: 8QR892QP
  - name: OsDeSorte 4
    tag: P8JCVQRP
```

**Comment by smlbiobot** [comment]
```yml
name: OsDeSorte
key: ODS
color: green
emblem: Clover_02
info:
  logo: /static/img/brands/logo/osdesorte.jpg
  description: >
    **Brazilian Top Professional and Competitive Team.**
    OsDeSorte (LuckyOnes): We are what the very best is. We are the very best we can do.
    Eternal improvement towards full success. Luck is the result of intense work and dedication.
    Love and Passion in everything we do.
  social:
    - twitter: https://twitter.com/osdesorteteam?lang=pt
    - facebook: https://www.facebook.com/milena.anchieta.79
clans:
  - name: OsDeSorte
    tag: 2CRP0URJ
  - name: OsDeSorte 2
    tag: 8Q9CQCJL
  - name: OsDeSorte 3
    tag: 8QR892QP
  - name: OsDeSorte 4
    tag: P8JCVQRP
```
