### ISSUE TITLE
运气选手

### ISSUE THREAD

**Issue by frankgao8866** [RoyaleAPI/cr-api-ux#286]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 运气选手大家庭
key: 运气选手
color: red
emblem: Flame_01.png
info: 
  logo:
  description: >
    **欢迎来到运气选手大家庭**
    高手路人聚集地，本部部落战百强，技术党众多
    分部高速发展，大佬云集
    微信：18897582280   QQ群：623403923
    **欢迎技术党高手们的加入**
  social:
clans:
  - name: 运气选手聚集地
    tag: 9JUYVYU
  - name: 运气选手度假村
    tag: 9U0GQYPY
  - name: 运气选手逍遥谷
    tag: PGUUJ0VR
```

**Comment by frankgao8866** [comment]
We want to make this new family web for our clans, thanks for you helps!

**Comment by smlbiobot** [comment]
- changed your key: don’t wanna use chinese characters in URL

```yml
name: 运气选手大家庭
key: yqxs
color: red
emblem: Flame_01
info:
  logo:
  description: >
    **欢迎来到运气选手大家庭**
    高手路人聚集地，本部部落战百强，技术党众多
    分部高速发展，大佬云集
    微信：18897582280   QQ群：623403923
    **欢迎技术党高手们的加入**
  social:
clans:
  - name: 运气选手聚集地
    tag: 9JUYVYU
  - name: 运气选手度假村
    tag: 9U0GQYPY
  - name: 运气选手逍遥谷
    tag: PGUUJ0VR
```
