### ISSUE TITLE
Undefined - Update

### ISSUE THREAD

**Issue by C00ls0ul** [RoyaleAPI/cr-api-ux#290]
```yaml
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/undefined.gif
  description: >
    🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟<br/>

    ⭐️Discord⭐️Invite Code: X55XZHD⭐️<br/>

    ⭐️twitch.tv/sepp317⭐️Family Clans: Undefined & Defined & Redefined⭐️<br/>

    🌠4#1<br/>
  social:
    - discord: https://discord.me/undefined
    - twitch: https://www.twitch.tv/sepp317
    - youtube: https://youtube.com/channel%2FUCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: 9RU2V2U9
  - name: Redefined
    tag: 9JJVUUUL
```
