### ISSUE TITLE
Family clan

### ISSUE THREAD

**Issue by miyagii** [RoyaleAPI/cr-api-ux#292]
```yaml
name: Proelium Family Clan
key: Proelium
color: Blue
emblem: flag_i_03.png
info:
  logo:
  description: >
Proelium has been a long lasting clan since the clash of clans days formed by a tight knit of friends. We've been steadily growing in the clash royale era and is now in need of adding more clans to house our members!

   
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
clans:
  - name: *proelium*
    tag: #vy02j2
  - name: **proelium**
    tag: #pjlvl2j2
```

**Comment by smlbiobot** [comment]
```yml
name: Proelium Family Clan
key: proelium
color: blue
emblem: flag_i_03
info:
  logo:
  description: >
    Proelium has been a long lasting clan since the clash of clans days formed by a tight knit of friends. We've been steadily growing in the clash royale era and is now in need of adding more clans to house our members!
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
clans:
  - name: "*proelium*"
    tag: VY02J2
  - name: "**proelium**"
    tag: PJLVL2J2
```

- special characters require special escaping
