### ISSUE TITLE
Pak Beast family clan

### ISSUE THREAD

**Issue by sohaibarshad2** [RoyaleAPI/cr-api-ux#298]
name: Pak Beasts
key: Pakbeasts
color: Green
track:false
emblem: A_Char_DarkPrince_01
info:
  logo: /static/img/brands/logo/pakbeasts.svg
  description: >
    Pak Beasts is fast growing clan in Pakistan had achieved manys boarderies to become competable with global clan.
    Pak beasts wellcome All Cr members And Taycons to be a part of this Oraganization to find good players. Pak beasts found in 2016 by Hassan 
  social:
    - Facebook: http://www.facebook.com/groups/200163113948750/
clans:
  - name: Pask Beasts
    tag: 9QR2YJU8
 - name: Pak Beasts jr
    tag: P9P9VYJL

**Comment by smlbiobot** [comment]
I don’t have your logo. Please provide a link

**Comment by smlbiobot** [comment]
Also is your clan name Pask Beasts or Pak Beasts? Your clan name is wrong if it’s pak beasts…

**Comment by smlbiobot** [comment]
```yml
name: Pak Beasts
key: pakbeasts
color: green
emblem: A_Char_DarkPrince_01
info:
  description: >
    Pak Beasts is fast growing clan in Pakistan had achieved many borders to become compatible with global clan.
    Pak beasts welcome All Cr members And Taycons to be a part of this Organization to find good players.
    Pak beasts found in 2016 by Hassan
  social:
    - Facebook: http://www.facebook.com/groups/200163113948750/
clans:
  - name: Pak Beasts
    tag: 9QR2YJU8
  - name: Pak Beasts jr
    tag: P9P9VYJL
    
```
