### ISSUE TITLE
Soggy Au Family

### ISSUE THREAD

**Issue by xRICHOx** [RoyaleAPI/cr-api-ux#300]
name: Soggy AU
key: Soggy
color: purple
emblem: Skull_05
info:
  logo: (none)
  description: >
    **Soggy AU** is an Australian based family... We are under a year old, and we are constantly improving. We are highly active, donating a large amount each week. We aim to get our top clan (SoggyWeetBix) onto the Top 200 clans in Australia... **Can you help us???**
  social:
    - discord: http://discord.gg/BhcbCsD
clans:
  - name: SoggyWeetBix
    tag: 9LUOJOLU
  - name: SoggyVegeMite
    tag: 9URV9OVL

**Comment by smlbiobot** [comment]
tags are always number `0` and not letters `O`

```yml
name: Soggy AU
key: soggy
color: purple
emblem: Skull_05
info:
  description: >
    **Soggy AU** is an Australian based family... We are under a year old, and we are constantly improving. We are highly active, donating a large amount each week. We aim to get our top clan (SoggyWeetBix) onto the Top 200 clans in Australia... **Can you help us???**
  social:
    - discord: http://discord.gg/BhcbCsD
clans:
  - name: SoggyWeetBix
    tag: 9LU0J0LU
  - name: SoggyVegeMite
    tag: 9URV90VL
```
