### ISSUE TITLE
Add Pak United family

### ISSUE THREAD

**Issue by miankhalid** [RoyaleAPI/cr-api-ux#301]
Configuration for the Pak United family in Clash Royale:
https://royaleapi.com/clan/9CGUU80Y

```yaml
name: Pak United
key: pak_united
color: green
emblem: Gem_01
info:
  logo: https://user-images.githubusercontent.com/1710804/45629666-55b90780-bab0-11e8-96a9-6b36624b6f7d.png
  description: >
  One of the most friendly, mature and professional CR family in Pakistan = 🇵🇰Pak United Family 🇵🇰
  Join the United forces of Pakistan. **Serious WAR CLAN**.
  35+ war wins required to join.
  Send a WhatsApp message on +923468382058 to get added to our WhatsApp group.
  #PakistanZindabad #UnitedWeStand #WeBleedGreen

  social:
    - twitter: https://twitter.com/QatilMian
    - facebook: https://www.facebook.com/khalidbintahir
    - youtube: https://www.youtube.com/channel/UC841sApNv7tgXCT3o5XHx-A/
    - email: mailto:qatilmian.cr@gmail.com
clans:
  - name: Ss | Pak United
    tag: 9CGUU80Y
  - name: Pak United II
    tag: 8JVY0LY0
  - name: Pak United III
    tag: 9P0PGUG2
  - name: Pak United IV
    tag: 9Y0JUV90
```

### Clan Logo for reference:

![pak_united](https://user-images.githubusercontent.com/1710804/45629666-55b90780-bab0-11e8-96a9-6b36624b6f7d.png)

**Comment by smlbiobot** [comment]
- tags are always number 0 and not letter O

```yml
name: Pak United
key: pak_united
color: green
emblem: Gem_01
info:
  logo: /static/img/brands/logo/pak-united.png
  description: >
    One of the most friendly, mature and professional CR family in Pakistan = 🇵🇰Pak United Family 🇵🇰
    Join the United forces of Pakistan. **Serious WAR CLAN**.
    35+ war wins required to join.
    Send a WhatsApp message on +923468382058 to get added to our WhatsApp group.
    #PakistanZindabad #UnitedWeStand #WeBleedGreen
  social:
    - twitter: https://twitter.com/QatilMian
    - facebook: https://www.facebook.com/khalidbintahir
    - youtube: https://www.youtube.com/channel/UC841sApNv7tgXCT3o5XHx-A/
    - email: mailto:qatilmian.cr@gmail.com
clans:
  - name: Ss | Pak United
    tag: 9CGUU80Y
  - name: Pak United II
    tag: 8JVY0LY0
  - name: Pak United III
    tag: 9P0PGUG2
  - name: Pak United IV
    tag: 9Y0JUV90
```
