### ISSUE TITLE
Revolutions Clan

### ISSUE THREAD

**Issue by teos619** [RoyaleAPI/cr-api-ux#302]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Revolutions Sv
key: REVSV01
color: blue
emblem: Traditional_Star_05
info:
  logo:
  description: 
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
clans:
  - name: REVOLUTIONS
    tag: VLYGRV0
```
