### ISSUE TITLE
Mowin Em Down Family

### ISSUE THREAD

**Issue by TheCing** [RoyaleAPI/cr-api-ux#303]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Mowin Em Down
key: med
color: blue
emblem: A_Char_King_01
info:
    description: >
      **Mowin Em Down** was built from the ground up as a family.
      From our humble beginnings as a local group of friends to our emergence into the Top 200 USA,
      we have strived to prove our ability to compete with the big names in Clash Royale.
      Our members come from all over the world and all walks of life.
      **Join our family and kick some grass!**
    social:
      - twitter: https://twitter.com/MowinEmDown01
clans:
  - name: Mowin Em Down
    tag: 299QCRR
  - name: Mowin Em Down 2
    tag: UC2VYYJ
  - name: Mowin Em Down 3
    tag: 2C9UGUJU
  - name: Mowin Em Down 4
    tag: 2LLYQVCV
```
