### ISSUE TITLE
알로하우이 Family

### ISSUE THREAD

**Issue by cheongbong** [RoyaleAPI/cr-api-ux#304]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 알로하우이 가족
key: aloha
color: Teal
emblem: Cherry_Blossom_05
info:
  logo:
  description: >
    안년하세요~~!! 알로하우이 가족입니다. 요기서 따뜻한 하루하루를 보내세요~~^^
  social:
    - discord: https://discord.gg/G5NkDDs
clans:
  - name: 알로하우이
    tag: 8J02G9RC
  - name: 알로하우이 SPRING
    tag: P809JLUQ
  - name: 알로하우이 FALL
    tag: P8P8J20U
  - name: 알로하우이 Winter
    tag: 9QV0GPCP
  - name: 알로하우이 summer
    tag: 9R2CR2GR
```

**Comment by cheongbong** [comment]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 알로하우이 가족
key: aloha
color: Teal
emblem: Cherry_Blossom_05
info:
  logo:
  description: >
    안년하세요~~!! 알로하우이 가족입니다. 요기서 따뜻한 하루하루를 보내세요~~^^
  social:
    - discord: https://discord.gg/G5NkDDs
clans:
  - name: 알로하우이
    tag: 8J02G9RC
  - name: 알로하우이 SPRING
    tag: P809JLUQ
  - name: 알로하우이 FALL
    tag: P8P8J20U
  - name: 알로하우이 Winter
    tag: 9QV0GPCP
  - name: 알로하우이 summer
    tag: 9R2CR2GR
```
