### ISSUE TITLE
Add new clan to #CR For Fun families

### ISSUE THREAD

**Issue by Xelagn** [RoyaleAPI/cr-api-ux#305]
Hi

I would like to add new clans to #CR For Fun family.

  - name: "#CR For Fun棄部落戰"
    tag: PP29PJRV

  - name: "#CR For Fun學回家"
    tag: PRYL9QU0

Thank you so much
Alex

name: "CR For Fun Family"
key: crforfun
color: teal
emblem: Tower_03
sort: trophy
info:
  logo: /static/img/brands/logo/crforfun.png
  description: >
    全台最大部落#CR For Fun持續招生中 - 目前總共十三個部落為全台之最 -
    不管你分數多少，只要你是活躍玩家，我們絕對都歡迎您❤
  social:
    - youtube: https://www.youtube.com/user/b09703021/
    - facebook: https://goo.gl/qK567D
clans:
  - name: "#CR For Fun™"
    tag: 9RULC0JU
  - name: "#CR For Fun開那女孩"
    tag: 9JG2928R
  - name: "#CR For Fun下屠刀"
    tag: 9GQG9Y2G
  - name: "#CR For Fun暑假"
    tag: 99RRCVJ0
  - name: "#CR For Fun好玩"
    tag: 20Y8R8L
  - name: "#CR For Fun棄治療"
    tag: 9G9PVVGJ
  - name: "#CR For Fun鴿子"
    tag: 9QV8Y20L
  - name: "#CR For Fun眼天下"
    tag: 9CQP28Y2
  - name: "#CR For Fun風箏"
    tag: P2VYU0JU
  - name: "#CR For Fun馬過來"
    tag: 9P2GJJYL
  - name: "#CR For Fun好放滿'"
    tag: 9V8URYC9
  - name: "#CR For Fun生"
    tag: 9Q888RVC
  - name: "#CR For Fun輕鬆"
    tag: 9QJU828U

**Comment by smlbiobot** [comment]
```yml
name: "CR For Fun Family"
key: crforfun
color: teal
emblem: Tower_03
sort: trophy
info:
  logo: /static/img/brands/logo/crforfun.png
  description: >
    全台最大部落#CR For Fun持續招生中 - 目前總共十三個部落為全台之最 -
    不管你分數多少，只要你是活躍玩家，我們絕對都歡迎您❤
  social:
    - youtube: https://www.youtube.com/user/b09703021/
    - facebook: https://goo.gl/qK567D
clans:
  - name: "#CR For Fun™"
    tag: 9RULC0JU
  - name: "#CR For Fun開那女孩"
    tag: 9JG2928R
  - name: "#CR For Fun下屠刀"
    tag: 9GQG9Y2G
  - name: "#CR For Fun暑假"
    tag: 99RRCVJ0
  - name: "#CR For Fun好玩"
    tag: 20Y8R8L
  - name: "#CR For Fun棄治療"
    tag: 9G9PVVGJ
  - name: "#CR For Fun鴿子"
    tag: 9QV8Y20L
  - name: "#CR For Fun眼天下"
    tag: 9CQP28Y2
  - name: "#CR For Fun風箏"
    tag: P2VYU0JU
  - name: "#CR For Fun馬過來"
    tag: 9P2GJJYL
  - name: "#CR For Fun好放滿'"
    tag: 9V8URYC9
  - name: "#CR For Fun生"
    tag: 9Q888RVC
  - name: "#CR For Fun輕鬆"
    tag: 9QJU828U
  - name: "#CR For Fun棄部落戰"
    tag: PP29PJRV
  - name: "#CR For Fun學回家"
    tag: PRYL9QU0
```
