### ISSUE TITLE
Team Demonic Family

### ISSUE THREAD

**Issue by TeamDemonic** [RoyaleAPI/cr-api-ux#308]
```yaml
name: Team Demonic
key: TeamDemonic
color: red
track: true
emblem:Skull_06
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    **Team Demonic** : 
Demonic Pride: the main international clan.; Demonic 3.0: the academy; Demonic Royale the first born italian clan 
  social:
    - telegram: https://t.me/joinchat/I_h5LBJthhBbKf9QBl_rPw
 clans:
  - name: Demonic Pride
    tag: 2G8LYY0R
  - name: Demonic 3.0
    tag: 9LU2LG0C
- name: Demonic Royale
    tag: YCVVU9
```

**Comment by smlbiobot** [comment]
```yml
name: Team Demonic
key: TeamDemonic
color: red
emblem: Skull_06
info:
  description: >
    **Team Demonic** :
      Demonic Pride: the main international clan.; Demonic 3.0: the academy; Demonic Royale the first born italian clan
  social:
    - telegram: https://t.me/joinchat/I_h5LBJthhBbKf9QBl_rPw
clans:
  - name: Demonic Pride
    tag: 2G8LYY0R
  - name: Demonic 3.0
    tag: 9LU2LG0C
  - name: Demonic Royale
    tag: YCVVU9
```
