### ISSUE TITLE
Illuminate Family 

### ISSUE THREAD

**Issue by lucarioman** [RoyaleAPI/cr-api-ux#310]
https://github.com/lucarioman/Illuminate_CR/blob/master/Illuminate.yml
```yaml
name: Illuminate™ Family
key: Illuminate
color: blue
emblem: Star_Shine_02
info:
  logo: https://pbs.twimg.com/profile_images/948280583767064578/OcTF0ngb_400x400.jpg
  description:  >
    Illuminate™ | Est. 12/10/16 | Top 50 Global Ladder and Clan War Clan | For Business Inquiries DM us in any of our social media * Illuminate The World by Joining Today *
  social: 
    - youtube: https://www.youtube.com/channel/UCb6XQl6fCs5IxuUCj0ffDeg
    - twitter: https://twitter.com/illuminate_CR
    - discord: https://discord.gg/DjRQGDj
  clans:
  - name: Illuminate™
    tag: #99P9UC9U
  - name: Illuminate™ II
    tag: #922PUVJ8
  - name: Illuminate™ III
    tag: #9P8LPGQ0
  - name: Illuminate™ IV
    tag: #9YVGUPUR
  - name: Illuminate™ JP
    tag: #9JCPJCRL
  - name: Illuminate™ BO
    tag: #9Y08YCPJ
```

**Comment by smlbiobot** [comment]
- please don’t ad hash to tags

```yml
name: Illuminate™ Family
key: illuminate
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/illuminate.jpg
  description:  >
    Illuminate™ | Est. 12/10/16 | Top 50 Global Ladder and Clan War Clan | For Business Inquiries DM us in any of our social media * Illuminate The World by Joining Today *
  social:
    - youtube: https://www.youtube.com/channel/UCb6XQl6fCs5IxuUCj0ffDeg
    - twitter: https://twitter.com/illuminate_CR
    - discord: https://discord.gg/DjRQGDj
clans:
  - name: Illuminate™
    tag: 99P9UC9U
  - name: Illuminate™ II
    tag: 922PUVJ8
  - name: Illuminate™ III
    tag: 9P8LPGQ0
  - name: Illuminate™ IV
    tag: 9YVGUPUR
  - name: Illuminate™ JP
    tag: 9JCPJCRL
  - name: Illuminate™ BO
    tag: 9Y08YCPJ
```
