### ISSUE TITLE
Beer&Story family

### ISSUE THREAD

**Issue by supersam1688** [RoyaleAPI/cr-api-ux#311]
```yaml
name: Beer&Story
key: Beer
color: Yellow
track: true
emblem: A_Char_DarkPrince_04
feature: true
vip: true
info:
  logo: cr-api-assets/badges/A_Char_DarkPrince_04.png
  description: >
    隨便玩，隨便課，奇葩聚集地。
clans:
  - name: Beer&Story
    tag: 9GU8G8UU
  - name: Cavatina
    tag: 28QR8L
  - name: Cavatina II
    tag: 89UQV9P
```

**Comment by smlbiobot** [comment]
```yml
name: Beer&Story
key: beer
color: Yellow
emblem: A_Char_DarkPrince_04
info:
  logo: /static/img/badge/A_Char_DarkPrince_04.png
  description: >
    隨便玩，隨便課，奇葩聚集地。
clans:
  - name: Beer&Story
    tag: 9GU8G8UU
  - name: Cavatina
    tag: 28QR8L
  - name: Cavatina II
    tag: 89UQV9P
```
