### ISSUE TITLE
Alpha Family

### ISSUE THREAD

**Issue by Jhussain12** [RoyaleAPI/cr-api-ux#322]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml.alpha
name:Alpha Family
key:AlphaFam
color:Red
emblem:flag_j_0


info:
  logo:
![image](https://user-images.githubusercontent.com/43724794/46258476-3e9af200-c480-11e8-8030-0ce50f712d29.png)

  description: >
    Alpha Family is a Clash Royale Clan Family that is growing to be known over the world, That is our goal. We have multiple Alpha Clans that we will grow and we will grow new clans.


    
  social:
    - twitter: http://twitter.com/AlphaFamily1
    - discord: http://discord.gg/q98hr5 
    - website: https://amifamooseyet.github.io/
    - instagram: https://instagram.com/super_family_alpha/
    - email: mailto: alphafamilymail@gmail.com
clans:
  - name:Alpha WaRRiorz!
    tag:9QY2QOLQ
  - name:Alpha Phoenix
    tag:9GUUR8LP
  - name:Alpha Destiny
    tag:9QCJJQO8
```

**Comment by smlbiobot** [comment]
```yml
name: Alpha Family
key: AlphaFam
color: red
emblem: flag_j_0
info:
  logo: /static/img/brands/logo/alphafam.png
  description: >
    Alpha Family is a Clash Royale Clan Family that is growing to be known over the world, That is our goal. We have multiple Alpha Clans that we will grow and we will grow new clans.
  social:
    - twitter: http://twitter.com/AlphaFamily1
    - discord: http://discord.gg/q98hr5
    - website: https://amifamooseyet.github.io/
    - instagram: https://instagram.com/super_family_alpha/
    - email: mailto:alphafamilymail@gmail.com
clans:
  - name: Alpha WaRRiorz!
    tag: 9QY2Q0LQ
  - name: Alpha Phoenix
    tag: 9GUUR8LP
  - name: Alpha Destiny
    tag: 9QCJJQ08
```
