### ISSUE TITLE
PLEASE CORRECT CLAN FAMILY INFO, BUT KEEP EXISTING LOGO (currently under UWRL)

### ISSUE THREAD

**Issue by Feliniacr** [RoyaleAPI/cr-api-ux#323]
name: UnderWorld
key: UW
color: purple
emblem: Elixir_02.png
info:
  logo: /static/img/brands/logo/
  description: >
The UnderWorld Clan Family (UW) consists of 6 clans. We have a friendly, competitive focus and work hard to help each other improve. Our clans’ members are from 28 countries and 6 continents. Over 1000 people enjoy our Discord-based community server which features channels for coaching, strategy assistance, tournaments, eSports, and scrimmages. 
social:
    - twitter: http://twitter.com/Underworldcr
    - discord: http://discord.gg/m6WKDFz
clans:
  - name: UndeRated
    tag: 222VGJ
  - name: UnderBelly
    tag: 2J8UVG99
  - name: UnderMiners
    tag: 2UV822JO
  - name: UnderSiege
    tag: PPY2LPYU
  - name: UnderCover
    tag: 9VY89UC2
  - name: UnderTrade
    tag: 9UL8CU8Pr

**Comment by smlbiobot** [comment]
Maybe type with no caps? What do you mean by “correct”? Do you mean update?

**Comment by smlbiobot** [comment]
- wrong tags
- typos

```yml
name: UnderWorld
key: UW
color: purple
emblem: Elixir_02
info:
  logo: /static/img/brands/logo/uwrl.jpg
  description: >
    The UnderWorld Clan Family (UW) consists of 6 clans. We have a friendly, competitive focus and work hard to help each other improve. Our clans’ members are from 28 countries and 6 continents. Over 1000 people enjoy our Discord-based community server which features channels for coaching, strategy assistance, tournaments, eSports, and scrimmages.
  social:
    - twitter: https://twitter.com/underworldcr?lang=en
    - discord: https://discord.gg/g4kfV4R
clans:
  - name: UndeRated
    tag: 222VGJ
  - name: UnderBelly
    tag: 2J8UVG99
  - name: UnderMiners
    tag: 2UV822J0
  - name: UnderSiege
    tag: PPY2LPYU
  - name: UnderCover
    tag: 9VY89UC2
  - name: UnderTrade
    tag: 9UL8CU8P
```
