### ISSUE TITLE
WHAM! eSports

### ISSUE THREAD

**Issue by RoyaleStormCR** [RoyaleAPI/cr-api-ux#324]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: WHAM! eSports
key: WHAM
color: blue
emblem: A_Char_DarkPrince_01
info:
sort: trophy
  logo: https://cdn.discordapp.com/attachments/423167739516157963/470475121950457876/1532240377657.png
  description: >
    WHAM! eSports was founded by a group of core members who believed that competitive play should be good, clean fun, and where team spirit & positive attitudes will be valued.  This soon grew to include a second competitive team, WHAM! Academy.  The WHAM! family also includes 3 ladder clans - WHAM! eSports, WHAM! Karaoke and WHAM! Harmony.


  social:
    -  twitter: https://twitter.com/WHAMeSportsGG
    -  discord: https://discord.gg/a5n3hXa
    -  website: http://www.whamesportsgg.com
    -  email: whamesportsgg@gmail.com
clans:
  -  name: WHAM! eSports
    tag: 90RJPCUU
  -  name: WHAM! Karaoke
    tag: 9LL8LU9R
  -  name: WHAM! Harmony
    tag: 9R2G90V8
```

**Comment by smlbiobot** [comment]
- spacing
- email requires `mailto:`

please use this config in the future:

```yml
name: WHAM! eSports
key: WHAM
color: blue
emblem: A_Char_DarkPrince_01
sort: trophy
info:
  logo: /static/img/brands/logo/wham.png
  description: >
    WHAM! eSports was founded by a group of core members who believed that competitive play should be good, clean fun, and where team spirit & positive attitudes will be valued.  This soon grew to include a second competitive team, WHAM! Academy.  The WHAM! family also includes 3 ladder clans - WHAM! eSports, WHAM! Karaoke and WHAM! Harmony.
  social:
    -  twitter: https://twitter.com/WHAMeSportsGG
    -  discord: https://discord.gg/a5n3hXa
    -  website: http://www.whamesportsgg.com
    -  email: mailto:whamesportsgg@gmail.com
clans:
  - name: WHAM! eSports
    tag: 90RJPCUU
  - name: WHAM! Karaoke
    tag: 9LL8LU9R
  - name: WHAM! Harmony
    tag: 9R2G90V8
```
