### ISSUE TITLE
WHAM! Clan Family

### ISSUE THREAD

**Issue by Soundium** [RoyaleAPI/cr-api-ux#327]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: WHAM! Clan Family
key: wham
color: teal
emblem: A_Char_DarkPrince_01
info:
  logo: /static/img/brands/logo/wham.svg
  description: >
**WHAM!** is an esports team competing in different Leagues worldwide.
    The three trophy-pushing clans below comprise the ladder branch of the organisation. Since creation, we as a family and individual players have grown immensely and continue to today.
    The clans are home to many talented tournament players and were founded by a group of friends in March 2018.


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/whamesportsgg
    - discord: https://discord.gg/XsXtZSM 
    - website: http://www.whamesportsgg.com

clans:
  - name: WHAM! eSports
    tag: 90RJPCUU
  - name: WHAM! Karaoke
    tag: 9LL8LU9R
  - name: WHAM! Harmony
    tag: 9R2G90V8
```
