### ISSUE TITLE
Taiwan Glory

### ISSUE THREAD

**Issue by soft2165** [RoyaleAPI/cr-api-ux#328]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Taiwan Glory
key: tg
color: Teal
emblem: Diamond_01.png
info:
  logo:https://www.dropbox.com/s/odex9tybxg14z94/taiwanglory.png
  description: >
    歡迎各路好手加入，目標是讓台灣Taiwan之名讓世界看見。目前有1A,2A,3A,NA及BA，參與部落戰務必四戰打完，加Line:0933707805，注意您的禮節，Have fun.收12本與4900+，招募夥伴中～



  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Taiwan Glory
    tag: RLYYQ
  - name: Taiwan Glory 3A
    tag: R920P2
  - name: Taiwan Glory 2A
    tag: JLJURV
  - name: Taiwan Glory 1A
    tag: 80LPRLJ
  - name: Taiwan Glory NA
    tag: 8JRQ8CV
  - name: Taiwan Glory BA
    tag: PLJUPGU
  
```

**Comment by smlbiobot** [comment]
- pls remove unused fields

```yml
name: Taiwan Glory
key: tg
color: teal
emblem: Diamond_01
info:
  logo: /static/img/brands/logo/taiwanglory.png
  description: >
    歡迎各路好手加入，目標是讓台灣Taiwan之名讓世界看見。目前有1A,2A,3A,NA及BA，參與部落戰務必四戰打完，加Line:0933707805，注意您的禮節，Have fun.收12本與4900+，招募夥伴中～
clans:
  - name: Taiwan Glory
    tag: RLYYQ
  - name: Taiwan Glory 3A
    tag: R920P2
  - name: Taiwan Glory 2A
    tag: JLJURV
  - name: Taiwan Glory 1A
    tag: 80LPRLJ
  - name: Taiwan Glory NA
    tag: 8JRQ8CV
  - name: Taiwan Glory BA
    tag: PLJUPGU
```
