### ISSUE TITLE
FresherThanYou Family

### ISSUE THREAD

**Issue by Maxigon** [RoyaleAPI/cr-api-ux#329]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: FresherThanYou Family
key: FTY
color: purple
emblem: 
        Freeze_01
info:
  description: >
**We are a very active German Clash Royale Clan focused on Clan War** 
   The main language in our chat is german. English is welcome. **Weitere Informationen findet ihr in unserem Discord Channel**
  social:
    - discord: https://discord.gg/zYzDQGb
clans:
  - name: #FresherThanYou HQ
    tag: GJ9G9R
  - name: FresherThanYou Dojo
    tag: P009PY9C
```

**Comment by smlbiobot** [comment]
```yml
name: FresherThanYou Family
key: FTY
color: purple
emblem: Freeze_01
info:
  description: >
    **We are a very active German Clash Royale Clan focused on Clan War**
    The main language in our chat is german. English is welcome. **Weitere Informationen findet ihr in unserem Discord Channel**
  social:
    - discord: https://discord.gg/zYzDQGb
clans:
  - name: \#FresherThanYou HQ
    tag: GJ9G9R
  - name: FresherThanYou Dojo
    tag: P009PY9C
```
