### ISSUE TITLE
Alpha Family

### ISSUE THREAD

**Issue by Jhussain12** [RoyaleAPI/cr-api-ux#333]
.

```yaml
name: Alpha Family
key: AlphaFam
color: Red
emblem: flag_j_03
info: 
  logo: 
![image](https://user-images.githubusercontent.com/43724794/46571784-44854d00-c930-11e8-89d4-ebe709d68844.png)

  description: Alpha Family is a Clash Royale Family Clan 
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/AlphaFamily1
    - discord: http://discord.gg/2FtFX2f
    - website:  https://amifamooseyet.github.io/
    - instagram: https://instagram.com//super_family_alpha/
    - email: mailto: alphafamilymail@gmail.com
clans:
  - name: Alpha Phoenix
    tag: #9GUUR8LP
  - name:Alpha Vortex
    tag: #9CJC2QY9
  - name: LA eSports
    tag: #9JC092GU
  - name: Alpha Destiny
    tag: #9QCJJQ08
  - name: The Cocfather
    tag: #UGUY0VU
```

**Comment by smlbiobot** [comment]
I’ve given the updated config for you to update. Can you update this instead:

```yml
name: Alpha Family
key: AlphaFam
color: red
emblem: flag_j_0
info:
  logo: /static/img/brands/logo/alphafam.png
  description: >
    Alpha Family is a Clash Royale Clan Family that is growing to be known over the world, That is our goal. We have multiple Alpha Clans that we will grow and we will grow new clans.
  social:
    - twitter: http://twitter.com/AlphaFamily1
    - discord: http://discord.gg/q98hr5
    - website: https://amifamooseyet.github.io/
    - instagram: https://instagram.com/super_family_alpha/
    - email: mailto:alphafamilymail@gmail.com
clans:
  - name: Alpha WaRRiorz!
    tag: 9QY2Q0LQ
  - name: Alpha Phoenix
    tag: 9GUUR8LP
  - name: Alpha Destiny
    tag: 9QCJJQ08
```

Please don’t put hash `#` in tags

**Comment by Jhussain12** [comment]
```yml
name:Alpha Family
keyAlphaFam
color:red
emblem:flag_j_0
info:
  logo: /static/img/brands/logo/alphafam.png
  description: >
    Alpha Family is a Clash Royale Clan Family that is growing to be known over the world, That is our goal. We have multiple Alpha Clans that we will grow and we will grow new clans.
  social:
    - twitter:http://twitter.com/AlphaFamily1
    - discord:http://discord.gg/q98hr5
    - website:https://amifamooseyet.github.io/
    - instagram:https://instagram.com/super_family_alpha/
    - email:mailto:alphafamilymail@gmail.com
clans:
  - name:Alpha Phoenix
    tag:9GUUR8LP
  - name:Alpha Vortex
     tag:9CJC2QY9
  - name: Alpha Destiny
    tag:9QCJJQ08
  - name:The Cocfather
     tag:UGUY0VU

**Comment by Jhussain12** [comment]
name: Alpha Family
key: AlphaFam
color: red
emblem: flag_j_0
info:
  logo: /static/img/brands/logo/alphafam.png
  description: >
    Alpha Family is a Clash Royale Clan Family that is growing to be known over the world, That is our goal. We have multiple Alpha Clans that we will grow and we will grow new clans.
  social:
    - twitter: http://twitter.com/AlphaFamily1
    - discord: http://discord.gg/q98hr5
    - website: https://amifamooseyet.github.io/
    - instagram: https://instagram.com/super_family_alpha/
    - email: mailto:alphafamilymail@gmail.com
clans:
   - name: Alpha Phoenix
    tag: 9GUUR8LP
  - name: Alpha Destiny
    tag: 9QCJJQ08
  - name: Alpha Vortex
    tag: 9CJC2QY9
  - name: The CocFather
    tag: UGUY0VU

**Comment by smlbiobot** [comment]
```yml
name: Alpha Family
key: AlphaFam
color: red
emblem: flag_j_0
info:
  logo: /static/img/brands/logo/alphafam.png
  description: >
    Alpha Family is a Clash Royale Clan Family that is growing to be known over the world, That is our goal. We have multiple Alpha Clans that we will grow and we will grow new clans.
  social:
    - twitter: http://twitter.com/AlphaFamily1
    - discord: http://discord.gg/q98hr5
    - website: https://amifamooseyet.github.io/
    - instagram: https://instagram.com/super_family_alpha/
    - email: mailto:alphafamilymail@gmail.com
clans:
  - name: Alpha Phoenix
    tag: 9GUUR8LP
  - name: Alpha Vortex
    tag: 9CJC2QY9
  - name: Alpha Destiny
    tag: 9QCJJQ08
  - name: The Cocfather
    tag: UGUY0VU
```
