### ISSUE TITLE
PERU TITANS

### ISSUE THREAD

**Issue by chendo09** [RoyaleAPI/cr-api-ux#336]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Peru Titans Family
key:
color: blue
emblem: https://github.com/RoyaleAPI/cr-api-assets/blob/master/badges/Bolt_03.png
info:
logo:https://www.facebook.com/PeruTitans/photos/a.1107199822654511/1477328272308329/?type=1&theater
  description: >
"Peru Titans" Clan Top Peruano y Equipo competitivo
 Actualmente contamos con 7 clanes que luchan en el top nacional de ladder y clan wars.
Tenemos jugadores casuales como también jugadores competitivos.
Estamos recibiendo jugadores constantemente que participen activamente en clan wars y subida de copas.
 Fundada por Chendo en Marzo de 2016.
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - Facebook: https://www.facebook.com/PeruTitans/
    - discord: https://discord.gg/3HSdyme
    - Twitter: https://twitter.com/PeruTitans
    - email: josuerubent@gmail.com
clans:
  - name: Peru Titans
    tag: Q9RP9Y
  - name: Peru Titans 2
    tag: 8C9UO2L
  - name: Peru Titans 3
    tag: JRVUP9L
 - name: Peru Titans 4
    tag: 8YGR89CL
  - name: Peru Titans X
    tag: 2988RUY9
  - name: Peru Titans Y
    tag: 8R92LYJ
 - name: Peru Titans Z
    tag: 9V8OPQLL
```

**Comment by smlbiobot** [comment]
```yml
name: Peru Titans Family
key: perutitans
color: blue
emblem: Bolt_03
info:
  logo: /static/img/brands/logo/perutitans.jpg
  description: >
    "Peru Titans" Clan Top Peruano y Equipo competitivo
     Actualmente contamos con 7 clanes que luchan en el top nacional de ladder y clan wars.
    Tenemos jugadores casuales como también jugadores competitivos.
    Estamos recibiendo jugadores constantemente que participen activamente en clan wars y subida de copas.
     Fundada por Chendo en Marzo de 2016.
  social:
    - Facebook: https://www.facebook.com/PeruTitans/
    - discord: https://discord.gg/3HSdyme
    - Twitter: https://twitter.com/PeruTitans
    - email: josuerubent@gmail.com
clans:
  - name: Peru Titans
    tag: Q9RP9Y
  - name: Peru Titans 2
    tag: 8C9U02L
  - name: Peru Titans 3
    tag: JRVUP9L
  - name: Peru Titans 4
    tag: 8YGR89CL
  - name: Peru Titans X
    tag: 2988RUY9
  - name: Peru Titans Y
    tag: 8R92LYJ
  - name: Peru Titans Z
    tag: 9V80PQLL
```
