### ISSUE TITLE
Family Config

### ISSUE THREAD

**Issue by ghost** [RoyaleAPI/cr-api-ux#338]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Drop Card
key: dropcard
color: blue
emblem: A_Char_King_03.png
info:
  logo:
  description: >
    1] 일주일 지원 50 미만 또는 3회 연속 수집일/전쟁일 미참여 "추방"
    2] 지원/클랜전 활동량에 따라 "승급"
    3] 승급 및 추방은 일요일에 진행
    We're Drop Card★
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Drop Card
    tag: 89C0YQG
```
