### ISSUE TITLE
Team Arctic Revolution 

### ISSUE THREAD

**Issue by ShadowLight23** [RoyaleAPI/cr-api-ux#342]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Arctic Revolution
key: AR
color: Blue
emblem: Twin_Peaks_02.png
info:
  logo: 
[ar-logo](https://user-images.githubusercontent.com/44174658/46967838-472c3300-d0e4-11e8-804e-489741aad595.png)

  description: >
    ***Arctic Revolution*** is a Finland based clash royale esports organization.  


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/AReSportsGG
    - discord: http://discord.gg/ezJuasB

clans:
  - name: AR eSports
    tag: 2RYRCRV9
  - name: AR Elite
    tag: 8PUR8J0Y
```
