### ISSUE TITLE
Greek Gods family-config

### ISSUE THREAD

**Issue by AlphaGlyph** [RoyaleAPI/cr-api-ux#343]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Greek Gods
key: Greek
color: black
emblem: flag_j_03
info: 
  logo: https://www.ancienthistorylists.com/wp-content/uploads/2015/03/ancient-greek-god-ares.x34319.jpg
  description: >
      The OMNIPOTENT. The ELITE. The TRUE ALPHA.
      What makes a GREEK GOD? A player who demonstrates improving skill, honesty and integrity, adaptability, problem-solving, dependability, and loyalty.
      We are a PERMANENT home. So if you like the way we run things, great. If not, move along... 
      RESPECTFUL and LOYAL members ONLY
      English ONLY. 
      Clans for all skill levels.
      Our Clan System is very simple. We are a brotherhood(sisters too). When Leaders feel you are ready to move up to a higher ranked clan, you will be notified. All ranks carry from clan to clan. Our ranks are given to supportive, respectful, reliable, loyal members who have proven themselves over time with consistent exceptional performance as a clanmate. Donations, trading, communication, war practice, advice, support, the list goes on. Everything you would desire from a leader, you will find from leaders here. Becoming a Leader is a great honor here and holds great respect and honor. We are an extremely strong war clan with many simple standards in place to maintain peace, promote growth, and drive success. We have worked so hard to make this community an amazing place for respectable players to call home and grow together. We have an incredible band of brothers(and sisters) and are always welcoming others who would like to take part in this outstanding community. 
      We are truly unlike other clans you will find.
      We don't have drama, we are respectful, we are supportive, we are always improving, our community is truly a home worth investing in. Do you have what it takes to be ALPHA?    
clans:
  - name: #alphaclash
    tag: 8G9PU0C0
  - name: #betaclash
    tag: 9RUGVCJU
  - name: #gammaclash
    tag: PRJ8JQRP
```

**Comment by smlbiobot** [comment]
- not sure if you really want to type an essay that won’t  fit a single page onto the screen
- updated with line spacing

```yml
name: Achieving Alpha
key: AAlpha
color: black
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/achieving-alpha.jpg
  description: >
      The OMNIPOTENT. The ELITE. The TRUE ALPHA.
    
    
      What makes a GREEK GOD? A player who demonstrates improving skill, honesty and integrity, adaptability, problem-solving, dependability, and loyalty.
    
    
      We are a PERMANENT home. So if you like the way we run things, great. If not, move along...
    
    
      RESPECTFUL and LOYAL members ONLY
    
    
      English ONLY.
    
    
      Clans for all skill levels.
    
    
      Our Clan System is very simple. We are a brotherhood(sisters too). When Leaders feel you are ready to move up to a higher ranked clan, you will be notified. All ranks carry from clan to clan. Our ranks are given to supportive, respectful, reliable, loyal members who have proven themselves over time with consistent exceptional performance as a clanmate. Donations, trading, communication, war practice, advice, support, the list goes on. Everything you would desire from a leader, you will find from leaders here. Becoming a Leader is a great honor here and holds great respect and honor. We are an extremely strong war clan with many simple standards in place to maintain peace, promote growth, and drive success. We have worked so hard to make this community an amazing place for respectable players to call home and grow together. We have an incredible band of brothers(and sisters) and are always welcoming others who would like to take part in this outstanding community.
    
    
      We are truly unlike other clans you will find.
    
    
      We don't have drama, we are respectful, we are supportive, we are always improving, our community is truly a home worth investing in. Do you have what it takes to be ALPHA?
clans:
  - name: \#alphaclash
    tag: 8G9PU0C0
  - name: \#betaclash
    tag: 9RUGVCJU
  - name: \#gammaclash
    tag: PRJ8JQRP
```
