### ISSUE TITLE
Clan configuration

### ISSUE THREAD

**Issue by BloodWarriorsVE** [RoyaleAPI/cr-api-ux#344]
```yaml
name: Blood Warriors
key: BloodWarriors
color: red
emblem: Skull_03
info: 
  logo: /static/img/brands/logo/bloodwarriors.png
  description: >
    **Blood Warriors** es un clan que prefiere la calidad ante la cantidad.
Uno de los pocos clanes en llegar a liga legendaria con menos de 20 personas.
Estamos reclutando.
¡Únete!
  social:
    - twitter: http://twitter.com/BloodWarriorsVE
    - instagram: https://instagram.com/bloodwarriorsve
clans:
  - name: Blood Warriors
    tag: 8PVVYPLG
```
