### ISSUE TITLE
Blood Warriors - Family config

### ISSUE THREAD

**Issue by BloodWarriorsVE** [RoyaleAPI/cr-api-ux#345]
```yaml
name: Blood Warriors
key: BloodWarriors
color: red
emblem: Skull_03
info: 
  logo: /static/img/brands/logo/bloodwarriors.png
  description: >
    **Blood Warriors** es un clan que prefiere la calidad ante la cantidad.
Uno de los pocos clanes en llegar a liga legendaria con menos de 20 personas.
Estamos reclutando.
¡Únete!
  social:
    - twitter: http://twitter.com/BloodWarriorsVE
    - instagram: https://instagram.com/bloodwarriorsve
clans:
  - name: Blood Warriors
    tag: 8PVVYPLG
  - name: Bloody Warriors
    tag: PO2UPOJG
```

**Comment by smlbiobot** [comment]
- if you want to include a logo please upload it somewhere and provide a URL

```yml
name: Blood Warriors
key: BloodWarriors
color: red
emblem: Skull_03
info:
  description: >
    **Blood Warriors** es un clan que prefiere la calidad ante la cantidad.
    Uno de los pocos clanes en llegar a liga legendaria con menos de 20 personas.
    Estamos reclutando.
    ¡Únete!
  social:
    - twitter: http://twitter.com/BloodWarriorsVE
    - instagram: https://instagram.com/bloodwarriorsve
clans:
  - name: Blood Warriors
    tag: 8PVVYPLG
  - name: Bloody Warriors
    tag: P02UP0JG
```
