### ISSUE TITLE
Rocket Pong - Update

### ISSUE THREAD

**Issue by blueblair** [RoyaleAPI/cr-api-ux#349]
```yaml
name: Rocket Pong
key: rocketpong
color: red
emblem: A_Char_Rocket_02
sort: trophy
info:
  logo:
  description: >
    Rocket Pong, the Top Clan of Korea
  social:
    - website: https://cafe.naver.com/rocketpong
clans:
  - name: "Rocket Pong #1"
    tag: RRQ2UCY
  - name: "Rocket Pong #2"
    tag: C89L080
  - name: Rocket Lunatic
    tag: PY2JL8RC
  - name: Rocket Squad
    tag: PRP9CJUY
  - name: Rocket Arena
    tag: 9Q9202Q8
  - name: "Rocket Pong #3"
    tag: 82R8U2JP
```
