### ISSUE TITLE
The Quest Family (updated)

### ISSUE THREAD

**Issue by SupremeBoh** [RoyaleAPI/cr-api-ux#352]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: The Quest Family
key: Quest
color: blue
emblem: flag_g_01
info:
  logo: https://cdn.discordapp.com/attachments/306189934279131139/496968630609772564/image0.jpg
  description: >
     The Quest family was created March 16, 2016 by Supreme Boh. The Quest family is home to 3 active clans that continue to grow and improve each day. The Quest, The Journey, and The Idea. The 3 clans share the same blue and white flag badge. 


  social:
    - discord: http://discord.gg/swPRQ2G
clans:
  - name: The Quest
    tag: 2GV80JP
  - name: The Journey
    tag: 2802UYC2
  - name: The Idea
    tag: 2JPPGGJ0
```
