### ISSUE TITLE
Clan-Arg Family

### ISSUE THREAD

**Issue by hermesarg** [RoyaleAPI/cr-api-ux#353]
```yaml
name: Clan-Arg CR
key: Clan-Arg
color: blue
emblem: Tower_01
info:
  logo: https://i.gyazo.com/5cd139c37b6330737be416bcbafd8a87.jpg
  description: >
    Clan Arg started with games such as Age of Empires, Dota, Counter Strike, etc.
    We were born in 07/20/2000 wich is friend's day in Argentina.
    Our goal is to create a group of friends and good people above all no matter your skills. 
    We are still alive because our group and we will be forever. 
    **Long live Arg**


    
  social:
    - twitter: http://twitter.com/ClanArg_TeaM
    - discord: http://discord.gg/zMXare8
    - youtube: https://www.youtube.com/channel/UCL9OjdY6RgI2fNsySi7m6gw
    - website: https://clanarg.com.ar/
    - facebook: https://www.facebook.com/groups/337025826807970/?ref=bookmarks
    - email: mailto: tinchoads7@gmail.com
clans:
  - name: Clan-Arg
    tag: 8CUVC2L0
  - name: Clan-Arg 2
    tag: 8V2YQQ9G
  - name: Clan-Arg 3
    tag: 9VP09J2V
```
