### ISSUE TITLE
Submit French Team Family Clans

### ISSUE THREAD

**Issue by Aticar** [RoyaleAPI/cr-api-ux#354]
```yaml
Name: French Team Family
key: French_Team
color: Blue
emblem: badges/flag_k_01
info:
  logo: http://image.noelshack.com/fichiers/2018/43/2/1540274625-1540274562819.png
  description: >
    ** French Team ** est une famille de 11 clans, composée d'environ 450 membres.
    Maturité, respect et entraide sont nos principales valeurs. 
    Actuellement, 2 clans top fr ladder et 3 clans ligue légendaire GDC.
    Pour infos, contact via id line : grpprv
 social:
    - discord: http://discord.gg/JQjBQEF
    - facebook: https://facebook.com/aticar75 
    - email: frenchteamwar@gmail.com
clans:
  - name: French Team
    tag: GRPPRV 
  - name: French Team 2
    tag: 29UJULJQ
  - name: French Team 3
    tag: 22YCOG9P
  - name: French Team 4
    tag: 899JVGUQ
  - name: French Team 5
    tag: 2Y992LL8
  - name: French Team 6
    tag: 8UCJVRUL
  - name: French Team 7
    tag: 8UL02YYQ
  - name: French Team 8
    tag: 9J2CJQ2J
  - name: French Team War
    tag: PPV9QULQ
  - name: FrenchTeamGhost
    tag: 8QL22RLQ
  - name: French Team GT 
    tag: 2PG9V8GV

**Comment by smlbiobot** [comment]
```yml
name: French Team Family
key: French_Team
color: blue
emblem: flag_k_01
info:
  logo: /static/img/brands/logo/french-team.png
  description: >
    ** French Team ** est une famille de 11 clans, composée d'environ 450 membres.
    Maturité, respect et entraide sont nos principales valeurs.
    Actuellement, 2 clans top fr ladder et 3 clans ligue légendaire GDC.
    Pour infos, contact via id line : grpprv

  social:
    - discord: http://discord.gg/JQjBQEF
    - facebook: https://facebook.com/aticar75
    - email: frenchteamwar@gmail.com
clans:
  - name: French Team
    tag: GRPPRV
  - name: French Team 2
    tag: 29UJULJQ
  - name: French Team 3
    tag: 22YC0G9P
  - name: French Team 4
    tag: 899JVGUQ
  - name: French Team 5
    tag: 2Y992LL8
  - name: French Team 6
    tag: 8UCJVRUL
  - name: French Team 7
    tag: 8UL02YYQ
  - name: French Team 8
    tag: 9J2CJQ2J
  - name: French Team War
    tag: PPV9QULQ
  - name: FrenchTeamGhost
    tag: 8QL22RLQ
  - name: French Team GT
    tag: 2PG9V8GV
```
