### ISSUE TITLE
Dunkle Armee Familie

### ISSUE THREAD

**Issue by eistuete22** [RoyaleAPI/cr-api-ux#356]
Dunkle Armee Familie

```yaml
name: Dunkle Armee Familie
key: DunkleArmee
color: red
emblem: Flame_03
info:
  logo: https://drive.google.com/open?id=1_WU_z2ojQOmxKc_k8VXShPekeflRMWDm
  description: >
    Die Dunkle Armee Familie ist eine deutsche Clanfamilie, die 7 Clans vereint. Alle Clans sind sehr aktiv und greifen nach den Sternen. Egal wie viele Pokale und Clanwar-Erfahrung du hast, einer unserer Clans passt perfekt zu dir, also bewirb dich! 
eSport-Team ist vorhanden
  social:
    - discord: discord.gg/8wsstmM
    - Line: kflmmlfk
clans:
  - name: Dunkle Armee
    tag: 2JVJQCJU
  - name: Dunkle Armee II
    tag: 8RGQVLQY
  - name: Dunkle Armee III
    tag: 9G8CGRQC
  - name: Dunkle Armee IV
    tag: 9QVRYLUY
  - name: Dunkle Armee V
    tag: PP9CJ880
  - name: Dunkle Armee VI
    tag: 9JU98JPY
  - name: Dunkle Armee VII
    tag: 9C0JG92L
```

**Comment by smlbiobot** [comment]
- Line cannot be in the social section because it has no URL. I’ve moved it to the description

```yml
name: Dunkle Armee Familie
key: DunkleArmee
color: red
emblem: Flame_03
info:
  logo: /static/img/brands/logo/dunkle-armee.jpg
  description: >
    Die Dunkle Armee Familie ist eine deutsche Clanfamilie, die 7 Clans vereint. Alle Clans sind sehr aktiv und greifen nach den Sternen. Egal wie viele Pokale und Clanwar-Erfahrung du hast, einer unserer Clans passt perfekt zu dir, also bewirb dich!
    eSport-Team ist vorhanden


    Line: kflmmlfk
  social:
    - discord: http://discord.gg/8wsstmM
clans:
  - name: Dunkle Armee
    tag: 2JVJQCJU
  - name: Dunkle Armee II
    tag: 8RGQVLQY
  - name: Dunkle Armee III
    tag: 9G8CGRQC
  - name: Dunkle Armee IV
    tag: 9QVRYLUY
  - name: Dunkle Armee V
    tag: PP9CJ880
  - name: Dunkle Armee VI
    tag: 9JU98JPY
  - name: Dunkle Armee VII
    tag: 9C0JG92L
```
