### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by tatoom62** [RoyaleAPI/cr-api-ux#358]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:planeswalkers
key:magic
color:black
emblem:lotus_01.png
inf
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/tatoom62
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name:  planeswalkers
    tag: 2LGJJU0Y
  - name:
    tag:
  - name:
    tag:
```
