### ISSUE TITLE
49Ws

### ISSUE THREAD

**Issue by KickerZero** [RoyaleAPI/cr-api-ux#359]
```yaml
name: 49™ Warriors Family
key: 49Ws
color: black
emblem: Moon_03
info:
  logo: https://drive.google.com/open?id=1SQzZG43wH2-V56c2iNqvVNytwgxXhtR8
  description: >
    **49™ Warriors** is a Brazilian family that start in 2018. 
    We are pleased to be in Brazilian Clans and War rank, as well to have many players also ranked
   

  social:
    - youtube: https://www.youtube.com/channel/UC5tZCgNTdNkbKhxCzhEHYvg

clans:
  - name: 49™ Warriors
    tag: 99CPV828
  - name: 49™ Warriors 2
    tag: 9RQLG2LJ
  - name: 49™ Warriors 3
    tag: 9J88CYQ8
  - name: 49™ Warriors 4
    tag: PUOOCP9V
```

**Comment by smlbiobot** [comment]
```yml
name: 49™ Warriors Family
key: 49Ws
color: black
emblem: Moon_03
info:
  logo: /static/img/brands/logo/49tmWarriors.png
  description: >
    **49™ Warriors** is a Brazilian family that start in 2018.
    We are pleased to be in Brazilian Clans and War rank, as well to have many players also ranked


  social:
    - youtube: https://www.youtube.com/channel/UC5tZCgNTdNkbKhxCzhEHYvg

clans:
  - name: 49™ Warriors
    tag: 99CPV828
  - name: 49™ Warriors 2
    tag: 9RQLG2LJ
  - name: 49™ Warriors 3
    tag: 9J88CYQ8
  - name: 49™ Warriors 4
    tag: PU00CP9V
```
