### ISSUE TITLE
Blood Warriors - Family config (update)

### ISSUE THREAD

**Issue by BloodWarriorsVE** [RoyaleAPI/cr-api-ux#361]
```yaml
name: Blood Warriors
key: BloodWarriors
color: black
emblem: Skull_03
info:
  logo: https://pbs.twimg.com/profile_images/1049491858521509888/qtabgGqt.jpg
  description: >
    **Blood Warriors** es un clan que prevalece por su calidad sobre cantidad.

    Uno de los pocos clanes en llegar a liga legendaria con menos de 20 personas.
    
    Mantenemos un ambiente unido y de respeto en aras del crecimiento y mejora constante.

    ¿Sientes que unes los requisitos para unirte?

    ¡Inténtalo, te esperamos!
  social:
    - twitter: http://twitter.com/BloodWarriorsVE
    - instagram: https://instagram.com/bloodwarriorsve
    - email: bloodwarriors2018@gmail.com
clans:
  - name: Blood Warriors
    tag: 8PVVYPLG
  - name: Bloody Warriors
    tag: P02UP0JG
```

**Comment by smlbiobot** [comment]
```yml
name: Blood Warriors
key: BloodWarriors
color: black
emblem: Skull_03
info:
  logo: /static/img/brands/logo/blood-warriors.jpg
  description: >
    **Blood Warriors** es un clan que prevalece por su calidad sobre cantidad.


    Uno de los pocos clanes en llegar a liga legendaria con menos de 20 personas.


    Mantenemos un ambiente unido y de respeto en aras del crecimiento y mejora constante.


    ¿Sientes que unes los requisitos para unirte?


    ¡Inténtalo, te esperamos!
  social:
    - twitter: http://twitter.com/BloodWarriorsVE
    - instagram: https://instagram.com/bloodwarriorsve
    - email: bloodwarriors2018@gmail.com
clans:
  - name: Blood Warriors
    tag: 8PVVYPLG
  - name: Bloody Warriors
    tag: P02UP0JG
```
