### ISSUE TITLE
Team Demonic family update

### ISSUE THREAD

**Issue by TeamDemonic** [RoyaleAPI/cr-api-ux#363]
```yaml
name: Team Demonic
key: TeamDemonic
color: red
track: true
emblem:Skull_06
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    **Team Demonic** : Located in Italian Area.
Demonic Royale: the first born; Demonic Pride: mother clan of Demonic 3.0 ; Demonic 3.0: Academy of Demonic Pride; Demonic 4.0: Academy of Demonic 3.0 
  
 clans:
  - name: Demonic Royale
    tag: YCVVU9
  - name: Demonic Pride
    tag: 2G8LYY0R
  - name: Demonic 3.0
    tag: 9LU2LG0C
  
  - name: Demonic 4.0
    tag: 9VG89LG9
  
```

**Comment by smlbiobot** [comment]
- don’t add fields that are not here
- in the future update this config instead:

```yml
name: Team Demonic
key: TeamDemonic
color: red
emblem: Skull_06
info:
  description: >
    **Team Demonic** : Located in Italian Area.


    Demonic Royale: the first born; Demonic Pride: mother clan of Demonic 3.0 ; Demonic 3.0: Academy of Demonic Pride; Demonic 4.0: Academy of Demonic 3.0

clans:
  - name: Demonic Royale
    tag: YCVVU9
  - name: Demonic Pride
    tag: 2G8LYY0R
  - name: Demonic 3.0
    tag: 9LU2LG0C
  - name: Demonic 4.0
    tag: 9VG89LG9

```
