### ISSUE TITLE
Pantheon Family update

### ISSUE THREAD

**Issue by PantheonFlint** [RoyaleAPI/cr-api-ux#365]
```yaml
name: Pantheon Family
key: Pantheon
color: red
track: true
emblem: Flame_03
feature: true
vip: true
info:
  logo: /static/img/brands/logo/Pantheon.png
  description: >
    __PANTHEON__ is a family of 11 clans that are made up of over 500 members from around the world. 
    We accept players of all skill and competitive levels.
  social:
    - twitter: http://twitter.com/PantheonFamily1
    - discord: https://discord.gg/x6N9cVR
    - website: http://pantheonfamily.com
clans:
  - name: ARES
    tag: 92LVUPJP
  - name: ATLAS
    tag: 8YLY2RV2
  - name: CHRONOS
    tag: 8U0PQCR0
  - name: HADES
    tag: 90GCRGY2
  - name: HELIOS
    tag: P89CP0QQ
  - name: HYPERION
    tag: 8R92C8VC
  - name: KRATOS
    tag: 9LVV9VVV
  - name: NEMESIS
    tag: 8QVYQL02
  - name: POSEIDON
    tag: 9R99Y9CU
  - name: STYX
    tag: 9Y20CQ9Y
  - name: THANATOS
    tag: 9UG80GY8
```

**Comment by smlbiobot** [comment]
- don’t add your own fields

```yml
name: Pantheon Family
key: Pantheon
color: red
emblem: Flame_03
info:
  logo: /static/img/brands/logo/pantheon.png
  description: >
    __PANTHEON__ is a family of 10 clans that are made up of over 450 members from around the world.
    We accept players of all skill and competitive levels.
  social:
    - twitter: http://twitter.com/PantheonFamily1
    - discord: https://discord.gg/x6N9cVR
    - website: http://pantheonfamily.com
clans:
  - name: ARES
    tag: 92LVUPJP
  - name: ATLAS
    tag: 8YLY2RV2
  - name: CHRONOS
    tag: 8U0PQCR0
  - name: HADES
    tag: 90GCRGY2
  - name: HYPERION
    tag: 8R92C8VC
  - name: KRATOS
    tag: 9LVV9VVV
  - name: NEMESIS
    tag: 8QVYQL02
  - name: POSEIDON
    tag: 9R99Y9CU
  - name: STYX
    tag: 9Y20CQ9Y
  - name: THANATOS
    tag: 9UG80GY8
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/Pantheon

**Comment by PantheonFlint** [comment]
My apologies. Which field was it, so I can refrain from doing it in the future. Actually, we launched another clan today and I need another update.

 

Thanks,

Chris

 

 


 <https://pantheonfamily.com/> Description: Description: http://pantheonfamily.com/files/emailsiglogo.png

 

Chris Austin (Flint)
Board Member, Admin, Webmaster
 <http://pantheonfamily.com> www.PantheonFamily.com
A Clash Royale Family of Clans

**Comment by smlbiobot** [comment]
I’d recommend that you don’t reply to github issues on emails — you can, obvioulsy, but then your full signature gets shown and I am not sure if you want that…

**Comment by PantheonFlint** [comment]
Update:

name: Pantheon Family
key: Pantheon
color: red
track: true
emblem: Flame_03
feature: true
vip: true
info:
  logo: /static/img/brands/logo/Pantheon.png
  description: >
    __PANTHEON__ is a family of 11 clans that are made up of over 500 members from around the world. 
    We accept players of all skill and competitive levels.
  social:
    - twitter: http://twitter.com/PantheonFamily1
    - discord: https://discord.gg/x6N9cVR
    - website: http://pantheonfamily.com
clans:
  - name: ARES
    tag: 92LVUPJP
  - name: ATLAS
    tag: 8YLY2RV2
  - name: CHRONOS
    tag: 8U0PQCR0
  - name: HADES
    tag: 90GCRGY2
  - name: HELIOS
    tag: P89CP0QQ
  - name: HYPERION
    tag: 8R92C8VC
  - name: KRATOS
    tag: 9LVV9VVV
  - name: NEMESIS
    tag: 8QVYQL02
  - name: POSEIDON
    tag: 9R99Y9CU
  - name: STYX
    tag: 9Y20CQ9Y
  - name: THANATOS
    tag: 9UG80GY8

**Comment by smlbiobot** [comment]
In the future, when you update, please open new issue and also **get rid of the track, feature, vip fields**

https://royaleapi.com/f/Pantheon

use this config HERE

```yml
name: Pantheon Family
key: Pantheon
color: red
emblem: Flame_03
info:
  logo: /static/img/brands/logo/pantheon.png
  description: >
    __PANTHEON__ is a family of 10 clans that are made up of over 450 members from around the world.
    We accept players of all skill and competitive levels.
  social:
    - twitter: http://twitter.com/PantheonFamily1
    - discord: https://discord.gg/x6N9cVR
    - website: http://pantheonfamily.com
clans:
  - name: ARES
    tag: 92LVUPJP
  - name: ATLAS
    tag: 8YLY2RV2
  - name: CHRONOS
    tag: 8U0PQCR0
  - name: HADES
    tag: 90GCRGY2
  - name: HELIOS
    tag: P89CP0QQ
  - name: HYPERION
    tag: 8R92C8VC
  - name: KRATOS
    tag: 9LVV9VVV
  - name: NEMESIS
    tag: 8QVYQL02
  - name: POSEIDON
    tag: 9R99Y9CU
  - name: STYX
    tag: 9Y20CQ9Y
  - name: THANATOS
    tag: 9UG80GY8
```
