### ISSUE TITLE
Fairy eSports

### ISSUE THREAD

**Issue by NahuE3** [RoyaleAPI/cr-api-ux#37]
```yaml
- name: Fairy eSports 
    key: FeS
    color: black
    emblem: Flame_03
    info:
      logo: https://media.discordapp.net/attachments/374032616430501888/421933361741692939/asd.png?width=286&height=301
      description: >
        **Fairy eSports** (FeS) tiene actualmente dos clanes de ladder y uno competitivo.

        Ademas de enfocarnos en Clash Royale tenemos otras divisiones en Arena of Valor y League of Legends 
      social:
        - twitter: https://twitter.com/FairyeSportsGG
        - discord: discord.gg/XECyRVx
        - email: mailto: fairyesportsgg@gmail.com
    clans:
      - name: Fairy eSports
        tag: 98LUC8JQ
      - name: Fairy Tail
        tag: 2UC2L0CU
      - name: Fairy Union
        tag: 8UUY8QQP
```

**Comment by smlbiobot** [comment]
```yaml
  - name: Fairy eSports
    key: fes
    color: black
    emblem: Flame_03
    info:
      logo: /static/img/brands/logo/fairy-esports.png
      description: >
        **Fairy eSports** (FeS) tiene actualmente dos clanes de ladder y uno competitivo.

        Ademas de enfocarnos en Clash Royale tenemos otras divisiones en Arena of Valor y League of Legends
      social:
        - twitter: https://twitter.com/FairyeSportsGG
        - discord: http://discord.gg/XECyRVx
        - email: mailto:fairyesportsgg@gmail.com
    clans:
      - name: Fairy eSports
        tag: 98LUC8JQ
      - name: Fairy Tail
        tag: 2UC2L0CU
      - name: Fairy Union
        tag: 8UUY8QQP
```
