### ISSUE TITLE
21 Legend

### ISSUE THREAD

**Issue by Neto21Legend** [RoyaleAPI/cr-api-ux#371]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 21 Legend Family
key: 21Legend
color: Blue 
emblem: Flame_02
sort: trophy
info:
  logo: https://drive.google.com/file/d/1Xzw6h87XOh2mzNJGPmDpqNGaXStIgXGd/view?usp=sharing
  description: >
**21 Legend** es una familia de clanes originaria de México que nace el 8 de Agosto de 2016,un proyecto estable que posee la mayor cantidad de jugadores activos a nivel global. 21 Legend como equipo ha sido protagonista en México en los circuitos nacionales de LVP, siempre con la filosofía de confiar en una base de jugadores formados a partir de la familia.

Como organización 21 Legend nace en 2018,confiando afianzarse en la escena profesional de los eSports manteniendo la bandera de dedicación y esfuerzo gracias al gran sentido de pertenencia de sus miembros.

¨Los Héroes son recordados pero las leyendas nunca mueren¨.

  social:
    - twitter: https://twitter.com/21Legend_CR
    - discord: https://discord.me/21Legend
    - website: http://www.21legend.com.mx
    - facebook: https://www.facebook.com/21Legend.gg
    - instagram: https://instagram.com/21legend.gg
    - email: contacto@21legend.com.mx
    - application:https: //t.co/q7zRdNf3eN
    - youtube: https://goo.gl/tLcE5q
    - twitch: https://www.twitch.tv/21legend_tv
clans:
  - name: 21 Legend
    tag: GGLV2CL
  - name: 21 Legend ARG
    tag: 88G9YJ90
  - name: Dark 21 Legend
    tag: 9J0J0GG
  - name: Elite 21 Legend
    tag: 9PUU8Y0G
  - name: Titan 21 Legend
    tag: 9JQJP2V2
  - name: 21 Legend PE
    tag: 9LYR2GPV
  - name: 21 Legend DT
    tag: 90QCQLPG
  - name: 21 Legend URU
    tag: 8P8C2UUL
  - name: Brohs 21 Legend
    tag: 9J0JQULP
  - name: HRZN 21 Legend
    tag: 9Q2280RP
  - name: Sweet 21 Legend
    tag: 9CLRPCV8
  - name: Hunt 21 Legend
    tag: 9PULU00J
  - name: 21 Legend Vzla
    tag: 88GQCU29
  - name: Aztec 21 Legend
    tag: 9GJVJ9GL
  - name: Sky 21 Legend
    tag: 9JPLR8YC
  - name: Dream 21 legend
    tag: 9UJG9YQ8
  - name: Gold 21 Legend
    tag: 8GCG2098
  - name: Flow 21 Legend
    tag: P2YG9UUC  
  - name: Light 21 Legend
    tag: 22UPJGLL  
  - name: Sector 21Legend
    tag: 92L9CCJJ  
  - name: STARS 21Legend
    tag: PCGPLQR9  
  - name: sparta 21Legend
    tag: 9JQGY29U  
  - name: Magnos 21Legend
    tag: 9UP82G9Q  
```

**Comment by smlbiobot** [comment]
- note spacing
- please update the following config in the future

```yml
name: 21 Legend Family
key: 21Legend
color: Blue
emblem: Flame_02
sort: trophy
info:
  logo: /static/img/brands/logo/21Legend.png
  description: >
    **21 Legend** es una familia de clanes originaria de México que nace el 8 de Agosto de 2016,un proyecto estable que posee la mayor cantidad de jugadores activos a nivel global. 21 Legend como equipo ha sido protagonista en México en los circuitos nacionales de LVP, siempre con la filosofía de confiar en una base de jugadores formados a partir de la familia.

    Como organización 21 Legend nace en 2018,confiando afianzarse en la escena profesional de los eSports manteniendo la bandera de dedicación y esfuerzo gracias al gran sentido de pertenencia de sus miembros.

    ¨Los Héroes son recordados pero las leyendas nunca mueren¨.

  social:
    - twitter: https://twitter.com/21Legend_CR
    - discord: https://discord.me/21Legend
    - website: http://www.21legend.com.mx
    - facebook: https://www.facebook.com/21Legend.gg
    - instagram: https://instagram.com/21legend.gg
    - email: mailto:contacto@21legend.com.mx
    - application: https://t.co/q7zRdNf3eN
    - youtube: https://goo.gl/tLcE5q
    - twitch: https://www.twitch.tv/21legend_tv
clans:
  - name: 21 Legend
    tag: GGLV2CL
  - name: 21 Legend ARG
    tag: 88G9YJ90
  - name: Dark 21 Legend
    tag: 9J0J0GG
  - name: Elite 21 Legend
    tag: 9PUU8Y0G
  - name: Titan 21 Legend
    tag: 9JQJP2V2
  - name: 21 Legend PE
    tag: 9LYR2GPV
  - name: 21 Legend DT
    tag: 90QCQLPG
  - name: 21 Legend URU
    tag: 8P8C2UUL
  - name: Brohs 21 Legend
    tag: 9J0JQULP
  - name: HRZN 21 Legend
    tag: 9Q2280RP
  - name: Sweet 21 Legend
    tag: 9CLRPCV8
  - name: Hunt 21 Legend
    tag: 9PULU00J
  - name: 21 Legend Vzla
    tag: 88GQCU29
  - name: Aztec 21 Legend
    tag: 9GJVJ9GL
  - name: Sky 21 Legend
    tag: 9JPLR8YC
  - name: Dream 21 legend
    tag: 9UJG9YQ8
  - name: Gold 21 Legend
    tag: 8GCG2098
  - name: Flow 21 Legend
    tag: P2YG9UUC
  - name: Light 21 Legend
    tag: 22UPJGLL
  - name: Sector 21Legend
    tag: 92L9CCJJ
  - name: STARS 21Legend
    tag: PCGPLQR9
  - name: sparta 21Legend
    tag: 9JQGY29U
  - name: Magnos 21Legend
    tag: 9UP82G9Q
```
