### ISSUE TITLE
Dunkle Armee Familie update

### ISSUE THREAD

**Issue by eistuete22** [RoyaleAPI/cr-api-ux#373]
```yaml
name: Dunkle Armee
key: DunkleArmee
color: red
emblem: Flame_03
info:
  logo: https://drive.google.com/open?id=1_WU_z2ojQOmxKc_k8VXShPekeflRMWDm
  description: >
    Die Dunkle Armee ist eine deutsche Clanfamilie, die 8 Clans vereint. Alle Clans sind sehr aktiv und greifen nach den Sternen. Egal wie viele Pokale und Clanwar-Erfahrung du hast, einer unserer Clans passt perfekt zu dir, also bewirb dich! 

Line: kflmmlfk

  social:
    Discord: https://discord.gg/8wsstmM
clans:
  - name: Dunkle Armee
    tag: 2JVJQCJU
  - name: Dunkle Armee II
    tag: 8RGQVLQY
  - name: Dunkle Armee III
    tag: 9G8CGRQC
  - name: Dunkle Armee IV
    tag: 9QVRYLUY
  - name: Dunkle Armee V
    tag: PP9CJ880
  - name: Dunkle Armee VI
    tag: 9JU98JPY
  - name: Dunkle Armee VII
    tag: 9C0JG92L
  - name: Dunkle Armee VIII
    tag: PY8V288G
```

changes:
name
description
add new clan
