### ISSUE TITLE
Asgard Alliance Family

### ISSUE THREAD

**Issue by CrimzinShadow** [RoyaleAPI/cr-api-ux#374]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Asgard Alliance
key: AsgardA
color: Orange
emblem: flag_j_03.png
info:
  description: Welcome to Asgard, the great Viking alliance made up of:

Valhalla - Our most competitive clan and home of Odin's chosen warriors Looking for 40+ war wins.

Ultra Fusion - An elite group who strikes fear to those who stand before them

Pig Legion - A bloodthirsty horde of warriors seeking to destroy their enemies in battle

Royale Family - Competitive in war, casual in spirit
Folkvangr - A friendly group, we keep it clean here

Helheim - A social clan of unique and tormented souls

Jotunheim - A clan for improvement and greatness
Full of immense competition, our seven clan alliance offers you a fun and active Clash Royale experience, with opportunities to be competitive or laid back and chill.

We are seeking highly active players who want more out of Clash Royale. Come join a fun and social experience where you can be part of our growing international family of clans.


  social:
    - discord: https://www.discord.gg/CtSkkYf
clans:
  - name: Valhalla
    tag: 2P9JJYPL
  - name: Royale Family
    tag: 9G2RCJJC
  - name: Helheim
    tag: 99JVRY00
  - name: Pig Legion
    tag: 2CJC0YJR
  - name: Ultra Fusion
    tag: 8VV22CP9
  - name: Jotunheim
    tag: PP8ZPVJL
  - name: Folkvangr
    tag: 828Q0PJ2
  sort: trophy
```

**Comment by CrimzinShadow** [comment]
Not sure what else I need but hopefully that works

**Comment by smlbiobot** [comment]
- Jotunheim’s tag is wrong. Updated for you
- I’ve reformatted your markdown to display in bullets
- please update the following config in the future

```yml
name: Asgard Alliance
key: AsgardA
color: orange
emblem: flag_j_03
sort: trophy
info:
  description: >
    Welcome to Asgard, the great Viking alliance made up of:


    - Valhalla - Our most competitive clan and home of Odin's chosen warriors Looking for 40+ war wins.

    - Ultra Fusion - An elite group who strikes fear to those who stand before them

    - Pig Legion - A bloodthirsty horde of warriors seeking to destroy their enemies in battle

    - Royale Family - Competitive in war, casual in spirit

    - Folkvangr - A friendly group, we keep it clean here

    - Helheim - A social clan of unique and tormented souls

    - Jotunheim - A clan for improvement and greatness


    Full of immense competition, our seven clan alliance offers you a fun and active Clash Royale experience, with opportunities to be competitive or laid back and chill.


    We are seeking highly active players who want more out of Clash Royale. Come join a fun and social experience where you can be part of our growing international family of clans.


  social:
    - discord: https://www.discord.gg/CtSkkYf
clans:
  - name: Valhalla
    tag: 2P9JJYPL
  - name: Royale Family
    tag: 9G2RCJJC
  - name: Helheim
    tag: 99JVRY00
  - name: Pig Legion
    tag: 2CJC0YJR
  - name: Ultra Fusion
    tag: 8VV22CP9
  - name: Jotunheim
    tag: PP82PVJL
  - name: Folkvangr
    tag: 828Q0PJ2
```
