### ISSUE TITLE
Born2Royale Family Config

### ISSUE THREAD

**Issue by booleanbird** [RoyaleAPI/cr-api-ux#378]
```yaml
name: Born2Royale Family
key: Born2Royale
color: blue
emblem: A_Char_King_01.png
info: 
  logo: https://royaleapi.com/static/img/badge/A_Char_King_01.png
  description: >
    **Born2Royale** is the head of the Born2Royale Family clans. Founded by brothers **Snoop King** 
    and **Grind Erb**, our clans are consistently in the top leaderboards in North America. Our top two 
    clans are the strongest and our other clans are there for the lower trophy rangers. See which clan 
    works best for you and climb the clans!


    **Join today!** Check us out on discord down below as well.
  social:
    - discord: https://discord.gg/z49WJxw
clans:
  - name: Born2Royale
    tag: RUCGUVC
  - name: Born2Royale2
    tag: UU9V8JP
  - name: Born2Royale3
    tag: 228PPQ8Q
  - name: Born2Royale4
    tag: UGGJRR9
```
