### ISSUE TITLE
German Galaxy Clan Family

### ISSUE THREAD

**Issue by Xsive** [RoyaleAPI/cr-api-ux#38]
```yaml
 - name: German Galaxy Clan Family
    key: ggcf
    color: blue
    emblem: Star_Shine_02
    info:
      logo: https://imgur.com/a/xFU2z
      description: >
Moin Moin ....

Endlich ist es soweit und wir können euch German Galaxy vorstellen.

Auf lange Sicht möchten wir eine starke und spielfreudige Clanfamilie werden, die eine gute Mischung aus Ehrgeiz, auf der Jagd nach Pokalen, und

Spaß am Spiel hinbekommt.

Was sollte man bei uns mitbringen und was bekommt man dafür???

Auf jeden Fall Ehrgeiz, Spielfreude und die Fähigkeit, respektvoll mit anderen umgehen zu können. Denn genau das kannst du auch von uns erwarten ^^

Wir organisieren/spendieren gelegentlich Turniere, um die Gemeinschaft zu fördern und neue Techniken sowie Decks ausprobieren zu können.

Zudem haben wir eine aktive LINE-Gruppe, in der sich unsere Mitglieder austauschen können und unser Clanprofil ebenfalls beschrieben wird.
      social:
        - discord: https://discord.gg/vXzNUhB

    clans:
      - name: German Galaxy
        tag: 2RGY2YGU
      - name: German Galaxy 2
        tag: 2JRCULPG
      - name: German Galaxy 3
        tag: 8QG8LLLQ
```

**Comment by smlbiobot** [comment]
Implemente: http://royaleapi.com/clan/family/ggcf/clans

However, I would recommend that you shorten your description as you will need to scroll a lot to get to your clans.

Please save the config below for future updates:

```yaml
  - name: German Galaxy Clan Family 
    key: ggcf 
    color: blue 
    emblem: Star_Shine_02
    clans:
      - name: German Galaxy
        tag: 2RGY2YGU
      - name: German Galaxy 2
        tag: 2JRCULPG
      - name: German Galaxy 3
        tag: 8QG8LLLQ
    info:
      logo: /static/img/brands/logo/ggcf.jpg
      description: >
        Moin Moin …

        Endlich ist es soweit und wir können euch German Galaxy vorstellen.

        Auf lange Sicht möchten wir eine starke und spielfreudige Clanfamilie werden,
        die eine gute Mischung aus Ehrgeiz, auf der Jagd nach Pokalen, und

        Spaß am Spiel hinbekommt.

        Was sollte man bei uns mitbringen und was bekommt man dafür???

        Auf jeden Fall Ehrgeiz, Spielfreude und die Fähigkeit, respektvoll mit anderen umgehen zu können.
        Denn genau das kannst du auch von uns erwarten

        Wir organisieren/spendieren gelegentlich Turniere,
        um die Gemeinschaft zu fördern und neue Techniken sowie Decks ausprobieren zu können.

        Zudem haben wir eine aktive LINE-Gruppe,
        in der sich unsere Mitglieder austauschen können und unser Clanprofil ebenfalls beschrieben wird.
      social:
        - discord: https://discord.gg/vXzNUhB
```
