### ISSUE TITLE
Mkers Clan Family - Update

### ISSUE THREAD

**Issue by riccardoperra** [RoyaleAPI/cr-api-ux#381]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Mkers Clan Family
key: mkers
color: black
emblem: A_Char_King_01
info:
  logo: https://mkers.gg/wp-content/uploads/2018/02/minilogotrasp.png
  description: >
   Mkers is an eSport Organization based in Italy and it's formed by managers and established players, more then 10 years of experience in our country across games, events and competitions. We're in Clash Royale, FIFA, FIFA Pro Club, Moto GP, Hearthstone, Brawl Stars, Tennis World Tour. In Clash Royale, Mkers consist of an international big family with many branches and team. Mainly, it's composed of a Pro Team and ladder clans. 


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/mkerscr
    - discord: bit.ly/discord-mkers
    - website: http://mkers.gg
    - instagram: https://instagram.com/mkersofficial
    - facebook: https://facebook.com/mkersofficial
    - email: mailto:ignazio@mkers.it
clans:
  - name: Mkers
    tag: 98QCV9CG
  - name: Mkers ITA
    tag: 9UJV0JGP
  - name: Mkers ITA 1
    tag: 9UC8C9UV
 - name: Mkers ITA 1
    tag: 9UC8C9UV
 - name: Mkers ITA 1
    tag: 9UC8C9UV

```
