### ISSUE TITLE
Mkers Clan Family - Update

### ISSUE THREAD

**Issue by riccardoperra** [RoyaleAPI/cr-api-ux#382]
```yaml
name: Mkers Clan Family
key: mkers
color: black
emblem: A_Char_King_01
sort: trophy
info:

  logo: https://mkers.gg/wp-content/uploads/2018/02/minilogotrasp.png
  description: >
   Mkers is an eSport Organization based in Italy and it's formed by managers and established players, more then 10 years of experience in our country across games, events and competitions. We're in Clash Royale, FIFA, FIFA Pro Club, Moto GP, Hearthstone, Brawl Stars, Tennis World Tour. In Clash Royale, Mkers consist of an international big family with many branches and team. Mainly, it's composed of a Pro Team and ladder clans. 


  social:
    - twitter: http://twitter.com/mkerscr
    - discord: bit.ly/discord-mkers
    - website: http://mkers.gg
    - instagram: https://instagram.com/mkersofficial
    - facebook: https://facebook.com/mkersofficial
    - email: mailto:ignazio@mkers.it
clans:
  - name: Mkers
    tag: 98QCV9CG
  - name: Mkers ITA
    tag: 9UJV0JGP
  - name: Mkers ITA 1
    tag: 9UC8C9UV
 - name: Mkers ITA 2
    tag: 9GYCQ0J8
 - name: Mkers ITA 3
    tag: 92U08YJ2
 - name: Mkers ITA III
    tag: 9GPRP9Q2
 - name: Mkers ITA 4
    tag: 9JY0V0LG
 - name: Mkers ITA 5
    tag: 9GUPYRYU
- name: Mkers RO
    tag: 9Q2980PR
- name: Mkers IND
    tag: 92RV2CGJ
- name: Mkers IND 2
    tag: 99JYV2U9
- name: Mkers IND 3
    tag: 990QCRJG
- name: Mkers IND 4
    tag: 9R8P2J2Y
- name: Mkers DE
    tag: 9YJ228YL
- name: Mkers DE 2 
    tag: 9P8VV0CJ
- name: Mkers CRC
    tag: 9VG892Q8
- name: Mkers CRC 1
    tag: 9VCCUGLY
- name: Mkers USA
    tag: P2V89JCQ
- name: Mkers USA 1
    tag: P82LJ0PY
- name: Mkers USA 2
    tag: 9RUCVJ8Q
- name: Mkers UK
    tag: 9CVUPLPY
- name: Mkers PE
    tag: 9JL9CGU2
- name: Mkers BR
    tag: P8PG2289
- name: Mkers Kick-Off
    tag: PY0U2RJU

```
