### ISSUE TITLE
Please add our family..

### ISSUE THREAD

**Issue by mikechw** [RoyaleAPI/cr-api-ux#383]
```yaml
name: 香港人俱樂部 Family
key: 香港人俱樂部
color: yellow
emblem: A_Char_Knight_02
info:
  description: >
    香港人俱樂部 & 香港人俱樂部.1st
  social:
    - website: https://goo.gl/dbnYme
clans:
  - name: 香港人俱樂部
    tag: VQYC80G
  - name: 香港人俱樂部-1st
    tag: 2GYJYYPL

```

**Comment by smlbiobot** [comment]
- can’t support chinese characters in keys

```yml
name: 香港人俱樂部 Family
key: hkclub
color: yellow
emblem: A_Char_Knight_02
info:
  description: >
    香港人俱樂部 & 香港人俱樂部.1st
  social:
    - website: https://goo.gl/dbnYme
clans:
  - name: 香港人俱樂部
    tag: VQYC80G
  - name: 香港人俱樂部-1st
    tag: 2GYJYYPL
```
