### ISSUE TITLE
BananaWarriors Update

### ISSUE THREAD

**Issue by DaDa101** [RoyaleAPI/cr-api-ux#386]
Thx in advance for updating !

```yaml
name: Banana Warriors
key: bw
color: yellow
emblem: Skull_01
sort: trophy
info:
  logo: https://bananenclan.de/wp-content/uploads/2018/06/banana_warriors192x150.png
  description: >
    Die *Banana Warriors* bestehen aus 5 Clans. In den ClanWars sind wir mittlerweile nicht mehr unter Gold II unterwegs. Kontinuität zahlt sich eben aus. Unter uns befinden sich auch einige erfolgreiche Turnier-Spieler und nicht zuletzt Streamer, die in ClashRoyal aktiv sind. Bei unseren Mitgliedern legen wir wert auf Aktivität im ClanWar, Freundlichkeit im Umgang mit Anderen, sowie Spass im und am Spiel.
  social:
    - discord: https://discord.me/bananawarriors
    - twitch: https://www.twitch.tv/neonvimes
    - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
    - website: http://bananawarriors.de
clans:
  - name: Platin Bananen
    tag: 8GUPGYVY
  - name: Xenon Bananen
    tag: 9YJLCRR0
  - name: Radium Bananen
    tag: 8Q8JRPQV
  - name: Neon Bananen
    tag: 8PRPP00J
  - name: Chrom Bananen
    tag: 8CLJQPR0
```

**Comment by smlbiobot** [comment]
- please update this config, not your own

```yml
name: Banana Warriors
key: bw
color: yellow
emblem: Skull_01
sort: trophy
info:
  logo: /static/img/brands/logo/banana_warriors.png
  description: >
    Die *Banana Warriors* bestehen aus 5 Clans. In den ClanWars sind wir mittlerweile nicht mehr unter Gold II unterwegs. Kontinuität zahlt sich eben aus. Unter uns befinden sich auch einige erfolgreiche Turnier-Spieler und nicht zuletzt Streamer, die in ClashRoyal aktiv sind. Bei unseren Mitgliedern legen wir wert auf Aktivität im ClanWar, Freundlichkeit im Umgang mit Anderen, sowie Spass im und am Spiel.
  social:
    - discord: https://discord.me/bananawarriors
    - twitch: https://www.twitch.tv/neonvimes
    - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
    - website: http://bananawarriors.de
clans:
  - name: Platin Bananen
    tag: 8GUPGYVY
  - name: Xenon Bananen
    tag: 9YJLCRR0
  - name: Radium Bananen
    tag: 8Q8JRPQV
  - name: Neon Bananen
    tag: 8PRPP00J
  - name: Chrom Bananen
    tag: 8CLJQPR0
```
