### ISSUE TITLE
German Galaxy Clan Family *Update* Thanks in Advance.

### ISSUE THREAD

**Issue by Xsive** [RoyaleAPI/cr-api-ux#39]
```yaml
 - name: German Galaxy Clan Family 
    key: ggcf 
    color: blue 
    emblem: Star_Shine_02
    clans:
      - name: German Galaxy
        tag: 2RGY2YGU
      - name: German Galaxy 2
        tag: 2JRCULPG
      - name: German Galaxy 3
        tag: 8QG8LLLQ
    info:
      logo: /static/img/brands/logo/ggcf.jpg
      description: >
Endlich ist es soweit und wir können euch German Galaxy vorstellen.
Auf lange Sicht möchten wir eine starke und spielfreudige Clanfamilie werden,
die eine gute Mischung aus Ehrgeiz, auf der Jagd nach Pokalen und Spaß am Spiel hin bekommt. Um zu uns zu gehören solltest du Ehrgeiz, Spielfreude und einen respektvollen Umgang mitbringen. Wir organisieren/spendieren gelegentlich Turniere, sowie Testspiele gegen andere Clans.
Außerdem verfügen wir über eine aktive Line-Gruppe.
      social:
        - discord: https://discord.gg/vXzNUhB
```
