### ISSUE TITLE
CR

### ISSUE THREAD

**Issue by HarryPrinceWong** [RoyaleAPI/cr-api-ux#392]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 天堂與地獄
key: heavenandhell
color: violet
emblem: A_Char_Prince_01
info:
  logo: /static/img/badge/Moon_03.png
  description: >
    大家好，請各位多多打盃。不收小號及不活躍人士，定期清理。大家一起加油💪努力💪！


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: https://discord.gg/UGGxgrW
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 天堂與地獄
    tag: 2RU9GQRG
  - name:
    tag:
  - name:
    tag:
```
