### ISSUE TITLE
Variation 

### ISSUE THREAD

**Issue by theycallmejun** [RoyaleAPI/cr-api-ux#395]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Variation 
key: variation 
color: red
emblem: Cherry_Blossom_03
info:
  logo:
  description: > Welcome! We like to war, trade and have fun 🤪 WhatsApp 📱Family Clan: Variation, Variation 2 & Variation 3 


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: https://discord.gg/T4Wj8ag 
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Variation 
    tag: 8UVJGQ0C 
  - name: Variation 2
    tag: P9U02CVJ 
  - name: Variation 3
    tag: 9VY09GC2 
```
