### ISSUE TITLE
4Kings

### ISSUE THREAD

**Issue by TB89** [RoyaleAPI/cr-api-ux#397]
```yaml
name: 4KingsofClash
key: 4KoC
color: black
emblem: A_Char_King_04
info:
  logo: https://imgur.com/a/le3ZtR8
  description: >
    The 4KingsofClash Family of Clans are a core group of strong players. The 4Kings Family welcomes a community of clashers from mid-range to high level players, as long as they're skilled. We encourage constructive behaviour and help each other grow into stronger players. We were first created over 2 years ago and have continue to expand ever since, now with 2 competitive clans and a 3rd for lower-level, casuals and smurf accounts. We sometimes compete under the Team Name - 4KoC!
  social:
    - facebook: https://www.facebook.com/groups/1426977657374949/
    - discord: https://discord.gg/KfFUYW

clans:
  - name: 4KingsOfClash
    tag: 2P0Y28
  - name: 4kingsofclash2
    tag: 88GCV889
  - name: 4KingsofClash3
    tag: PPY2PUCQ
  …
```
