### ISSUE TITLE
Nova Czech Family

### ISSUE THREAD

**Issue by McSlina** [RoyaleAPI/cr-api-ux#398]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Nova Czech
key:
color: Purple
emblem: Star_Shine_03.png
info:
  logo:
  description: >
   Stále silný klan Nova Czech se svými coop academy 
Nova Czech² a Nova Czech³ vás zvou do svých řad. 
Oddanost, loajalita, bojovnost a hlavně friendly přístup. @Novapower

     social:
    - discord: https://discord.gg/MS9f3av
    - youtube: https://www.youtube.com/channel/UCPQ-B1_P3sNZ8Ucx1-Up1Gg
    - facebook: https://www.facebook.com/groups/243954189142093/?hc_ref=ARQiO5sTf2Bpl2s4jaqc1YPBAG3oMsJcrRcMF5nYGFi11yoLlnUIj8Y3VBWYh41QaHU
  
clans:
  - name: Nova Czech
    tag: RY8JQVG
  - name: Nova Czech²
    tag: 8V0PU02P
  - name: Nova Czech³
    tag: 9PV0Y9PP
```

**Comment by smlbiobot** [comment]
```yml
name: Nova Czech
key: novaczech
color: Purple
emblem: Star_Shine_03
info:
  description: >
    Stále silný klan Nova Czech se svými coop academy
    Nova Czech² a Nova Czech³ vás zvou do svých řad.
    Oddanost, loajalita, bojovnost a hlavně friendly přístup. @Novapower

  social:
    - discord: https://discord.gg/MS9f3av
    - youtube: https://www.youtube.com/channel/UCPQ-B1_P3sNZ8Ucx1-Up1Gg
    - facebook: https://www.facebook.com/groups/243954189142093/?hc_ref=ARQiO5sTf2Bpl2s4jaqc1YPBAG3oMsJcrRcMF5nYGFi11yoLlnUIj8Y3VBWYh41QaHU

clans:
  - name: Nova Czech
    tag: RY8JQVG
  - name: Nova Czech²
    tag: 8V0PU02P
  - name: Nova Czech³
    tag: 9PV0Y9PP
```
