### ISSUE TITLE
clan family

### ISSUE THREAD

**Issue by yautah** [RoyaleAPI/cr-api-ux#40]
we want our clan family to be listed on the clan family page,

here is the config:

```yaml
- name: 气质征服你
  key: TCY
  color: pink
  emblem: A_Char_Pekka_02
  sort: trophy
  info:
      logo: http://obsaom04l.bkt.clouddn.com/logo.jpg
      description: >
          欢迎加入本部落，大家开心游戏。积极捐卡，利人利己。 
          Welcome to the clan "Temperament conquer you".
          Have fun! QQ群：13285012.
          更多服务请访问：royaleapi.com
      social:
          - email: mailto:feza@163.com
  clans:
    - name: 气质征服你
    tag: CC8GR0Q
    - name: 气质征服你【1分部】
    tag: 2QVCUYQR
    - name: 气质征服你【2分部】
    tag: 8JJUPG82
```

**Comment by smlbiobot** [comment]
```yaml
  - name: 气质征服你
    key: tcy
    color: pink
    emblem: A_Char_Pekka_02
    sort: trophy
    info:
      logo: /static/img/brands/logo/tcy.jpg
      description: >
        欢迎加入本部落，大家开心游戏。积极捐卡，利人利己。<br/>
        Welcome to the clan "Temperament conquer you". <br/>
        Have fun! QQ群：13285012. <br/>
        更多服务请访问：royaleapi.com
      social:
        - email: mailto:feza@163.com
    clans:
      - name: 气质征服你
        tag: CC8GR0Q
      - name: 气质征服你【1分部】
        tag: 2QVCUYQR
      - name: 气质征服你【2分部】
        tag: 8JJUPG82
```
