### ISSUE TITLE
[Family Update] Kasalla

### ISSUE THREAD

**Issue by lemonixxx** [RoyaleAPI/cr-api-ux#400]
Update: 
- delete Clan "autkrieger" 
- added Clan "Kasalla Academy"
- added Clan "i.9 eSports" 

```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/kasalla.jpg
  description: >
    **Kasalla** ist eine deutschsprachige Clash Royale Clan Familie.
    Wir haben einen eSport Partner, die RDKL, mit eigener Liga, bei dem sich auch neue Mitglieder immer beweisen können!
    Durch unsere Sponsoren ist es uns erlaubt regelmäßige Turniere mit Preisgeldern zu veranstalten.
	Außerdem besitzen wir einen gut organisierten Discord Server(1000+ Mitglieder), mit eigenen Chaträumen für Tauschmarken, Turniere, Streaming usw. rund um Clash Royale.   
    Aufgrund unserer vielen Clans ist Jeder Spieler bei uns willkommen und gut aufgehoben. 
	Was willst du mehr? JOIN NOW!


  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://instagram.com/kasallacr
clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: provocatione™
    tag: 9Y8YVJYP
  - name: i.9 eSports
    tag: 80ULQRLU 
  - name: Kasalla Castle
    tag: P9G0R8G0
  - name: Kasalla War
    tag: P0Q220PY
  - name: Kasalla Deluxe
    tag: 9CVCRP9L 
  - name: Kasalla Phoenix
    tag: PPYG2QPJ  
  - name: Kasalla Gala™
    tag: 9R99Y29L  	
  - name: Kasalla Academy
    tag: PUGP20P2     
```
