### ISSUE TITLE
[AT]Family

### ISSUE THREAD

**Issue by foxyboss** [RoyaleAPI/cr-api-ux#402]
```yaml
name: [AT]Family
key: at-family
color: black
emblem: A_Char_King_02
info:
  description: >
    **[AT]Family**


    Drei Clans definieren unsere Familie:
clans:
  - name: [AT]AlpenElite™
    tag: 8VLYC92V
  - name: [AT]Sturmreiter
    tag: 8V0JUL20
  - name: [AT]retrobroz
    tag: P20Q8Y9Q
```

**Comment by smlbiobot** [comment]
- special characters requires quotes

```yml
name: "[AT]Family"
key: at-family
color: black
emblem: A_Char_King_02
info:
  description: >
    **[AT]Family**


    Drei Clans definieren unsere Familie:
clans:
  - name: "[AT]AlpenElite™"
    tag: 8VLYC92V
  - name: "[AT]Sturmreiter"
    tag: 8V0JUL20
  - name: "[AT]retrobroz"
    tag: P20Q8Y9Q
```
