### ISSUE TITLE
[Family Update] SRB Royale Guard Family

### ISSUE THREAD

**Issue by aleksandarmomic** [RoyaleAPI/cr-api-ux#408]
We have a new clan added to our family, so I would like to update it on the website.
```yaml
  - name: SRB Royal Guard Family
    key: srgcf
    color: orange
    emblem: flag_m_03
    clans:
      - name: SRB Royal Guard
        tag: 82JJPPGQ
      - name: SRB Noble Guard
        tag: 8GCQPYLJ
      - name: SRB LegionGuard
        tag: 8GRVJYR0
      - name: SRB EmpireGuard
        tag: 9V09QQUJ
    info:
      logo: /static/img/brands/logo/srgcf.png
      description: >
        Well organized and long living Serbian clan family. We have been around from the beginning of Clash Royale.
        Our main clan is always on the global leaderboard top 200.
      social:
        - twitter: https://twitter.com/z4ki_tm
        - youtube: https://www.youtube.com/channel/UCB-jt0_yywOhqgcFLFxXTqA
        - facebook: https://www.facebook.com/srbroyalguard
        - instagram: https://www.instagram.com/srb.royal.guard
```
