### ISSUE TITLE
Clan configuration - Blood Warriors (Update)

### ISSUE THREAD

**Issue by BloodWarriorsVE** [RoyaleAPI/cr-api-ux#410]
```yaml
name: Blood Warriors
key: BloodWarriors
color: black
emblem: Skull_03
info:
  logo: /static/img/brands/logo/blood-warriors.png
  description: >
    **Blood Warriors** es un clan enfocado en guerras que prevalece por su calidad ante la cantidad.


    Uno de los pocos clanes en llegar a liga legendaria con menos de 20 personas y pertenecer al top 20 en guerras de Venezuela.


    Mantenemos un ambiente unido y de respeto en aras del crecimiento y mejora constante.


    Blood Warriors está afiliado a TG Paragon, una potente organización de eSports, la cual además de contar con ligas y torneos exclusivos para miembros de los clanes pertenecientes a la estructura, cuenta con equipos de alto nivel competitivo en LATAM y EU.


    ¿Sientes que reúnes los requisitos para unirte?


    ¡Inténtalo, te esperamos!
  social:
    - twitter: http://twitter.com/BloodWarriorsVE
    - instagram: https://instagram.com/bloodwarriorsve
    - discord: http://discord.gg/RUycPWp
    - email: bloodwarriors2018@gmail.com
clans:
  - name: Blood Warriors
    tag: 8PVVYPLG
  - name: Bloody Warriors
    tag: P02UP0JG
```
