### ISSUE TITLE
ADD two more clan to 小蘑菇联盟 total is 7 clans in famliy

### ISSUE THREAD

**Issue by tudouWang** [RoyaleAPI/cr-api-ux#411]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 小蘑菇联盟
    tag: VGQRQG
  - name:小蘑菇庄园
    tag: 9C2VYUYP
  - name:小蘑菇乐园
    tag: 9G29GUJU
```

**Comment by smlbiobot** [comment]
I only see 3 clans here. You also need to fill out the rest of the info

**Comment by smlbiobot** [comment]
hello?? @tudouWang

**Comment by smlbiobot** [comment]
I just realized that you might mean to update this config. I have added for you:

```yml
name: 小蘑菇联盟
key: mushroom
color: red
emblem: A_Char_King_03
track: false
feature: true
sort: trophy
info:
  description: >
    欢迎大家加入小蘑菇家族，部落群请加首领微信qxh121527，部落宝箱最低20冠，宝箱合格捐兵700长老，宝箱前三捐兵1200副首，安活跃度晋升职位，加微信注明 id和杯段！祝大家玩得愉快
clans:
  - name: 小蘑菇联盟
    tag: VGQRQG
  - name: 小蘑菇庄园
    tag: 9C2VYUYP
  - name: 小蘑菇乐园
    tag: 9G29GUJU
  - name: 小蘑菇军团
    tag: 80JJLQ0L
  - name: 小蘑菇帝国
    tag: 20YP0JPJ
  - name: 流风回雪
    tag: 2LQG2PCP
  - name: 罗沫生尘
    tag: 9Y2GV82U
```
