### ISSUE TITLE
Clan-Family request "Project DisCom"

### ISSUE THREAD

**Issue by daerias** [RoyaleAPI/cr-api-ux#414]
```yaml
name: Project DisCom Clan-Family
key: PDC
color: black
emblem: Flame_03
info: www.Project-DisCom.ga Clanfamilie α+β (α ab 4k+ der Rest β) AKTIV/LOYAL/etwas durchgeknallt royaleapi.com - Discord PFLICHT ⚠️
  logo: https://i.imgur.com/wnWc4B8.png
  description: >
    **Project DisCom** Unser Clan ist unsere Discord Community, die auf Clans als Außenstellen verteilt ist. Der Clan wurde im Mai 2017 ins Leben gerufen. Wir haben viel Gutes und Schlechtes durchgemacht und viel an Erfahrung gewonnen und nun ist der Clan perfekt. Wir legen viel Wert auf Vertrauen, Höflichkeit, familiäre Atmosphäre und allgemeine Aktivität! Du hast es satt vom Clan zum Clan zu jumpen und ständig auf der Suche nach was passendem zu sein? Project DisCom wird dir das bieten was du lange gesucht hast! ;-)


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discordapp.com/invite/7twprPm
    - website: http://www.project-discom.ga
clans:
  - name: Project DisCom α
    tag: 9vrjl2v9
  - name:Project DisCom β
    tag: pqqy0y8q
```

**Comment by smlbiobot** [comment]
```yml
name: Project DisCom Clan-Family
key: PDC
color: black
emblem: Flame_03
info:
  logo: /static/img/brands/logo/project-discom.png
  description: >
    **Project DisCom** Unser Clan ist unsere Discord Community, die auf Clans als Außenstellen verteilt ist. Der Clan wurde im Mai 2017 ins Leben gerufen. Wir haben viel Gutes und Schlechtes durchgemacht und viel an Erfahrung gewonnen und nun ist der Clan perfekt. Wir legen viel Wert auf Vertrauen, Höflichkeit, familiäre Atmosphäre und allgemeine Aktivität! Du hast es satt vom Clan zum Clan zu jumpen und ständig auf der Suche nach was passendem zu sein? Project DisCom wird dir das bieten was du lange gesucht hast! ;-)


    www.Project-DisCom.ga Clanfamilie α+β (α ab 4k+ der Rest β) AKTIV/LOYAL/etwas durchgeknallt royaleapi.com - Discord PFLICHT ⚠️
  social:
    - discord: https://discordapp.com/invite/7twprPm
    - website: http://www.project-discom.ga
clans:
  - name: Project DisCom α
    tag: 9VRJL2V9
  - name: Project DisCom β
    tag: PQQY0Y8Q
```
