### ISSUE TITLE
The 3 Lions Family

### ISSUE THREAD

**Issue by Lochshin** [RoyaleAPI/cr-api-ux#418]
```yaml
name: The 3 Lions Family
key: t3l
color: Grey
emblem: flag_j_03
info:
  logo:
  description: >
    The 3 Lions Family is a growing community of active Royale players looking to continue to improve and sharpen their skills in an environment that is supportive and challenging.  Founded Day 1, we continue to look for strong active players that are looking for a clan that is just as dedicated as they are.
  social:
    - discord: http://discord.gg/Z3KQRxU
    - youtube: https://www.youtube.com/channel/UC6evLrbX01lkhtdQcVIGAjA
    - instagram: https://instagram.com/theofficial3lions
    - facebook: https://facebook.com/groups/The3Lions
    - email: mailto: the3lions.cr@gmail.com
clans:
  - name: The 3 Lions
    tag: 2GQCJVU
  - name: The 3 Lions II
    tag: PPVLGJ0U
  - name: GreenGreen
    tag: 2L89YGQ
```

**Comment by smlbiobot** [comment]
```yml
name: The 3 Lions Family
key: t3l
color: grey
emblem: flag_j_03
info:
  logo:
  description: >
    The 3 Lions Family is a growing community of active Royale players looking to continue to improve and sharpen their skills in an environment that is supportive and challenging.  Founded Day 1, we continue to look for strong active players that are looking for a clan that is just as dedicated as they are.
  social:
    - discord: http://discord.gg/Z3KQRxU
    - youtube: https://www.youtube.com/channel/UC6evLrbX01lkhtdQcVIGAjA
    - instagram: https://instagram.com/theofficial3lions
    - facebook: https://facebook.com/groups/The3Lions
    - email: mailto:the3lions.cr@gmail.com
clans:
  - name: The 3 Lions
    tag: 2GQCJVU
  - name: The 3 Lions II
    tag: PPVLGJ0U
  - name: GreenGreen
    tag: 2L89YGQ
```
