### ISSUE TITLE
Family: Devil Drops Family

### ISSUE THREAD

**Issue by blowsie** [RoyaleAPI/cr-api-ux#420]
```yaml
name: Devil Drops Family
key: dd
color: purple
emblem: Elixir_02
info:
  logo: https://cdn.discordapp.com/icons/396041799723909121/ec6dd9a2b9f499c3264bfbed8bea7ffa.png
  description: >
    **Devil Drops** is an competitive yet fun family of clans found in Clash Royale.
    We are active on discord and highly motivated to help each other get the best out of our cards and decks.
  social:
    - twitter: 
    - discord: https://discord.gg/BUxC573
    - twitch: 
    - reddit: 
    - youtube:
    - website: 
clans:
  - name: Devil Drops
    tag: 22JPVR92
  - name: Devil Drops II
    tag: 8JPGP0U9
```

**Comment by smlbiobot** [comment]
```yml
name: Devil Drops Family
key: dd
color: purple
emblem: Elixir_02
info:
  logo: /static/img/brands/logo/devil-drops.png
  description: >
    **Devil Drops** is an competitive yet fun family of clans found in Clash Royale.
    We are active on discord and highly motivated to help each other get the best out of our cards and decks.
  social:
    - discord: https://discord.gg/BUxC573
clans:
  - name: Devil Drops
    tag: 22JPVR92
  - name: Devil Drops II
    tag: 8JPGP0U9
```
