### ISSUE TITLE
ACDC Clan Family

### ISSUE THREAD

**Issue by gbere** [RoyaleAPI/cr-api-ux#422]
```yaml
name: ACDC
key: acdc
color: blue
emblem: Bolt_02
info:
  logo:
  description: >
    La historia del clan ACDC empezó en el clash of clans,
    un clan activo y guerrero, (ACDC #8R8Q8P82 nivel 17).


    El 2/2/16 nació la beta en android de clash royale y el clan ACDC #VVVG.
clans:
  - name: ACDC
    tag: VVVG
  - name: ACDC 2.0
    tag: UQPJPRQ
  - name: ACDC 3.0
    tag: GU088C0
  - name: ACDC 4.0
    tag: ULQQ92C
```
