### ISSUE TITLE
Famille Karmes PDF December 2018 Update

### ISSUE THREAD

**Issue by diegotercero** [RoyaleAPI/cr-api-ux#424]
```yaml
name: Karmes PDF
key: karmespdf
color: blue
emblem: Moon_03.png
feature: true
track : true
info: 
  description: >
    **Karmes PDF** est un famille orientée RUSH/GDC. Objectif clan 1 -> TOP GDC /
    Objectif clans 2, 3, 4 et 5 -> TOP RUSH. Famille mature et stable. Allers/Retours interdits.
    Pour infos contacter **karon69120** app mobile LINE ou https://discord.gg/yjx7uY
  social:
    discord: https://discord.gg/yjx7uY
clans:
  - name: Karmes PDF
    tag: 8L8C2VJQ
  - name: Karmes PDF 2
    tag: 8Y0LRR92
  - name: Karmes PDF 3
    tag: 2C8L2299
  - name: Karmes PDF 4
    tag: 900LYVVU
  - name: Karmes PDF 5
    tag: P90L0CJP
```
