### ISSUE TITLE
Woodland

### ISSUE THREAD

**Issue by jedholm** [RoyaleAPI/cr-api-ux#426]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Woodland
key: woodland
color: red
emblem: Pine_02
info:
  logo:
  description: >
    **Woodland** är Sveriges #1 i Clan Wars och #1 i trophies och vi närmar oss stadigt topp 200 global i Clan Wars. Vår klan är en bra plats för att utveckla ditt spel till en högre nivå och omge dig med spelare med den största ambitionen. Vi är en familj med fem klaner (Woodland 2 topp 10 i Sverige) så alla seriösa spelare över 4k trophies har vi säkerligen en plats för i någon av våra klaner. Ansök gärna via vår discord server http://discord.gg/wtUBxHh


  social:
    - discord: http://discord.gg/wtUBxHh
    - website: http://www.woodlandcr.se
clans:
  - name: Woodland
    tag: 29Y2UL82
  - name: Woodland 2
    tag: 2GQ90YLG
  - name: Woodland 3
    tag: 98J89V0U
  - name: Woodland 4
    tag: P29U2UC0
  - name: Woodland 5
    tag: P9G0LCC9
```
