### ISSUE TITLE
Powder Nation Family Config

### ISSUE THREAD

**Issue by misaugstad** [RoyaleAPI/cr-api-ux#428]
```yaml
name: Powder Nation
key: powdernation
color: green
emblem: Coin_01
info:
  logo: https://media.simplecast.com/podcast/logo_image/2389/medium.jpg
  description: >
    We are fans of the hit podcast Do By Friday. Challenge each other, challenge yourself.
  social:
    - twitter: https://twitter.com/dobyfriday
    - reddit: https://www.reddit.com/r/DoByFriday/
    - website: http://dobyfriday.com/
clans:
  - name: The IAP Boys
  - tag: C08R2V
  - name: Powder Nation
    tag: 8G8CYR90
  - name: POWDER NATION 2
    tag: 8VVVCL9P
  - name: powder nation
    tag: 8GQCR20J
- sort: trophy
```
