### ISSUE TITLE
Team Demonic Family Update

### ISSUE THREAD

**Issue by TeamDemonic** [RoyaleAPI/cr-api-ux#430]
```yaml
name: Team Demonic
key: TeamDemonic
color: red
track: true
emblem:Skull_06
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    **Team Demonic** : Located in Italian Area.
Demonic Pride: Mother Clan  ; Demonic 4.0: Academy of Demonic Pride; Demonic 2.0: Academy of Demonic 4.0; Demonic 3.0: Ex Academy, Lost; Demonic Royale: the first born; Demonic Elite: The Clan of the strongest in wars 
  
 clans:
  - name: Demonic Pride
    tag: 2G8LYY0R
  - name: Demonic 3.0
    tag: 9LU2LG0C  
  - name: Demonic 4.0
    tag: 9VG89LG9
  - name: Demonic 2.0
    tag: Y0PC28PG
  - name: Demonic Elite
    tag: P082G990
  - name: Demonic Royale
    tag: YCVVU9

  
```
