### ISSUE TITLE
Apex Predators Clan Family

### ISSUE THREAD

**Issue by J3H4M970N** [RoyaleAPI/cr-api-ux#435]
```yaml
name: Apex Predators Clan Family
key: APEX
color: Blue
emblem: Crown_03.png
info:
  logo: https://imgur.com/a/ubKNr5l
  description: **Apex Predators** is a mobile based gaming family. We are home to competitive and casual gamers. We started our journey to greatness 3 years ago and have grown into a team of over 150 members.


We are active, dedicated and driven to be the best. **Come join the pride, greatness lies within!**
  social:
    - discord: http://discord.gg/JYerWAD
    - youtube: https://m.youtube.com/channel/UC4VCvb6lVjIZNjmRyMQn8mA
    - email: thelions.clashroyale@gmail.com mailto: Admin
clans:
  - name: The Lions
    tag: 2Q2ULLQ
  - name: The Wolves
    tag: 9Q98JQCV
  - name: Jaguars [APEX]
    tag: PCG2V9V8
  - name: FireStorm
    tag: Y022VJVJ
```
