### ISSUE TITLE
Headhunters Clan Family

### ISSUE THREAD

**Issue by arranstuart2000** [RoyaleAPI/cr-api-ux#436]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Headhunters Clan Family
key: hh
color: black 
emblem: flame_04
info: 
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/yGhaTV2
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Headhunters 
    tag: 9YC0V2JP
  - name: The Regulators 
    tag: 9UCQCC80
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
```yml
name: Headhunters Clan Family
key: hh
color: black 
emblem: flame_04
clans:
  - name: Headhunters 
    tag: 9YC0V2JP
  - name: The Regulators 
    tag: 9UCQCC80

```
