### ISSUE TITLE
[Family Update] Kasalla

### ISSUE THREAD

**Issue by lemonixxx** [RoyaleAPI/cr-api-ux#437]
Update: 

- new description
- added twitter 
- added Clan "BerlinciTy"
- delete Clan "Kasalla Castle" 

```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/kasalla.jpg
  description: >
**Kasalla** ist eine der größten deutschsprachigen Clash Royale Clan Familien.
Wir haben eine eigene eSport Liga, die **RDKL**, sowie ein eigens eSport Team bei dem sich auch neue Mitglieder immer beweisen können!
Durch unsere Sponsoren ist es uns erlaubt regelmäßige Turniere mit Preisgeldern zu veranstalten.
Außerdem besitzen wir einen gut organisierten Discord Server(1000+ Mitglieder), mit eigenen Chaträumen für Tauschmarken, Turniere, Streaming usw. rund um Clash Royale.   
Aufgrund unserer vielen Clans ist Jeder Spieler bei uns willkommen und gut aufgehoben. 
Was willst du mehr? JOIN NOW!


  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://instagram.com/kasallacr
    - twitter: https://twitter.com/discordleague?lang=de

clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: provocatione™
    tag: 9Y8YVJYP
  - name: i.9 eSports
    tag: 80ULQRLU 
  - name: BerlinciTy
    tag: 2R880VJV
  - name: Kasalla Phoenix
    tag: PPYG2QPJ  
  - name: Kasalla War
    tag: P0Q220PY
  - name: Kasalla Deluxe
    tag: 9CVCRP9L 
  - name: Kasalla Academy
    tag: PUGP20P2  
  - name: Kasalla Gala™
    tag: 9R99Y29L
```
