### ISSUE TITLE
QLASHFamilyClan

### ISSUE THREAD

**Issue by matteo9919** [RoyaleAPI/cr-api-ux#439]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: QLASH Family Clan
key: QLASH
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Arcadia
    tag: PQCC9JY8
  - name: QLASH Beyond
    tag: P92VY2LY
  - name: QLASH Beyond2
    tag: 9CR80CRG
  - name: QLASH Beyond3
    tag: 9QVQ8PG2
  - name: QLASH Beyond4
    tag: 9QL0JJUU
  - name: QLASH Beyond5
    tag: 9VQR88U2
  - name: QLASH Chaos
    tag: 9U2QUL8U
  - name: QLASH Chaos2
    tag: 922RP8GL
  - name: QLASH Chaos3
    tag: 92QRY8G0
  - name: QLASH Chaos4
    tag: 9QCUPGQP
  - name: QLASH Danger
    tag: 98PL02LC
  - name: QLASH Danger2
    tag: P02LULUR
  - name: QLASH Danger3
    tag: 9GUL90UL
  - name: QLASH Danger4
    tag: P08RJVVL
  - name: QLASH Diamonds
    tag: P0LGP80U
  - name: QLASH Diamonds2
    tag: 9QCVJLJ2
  - name: QLASH Diamonds3
    tag: P2QGRLPV
  - name: QLASH Diamonds4
    tag: P0LRLQC9
  - name: QLASH Echo
    tag: PY02QJ8V
  - name: QLASH Echo2
    tag: 9J9YYYVR
  - name: QLASH Echo3
    tag: 9G0Q0P2Y
  - name: QLASH Echo4
    tag: 9GC09GUG
  - name: QLASH Eclipse
    tag: P0LLG9RG
  - name: QLASH Eclipse2
    tag: 9QRVUQ8Y
  - name: QLASH Eclipse3
    tag: 9vvujlgp
  - name: QLASH Eclipse4
    tag: pur922cc
  - name: QLASH Eclipse5
    tag: PQ290Q0R
  - name: QLASH Egypt
    tag: PLJJQ0Y9
  - name: QLASH Egypt II
    tag: plcujrp2
  - name: QLASH Egypt III
    tag: PLCPRPY0
  - name: QLASH Egypt IV
    tag: P0L28C0R
  - name: QLASH Egypt V
    tag: P902VV0J
  - name: QLASH Egypt VI
    tag: PYV2QVGV
  - name: QLASH Egypt VII
    tag: PLC8JJ2G
  - name: QLASH Exiled
    tag: PYGYQ9P8
  - name: QLASH GSD
    tag: 9QJGQ9P2
  - name: QLASH GSD1
    tag: P0J8RGU8
  - name: QLASH GSD2
    tag: 9R8CG2LG
  - name: QLASH GSD3
    tag: 9QJU89RV
  - name: QLASH GSD4
    tag: P0JGG08P
  - name: QLASH Hades
    tag: 9U2UYRQU
  - name: QLASH Hades2
    tag: P08288YG
  - name: QLASH Hellas
    tag: 9QJ9YJJJ
  - name: QLASH Hellas2
    tag: 9QJQJGPV
  - name: QLASH Hellas3
    tag: PLC8CPU
  - name: QLASH Hellas4
    tag: P2UJC9J2
  - name: QLASH Hellas5
    tag: 9V20JU09
  - name: QLASH Hellas Ac
    tag: PYLC0QYQ
  - name: QLASH India
    tag: P2GPVVLP
  - name: QLASH India2
    tag: P0Q2P8C0
  - name: QLASH India3
    tag: 9VLL8VL8
  - name: QLASH ITLegends
    tag: 9QJURCQ0
  - name: QLASH Itc
    tag: P0C28V0C
  - name: QLASH Itc2
    tag: PLVLLRVP
  - name: QLASH Itc3
    tag: 9UQCLRGV
  - name: QLASH Itc4
    tag: 9CYL929Q
  - name: QLASH Latam
    tag: PL2299Y0
  - name: QLASH Latam1
    tag: 9RY2CCYVP
  - name: QLASH Latam2
    tag: 9UY8P2QL
  - name: QLASH Nàpoles
    tag: 9RCJU2UU
  - name: QLASH Revenge
    tag: PYV0PQYJ
  - name: QLASH Revenge2
    tag: PLU0JJL8
  - name: QLASH Sentry
    tag: 9QY9JG09
  - name: QLASH Sentry2
    tag: 92URLJYG
  - name: QLASH Sentry3
    tag: 99LQJ8GY
  - name: QLASH Sentry4
    tag: 90QVQRCU
  - name: QLASH Sentry5
    tag: 98Y9VRYP
  - name: QLASH Sentry6
    tag: 9G2YCULP
  - name: QLASH Top Clan
    tag: 9989JURU
  - name: QLASH Trident
    tag: 9L8R8G98
  - name: QLASH Trident2
    tag: PPLVRL0R
  - name: QLASH Trident3
    tag: 9UVU00JG
  - name: QLASH Void
    tag: 9QCVCGQU
  - name: QLASH Void2
    tag: 9QV2P0CR
  - name: QLASH Void3
    tag: 9QVJJ9GJ
  - name: QLASH Void4
    tag: 9LVLQG9C
  - name: QLASH Void5
    tag: 9CJ02VQJ
```

**Comment by smlbiobot** [comment]
Great but we can’t support a family having more than 20 clans. Please break them apart into multiple configuration. We can theoretically list them but it will probably timeout. Please see how Nova + Team Liquid does theirs and submit multiple configs. thanks!

**Comment by matteo9919** [comment]
name: QLASH Italian Main Clans
key: QLASH
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Beyond
    tag: P92VY2LY
  - name: QLASH Chaos
    tag: 9U2QUL8U
  - name: QLASH Danger
    tag: 98PL02LC
  - name: QLASH Diamonds
    tag: P0LGP80U
  - name: QLASH Echo
    tag: PY02QJ8V
  - name: QLASH Eclipse
    tag: P0LLG9RG
  - name: QLASH Exiled
    tag: PYGYQ9P8
  - name: QLASH Hades
    tag: 9U2UYRQU
  - name: QLASH ITLegends
    tag: 9QJURCQ0
  - name: QLASH Itc
    tag: P0C28V0C
  - name: QLASH Nàpoles
    tag: 9RCJU2UU
  - name: QLASH Revenge
    tag: PYV0PQYJ
  - name: QLASH Sentry
    tag: 9QY9JG09
  - name: QLASH Top Clan
    tag: 9989JURU
  - name: QLASH Void
    tag: 9QCVCGQU

**Comment by matteo9919** [comment]
```yaml
name: QLASH Italian Main Clans
key: QLASH
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Arcadia
    tag: PQCC9JY8
  - name: QLASH Egypt
    tag: PLJJQ0Y9
  - name: QLASH GSD
    tag: 9QJGQ9P2
  - name: QLASH Hellas
    tag: 9QJ9YJJJ
  - name: QLASH India
    tag: P2GPVVLP
  - name: QLASH Latam
    tag: PL2299Y0
  - name: QLASH Trident
    tag: 9L8R8G98
```

**Comment by matteo9919** [comment]
```yaml
name: QLASH Italian Academies Clans 1
key: QLASH
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Beyond2
    tag: 9CR80CRG
  - name: QLASH Beyond3
    tag: 9QVQ8PG2
  - name: QLASH Beyond4
    tag: 9QL0JJUU
  - name: QLASH Beyond5
    tag: 9VQR88U2
  - name: QLASH Chaos2
    tag: 922RP8GL
  - name: QLASH Chaos3
    tag: 92QRY8G0
  - name: QLASH Chaos4
    tag: 9QCUPGQP
  - name: QLASH Danger2
    tag: P02LULUR
  - name: QLASH Danger3
    tag: 9GUL90UL
  - name: QLASH Danger4
    tag: P08RJVVL
  - name: QLASH Diamonds2
    tag: 9QCVJLJ2
  - name: QLASH Diamonds3
    tag: P2QGRLPV
  - name: QLASH Diamonds4
  - name: QLASH Echo2
    tag: 9J9YYYVR
  - name: QLASH Echo3
    tag: 9G0Q0P2Y
  - name: QLASH Echo4
  - name: QLASH Eclipse2
    tag: 9QRVUQ8Y
  - name: QLASH Eclipse3
    tag: 9vvujlgp
  - name: QLASH Eclipse4
    tag: pur922cc
  - name: QLASH Eclipse5
```

**Comment by matteo9919** [comment]
```yaml
name: QLASH Iternational Academies 2
key: QLASH
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Egypt II
    tag: PLCUJRP2
  - name: QLASH Egypt III
    tag: PLCPRPY0
  - name: QLASH Egypt IV
    tag: P0L28C0R
  - name: QLASH Egypt V
    tag: P902VV0J
  - name: QLASH Egypt VI
    tag: PYV2QVGV
  - name: QLASH Egypt VII
    tag: PLC8JJ2G
  - name: QLASH GSD1
    tag: P0J8RGU8
  - name: QLASH GSD2
    tag: 9R8CG2LG
  - name: QLASH GSD3
    tag: 9QJU89RV
  - name: QLASH GSD4
    tag: P0JGG08P
  - name: QLASH India
    tag: P2GPVVLP
  - name: QLASH India2
    tag: P0Q2P8C0
  - name: QLASH India3
    tag: 9VLL8VL8

**Comment by matteo9919** [comment]
```yaml
name: QLASH Iternational Academies 2
key: QLASH
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Hellas2
    tag: 9QJQJGPV
  - name: QLASH Hellas3
    tag: PLC8CPU
  - name: QLASH Hellas4
    tag: P2UJC9J2
  - name: QLASH Hellas5
    tag: 9V20JU09
  - name: QLASH Hellas Ac
    tag: PYLC0QYQ
  - name: QLASH Latam1
    tag: 9RY2CCYVP
  - name: QLASH Latam2
    tag: 9UY8P2QL
  - name: QLASH Trident2
    tag: PPLVRL0R
  - name: QLASH Trident3
    tag: 9UVU00JG

**Comment by smlbiobot** [comment]
@matteo9919 thank you. Qlash cannot be the same key for everything, as they will need to be unique. Pls fix that in your config comments.

**Comment by matteo9919** [comment]
@smlbiobot done

**Comment by smlbiobot** [comment]
wrong clan tag for `QLASH Hellas Ac` — corrected below via search:

```yml
name: QLASH International Academies 2
key: QLASH_INT_HD_2
color: Teal
emblem: Flame_04
info:
  logo: /static/img/brands/logo/qlash.jpg
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_ClashRoyale
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Hellas2
    tag: 9QJQJGPV
  - name: QLASH Hellas3
    tag: PLC8CPU
  - name: QLASH Hellas4
    tag: P2UJC9J2
  - name: QLASH Hellas5
    tag: 9V20JU09
  - name: QLASH Hellas Ac
    tag: PYLC0QJQ
  - name: QLASH Latam1
    tag: 9RY2CCYVP
  - name: QLASH Latam2
    tag: 9UY8P2QL
  - name: QLASH Trident2
    tag: PPLVRL0R
  - name: QLASH Trident3
    tag: 9UVU00JG
```

**Comment by smlbiobot** [comment]
added but i think that some of your clan tags are wrong. Please note what is wrong and open new issues …

**Comment by matteo9919** [comment]
wrong clan tag for QLASH GSD2 — corrected below:
```yaml
name: QLASH International Academies 1
key: QLASH_INT_HD_1
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_ClashRoyale
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Egypt II
    tag: PLCUJRP2
  - name: QLASH Egypt III
    tag: PLCPRPY0
  - name: QLASH Egypt IV
    tag: P0L28C0R
  - name: QLASH Egypt V
    tag: P902VV0J
  - name: QLASH Egypt VI
    tag: PYV2QVGV
  - name: QLASH Egypt VII
    tag: PLC8JJ2G
  - name: QLASH GSD1
    tag: P0J8RGU8
  - name: QLASH GSD2
    tag: 9R8CG2LQ
  - name: QLASH GSD3
    tag: 9QJU89RV
  - name: QLASH GSD4
    tag: P0JGG08P
  - name: QLASH India
    tag: P2GPVVLP
  - name: QLASH India2
    tag: P0Q2P8C0
  - name: QLASH India3
    tag: 9VLL8VL8

**Comment by smlbiobot** [comment]
In the future, on the field for your logo, please use:

```yml
logo: /static/img/brands/logo/qlash.jpg
```

**Comment by smlbiobot** [comment]
Your clan tags for Qlash Latam1 and Hellas Ac are wrong. Please update and use this config:

```yml
name: QLASH International Academies 2
key: QLASH_INT_HD_2
color: Teal
emblem: Flame_04
info:
  logo: /static/img/brands/logo/qlash.jpg
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_ClashRoyale
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Hellas2
    tag: 9QJQJGPV
  - name: QLASH Hellas3
    tag: PLC8C2PU
  - name: QLASH Hellas4
    tag: P2UJC9J2
  - name: QLASH Hellas5
    tag: 9V20JU09
  - name: QLASH Hellas Ac
    tag: PYLC0QJQ
  - name: QLASH Latam1
    tag: 9RJ2CYVP
  - name: QLASH Latam2
    tag: 9UY8P2QL
  - name: QLASH Trident2
    tag: PPLVRL0R
  - name: QLASH Trident3
    tag: 9UVU00JG
```

**Comment by smlbiobot** [comment]
And here for HD 1:

```yml
name: QLASH International Academies 1
key: QLASH_INT_HD_1
color: teal
emblem: Flame_04
info:
  logo: /static/img/brands/logo/qlash.jpg
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_ClashRoyale
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en
clans:
  - name: QLASH Egypt II
    tag: PLCUJRP2
  - name: QLASH Egypt III
    tag: PLCPRPY0
  - name: QLASH Egypt IV
    tag: P0L28C0R
  - name: QLASH Egypt V
    tag: P902VV0J
  - name: QLASH Egypt VI
    tag: PYV2QVGV
  - name: QLASH Egypt VII
    tag: PLC8JJ2G
  - name: QLASH GSD1
    tag: P0J8RGU8
  - name: QLASH GSD2
    tag: 9R8CG2LQ
  - name: QLASH GSD3
    tag: 9QJU89RV
  - name: QLASH GSD4
    tag: P0JGG08P
  - name: QLASH India
    tag: P2GPVVLP
  - name: QLASH India2
    tag: P0Q2P8C0
  - name: QLASH India3
    tag: 9VLL8VL8
```
