### ISSUE TITLE
Sharp Enforcers

### ISSUE THREAD

**Issue by ANN0Y1NGHACKER** [RoyaleAPI/cr-api-ux#441]
```yaml
name: Sharp Enforcers
key: Sharp
color: red
emblem: Flame_01
info:
  logo: https://i.imgur.com/HkrWjMo.png
  description: >
    **Sharp Enforcers** is a UAE based clan family with __$enior Pla$ter__ and __ANN0Y1NGHACKER__ as the leaders. It is slowly growing and has a well maintained discord server.
  social:
    - discord: http://discord.gg/KD2sCya
clans:
  - name: Sharp Enforcers
    tag: 8VGCQYQ0
  - name: S.E. Academy
    tag: PUGYLULQ
```
