### ISSUE TITLE
Blood Legions

### ISSUE THREAD

**Issue by VoltaireCR** [RoyaleAPI/cr-api-ux#442]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Blood Legions
key: URL shortname
color: blue
emblem: Bamboo_01.png
…
```
