### ISSUE TITLE
Elizabethans Family

### ISSUE THREAD

**Issue by IronMatrix** [RoyaleAPI/cr-api-ux#447]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Elizabethans Family
key: vicbeth
color: red
emblem: flag_d_02.png 
info: 
  logo: 
  description: >
   Three different level clans all apart of one family, Always aiming higher, both trophies and wars. English speaking but all are welcome. Very active in Wars and day to day. Within our big family we try to help all members with deck edits and playstyle improvements. Always wanting to expand our clan family to new members and players we are bound to have a clan for you.

    Add new line with 2 line breaks as above.
  social:
    clans:
  - name: Elizabethans
    tag: #9RLYVGLY
  - name: Victorians
    tag: #9RY8Q9JP
  - name: Tudors
    tag: #PGJ2909R
```

**Comment by smlbiobot** [comment]
no hash for tags pls

```yml
name: Elizabethans Family
key: vicbeth
color: red
emblem: flag_d_02.png
info:
  logo:
  description: >
   Three different level clans all apart of one family, Always aiming higher, both trophies and wars. English speaking but all are welcome. Very active in Wars and day to day. Within our big family we try to help all members with deck edits and playstyle improvements. Always wanting to expand our clan family to new members and players we are bound to have a clan for you.

    Add new line with 2 line breaks as above.
  social:
    clans:
  - name: Elizabethans
    tag: 9RLYVGLY
  - name: Victorians
    tag: 9RY8Q9JP
  - name: Tudors
    tag: PGJ2909R
```
