### ISSUE TITLE
Clan Family Request

### ISSUE THREAD

**Issue by aleksandarmomic** [RoyaleAPI/cr-api-ux#45]
```yaml
- name: SRB Royal Guard Family
key: srgcf
color: orange
emblem: flag_m_03
info:
  logo: https://drive.google.com/open?id=1DcqeSR774TgeL73W6SKcoqRsG-iF28DV
  description: >
    Well organized and long living Serbian clan family. We have been around from the beginning of Clash Royale.
    Our main clan is always on the global leaderboard top 200.
  social:
    - twitter: https://twitter.com/z4ki_tm
    - youtube: https://www.youtube.com/channel/UCB-jt0_yywOhqgcFLFxXTqA
    - facebook: https://www.facebook.com/srbroyalguard/
    - instagram: https://www.instagram.com/srb.royal.guard/
  clans:
    - name: SRB Royal Guard
      tag: 82JJPPGQ
    - name: SRB Noble Guard
      tag: 8GCQPYLJ
    - name: SRB LegionGuard
      tag: 8GRVJYR0
```

**Comment by Gr8z** [comment]
>  global ladderboard ?

**Comment by aleksandarmomic** [comment]
#190 right now.

**Comment by Gr8z** [comment]
No, I meant you spelled "leaderboard wrong"

**Comment by aleksandarmomic** [comment]
Oops, fixed it. Thanks!

**Comment by smlbiobot** [comment]
Final config

```yaml
  - name: SRB Royal Guard Family
    key: srgcf
    color: orange
    emblem: flag_m_03
    clans:
      - name: SRB Royal Guard
        tag: 82JJPPGQ
      - name: SRB Noble Guard
        tag: 8GCQPYLJ
      - name: SRB LegionGuard
        tag: 8GRVJYR0
    info:
      logo: /static/img/brands/logo/srgcf.png
      description: >
        Well organized and long living Serbian clan family. We have been around from the beginning of Clash Royale.
        Our main clan is always on the global leaderboard top 200.
      social:
        - twitter: https://twitter.com/z4ki_tm
        - youtube: https://www.youtube.com/channel/UCB-jt0_yywOhqgcFLFxXTqA
        - facebook: https://www.facebook.com/srbroyalguard/
        - instagram: https://www.instagram.com/srb.royal.guard/
```
Please keep this for your reference
