### ISSUE TITLE
3 Crown Clan Family

### ISSUE THREAD

**Issue by csimpson11** [RoyaleAPI/cr-api-ux#451]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: 3 Crown Clan Family
key: 3_Crown_Family
color: Blue
emblem: Crown_3
info:
  logo:
  description: >
    Welcome to the **3 Crown Clan Family**! We have a clan available for many levels of players. Our members a very active and willing to help others out. Our Discord has about 80 members in it so it’s a great way for everyone to communicate about war, trades, or just to socialize.


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/8UDSNeV
    - reddit: https://www.reddit.com/message/compose/?to=3C_Coleslaw
clans:
  - name: 3 Crown N' Down
    tag: 2R89V00G
  - name: 3 Crown Bravo
    tag: PRG9CJ90
  - name: 3 Crown Charlie
    tag: P8L8VUCV
```
