### ISSUE TITLE
Beetroot Juice™

### ISSUE THREAD

**Issue by andreaolivieri87** [RoyaleAPI/cr-api-ux#453]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Beetroot Juice™
key: BeetrootJuice
color: purple
emblem: Elixir_02

![elixir_drop](https://user-images.githubusercontent.com/18230311/51066432-64e93580-160a-11e9-8713-c1883eeb24ba.jpg)

info:
  logo: /static/img/brands/logo/elixir_drop.jpg

  description: >

   The Beetroot Juice™ family is one of the most recent and fastest growing families in Clash Royale!
    Since creation, we as a family and individual players have grown immensely
    and continue to today.
    We believe that’s the reason why we have come so far.
    **The family is a place for everyone, as our members come from all around the world,
    from casual to competitive players, old to young,
    active to very active and so on.**
    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join the Family. If you got the Juice. **

  social:   
    - discord: http://discord.gg/jRRqPUG

clans:
  - name: Beetroot Juice™
    tag: PJURC0V0
  - name: BeetrootJuice2™
    tag: P9GRVPQ9

```
