### ISSUE TITLE
Jedi Legion Clan Family

### ISSUE THREAD

**Issue by clashyoda** [RoyaleAPI/cr-api-ux#454]
```yaml
name: Jedi Legion Clan Family
key: JediLegion
color: red
emblem: Skull_05
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    **Jedi Legion** WANTS YOU!  Come join a community of force-wielding lightsaber-slinging Clashers!  We are passionate about player development and want YOU to succeed in reaching your goals!  

Is the Force strong with you?  COME FIND OUT!


social:
    - discord: http://discord.gg/wnCp5VX
clans:
  - name: Jedi Outcasts
    tag: VYG80JY
  - name: Scared Sithless
    tag: 98VQCRG8
  - name: Jedi
    tag: 28209U8
  - name: Jedi Knights
    tag: P82L2R
  - name: Jedi Alliance
    tag: PLQ99LCC
  - name: Star Warz Fans
    tag: 28LPL9G
  - name: SithlessAcademy
    tag: 9CLPR20J
  - name: Sithless Legion
    tag: Y2GPGPLR
```
