### ISSUE TITLE
[Update] Sharp Enforcers

### ISSUE THREAD

**Issue by ANN0Y1NGHACKER** [RoyaleAPI/cr-api-ux#456]
## Update:
* I previously uploaded the wrong logo and have provided the new one.
* Fixed spelling errors in description.

```yaml
name: Sharp Enforcers
key: Sharp
color: red
emblem: Flame_01
info:
  logo: https://imgur.com/aSpEya7
  description: >
    Sharp Enforcers family consist of two clans, **Sharp Enforcers** as main clan and **SE Academy** to recruit talented Pro Players. 


    We use all the possible technologies to monitor the performance of our players, analyzing their battles, define suitable decks for each one according to the current META. 


    We manage both of our clans through the discord group supported with own created BOT (work in progress) to serve our purpose. 


    Our future aim is to exist in the competitive E-Sport marketplace. 


    _Social Media presence is being planned and launch will take place in the near future._


    We will be pleased to have you as an active member of our family.


    Yours,
    Sharp Enforcers Family.


  social:
    - discord: http://discord.gg/KD2sCya
clans:
  - name: Sharp Enforcers
    tag: 8VGCQYQ0
  - name: S.E. Academy
    tag: PUGYLULQ
```
