### ISSUE TITLE
3 Crown Family (Update: Description & Key if possible)

### ISSUE THREAD

**Issue by csimpson11** [RoyaleAPI/cr-api-ux#457]
```yaml
name: 3 Crown Clan Family
key: 3Crown
color: blue
emblem: Crown_03
info:
  description: >
    Welcome to the **3 Crown Clan Family**! We are a competitive clan family that focuses on War and Player Progression. We are looking for players that are War focused and looking for a long-term clan.


    We have a clan available for many levels of players. Our members are very active and willing to help everyone in our family succeed. Our Discord has 100+ members so it’s a great way for everyone to communicate about war, trades, or just to socialize.
  social:
    - discord: https://discord.gg/8UDSNeV
    - reddit: https://www.reddit.com/message/compose/?to=3C_Coleslaw
clans:
  - name: 3 Crown N' Down
    tag: 2R89V00G
  - name: 3 Crown Bravo
    tag: PRG9CJ90
  - name: 3 Crown Charlie
    tag: P8L8VUCV
```

**Comment by csimpson11** [comment]
Sorry for the quick update. 

I saw an error in the description and want to edit the Key if possible.

**Comment by csimpson11** [comment]
Edit: Fixed color issue as well. Wasn't all lower case.

**Comment by smlbiobot** [comment]
```yml
name: 3 Crown Clan Family
key: 3Crown
color: blue
emblem: Crown_03
info:
  logo:
  description: >
    Welcome to the **3 Crown Clan Family**! We are a competitive clan family that focuses on War and Player Progression. We are looking for players that are War focused and looking for a long-term clan.


    We have a clan available for many levels of players. Our members are very active and willing to help everyone in our family succeed. Our Discord has 100+ members so it’s a great way for everyone to communicate about war, trades, or just to socialize.
  social:
    - discord: https://discord.gg/8UDSNeV
    - reddit: https://www.reddit.com/message/compose/?to=3C_Coleslaw
clans:
  - name: 3 Crown N' Down
    tag: 2R89V00G
  - name: 3 Crown Bravo
    tag: PRG9CJ90
  - name: 3 Crown Charlie
    tag: P8L8VUCV
```
