### ISSUE TITLE
Leviatano Family

### ISSUE THREAD

**Issue by jesushot** [RoyaleAPI/cr-api-ux#458]
```yaml
name: Leviatano
key: lev
color: black
emblem: Elixir_02
info:
  logo: 
  description: >
    	**Leviatano** is the official clan of Leviatano, a team competing in Clash Royale. 
	The five clans below comprise the Clan Family, which is home to many experienced trophy-pushing and above all clan wars competitor in Italy. The clans were created as a result of a group of friends getting fun during boring lessons, founded by jesus in February 2017.
  social:
    - youtube: https://www.youtube.com/channel/UCG6lsvQ4iuCQ2Gg1XAHVWfg
    - instagram: https://www.instagram.com/leviatanofficial/?hl=it
clans:
 - name: Leviatano	
   tag: 2GUJGQQ2 
 - name: Leviatano 2
   tag: 9V2PYL22
 - name: Leviatano 3
 - tag: 9Q82VL0Q
- name: Leviatano 4
 - tag: 9UYVY9QV
- name: Leviatano 5
 - tag: P0QJPUPQ
…

**Comment by smlbiobot** [comment]
- note spacing

```yml
name: Leviatano
key: lev
color: black
emblem: Elixir_02
info:
  description: >
    **Leviatano** is the official clan of Leviatano, a team competing in Clash Royale.
    The five clans below comprise the Clan Family, which is home to many experienced trophy-pushing and above all clan wars competitor in Italy. The clans were created as a result of a group of friends getting fun during boring lessons, founded by jesus in February 2017.
  social:
    - youtube: https://www.youtube.com/channel/UCG6lsvQ4iuCQ2Gg1XAHVWfg
    - instagram: https://www.instagram.com/leviatanofficial/?hl=it
clans:
 - name: Leviatano
   tag: 2GUJGQQ2
 - name: Leviatano 2
   tag: 9V2PYL22
 - name: Leviatano 3
   tag: 9Q82VL0Q
 - name: Leviatano 4
   tag: 9UYVY9QV
 - name: Leviatano 5
   tag: P0QJPUPQ
```
