### ISSUE TITLE
Legacy Family

### ISSUE THREAD

**Issue by KingLois** [RoyaleAPI/cr-api-ux#459]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Legacy
key: Legacy
color: Red
emblem: Gem_01
info: 
  logo: /static/img/badge/legendary/Gem_01.png?t=1533013025.8350427
  description: >
    Welcome to Legacy!
social:
       - discord:  https://discord.gg/5RMy7Mn
clans:
  - name: Wars of Legacy
    tag: 9GVCUR08
  - name: LegacyAscension
    tag: 299RQGJG

```

**Comment by smlbiobot** [comment]
note spacing

```yml
name: Legacy
key: legacy
color: red
emblem: Gem_01
info:
  logo: /static/img/badge/legendary/Gem_01.png
  description: >
    Welcome to Legacy!
  social:
    - discord: https://discord.gg/5RMy7Mn
clans:
  - name: Wars of Legacy
    tag: 9GVCUR08
  - name: LegacyAscension
    tag: 299RQGJG
```
