### ISSUE TITLE
Panda Dome! Family

### ISSUE THREAD

**Issue by AkitaLuna** [RoyaleAPI/cr-api-ux#461]
```yaml
name: Panda Dome! Family
key: PD
color: blue
emblem: Bamboo_04
  logo: https://imgur.com/a/EaOV0X1
  description: >
    Panda Dome! is the main clan of Panda Dome! Family and was born on October 1st 2017. As the players grew, the clan grew and we haven't stopped growing since. We are a war based community that encourages war and trophy pushing in a friendly but competitive environment. Always on the lookout for active talent to help our family grow bigger!
  social:
       - discord: https://discord.gg/KwbPRzk
clans:
  - name: Panda Dome!
    tag: 8U2JRJJ2
  - name: Panda Dome! 2.0
    tag: 92VLCPUG
  - name: Panda Dome! 3.0
    tag: 9J9VC9GU
```
