### ISSUE TITLE
Clasharmy:)

### ISSUE THREAD

**Issue by ace2awesome** [RoyaleAPI/cr-api-ux#463]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:clasharmy:)
key:#PR2OLCY2
color:bronze
emblem:Bolt_02.png
info:
  logo:
  description: >new clan looking for active members to join the clan
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```
