### ISSUE TITLE
My clan

### ISSUE THREAD

**Issue by ace2awesome** [RoyaleAPI/cr-api-ux#464]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:clasharmy:)
key:
color:red
emblem:Bolt_02.png
info:new/clan/just/started/clash/on
  logo:
  Description:> let’s clash


  social:
    - youtube: Aidanbogardlive3 https://www.youtube.com/channel/aidanbogardlive3
    - email: mailto:ace2awesome@icloud.com
clans:
  - name: 
    tag: 
  - name:
    tag:
  - name:
    tag:
```
