### ISSUE TITLE
Lightning Community Clan Family

### ISSUE THREAD

**Issue by RNKnight1** [RoyaleAPI/cr-api-ux#465]
name: Lightning Community
key: LC
color: Blue
emblem: Bolt_03
info:
  description: >  We are only active players with constant war! Anyone from 0 - INFINITY allowed here. Show your leadership skill to get Co!

clans:
  - name: Lightning Rift
    tag: 9VG0GQ8C
  - name: Lightning Swift
    tag: 9VRPC8UG
  - name: Lightning Drift
    tag: #P90Q99G2

**Comment by smlbiobot** [comment]
```yml
name: Lightning Community
key: LC
color: blue
emblem: Bolt_03
info:
  description: >  
    We are only active players with constant war! Anyone from 0 - INFINITY allowed here. Show your leadership skill to get Co!

clans:
  - name: Lightning Rift
    tag: 9VG0GQ8C
  - name: Lightning Swift
    tag: 9VRPC8UG
  - name: Lightning Drift
    tag: P90Q99G2
```
