### ISSUE TITLE
Wolf Family Clans

### ISSUE THREAD

**Issue by Ulfgardgageguy** [RoyaleAPI/cr-api-ux#466]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

name: Wolf Family clans
key: Wolf
color: black/gold
  description: > Be a part of a great clan family. Work your way up to the top in one of the top clans of United states - The best Wolfpack clan.

  social:
    - discord: http://discord.gg/FaR4yVt

clans:
  - name: Wolfpack
    tag: 2GCLL92
  - name: Wolfpups
    tag: 2YG00LVP
  - name: Wolfden
    tag: 2J2P80CC
  - name: Wolfbetas
    tag: 9929JRUL
  - name: Wolfcubs
    tag: 9RP2Q9Q2

**Comment by smlbiobot** [comment]
```yml
name: Wolf Family clans
key: wolf
color: yellow
info:
  description: >
    Be a part of a great clan family. Work your way up to the top in one of the top clans of United states - The best Wolfpack clan.
  social:
    - discord: http://discord.gg/FaR4yVt
clans:
  - name: Wolfpack
    tag: 2GCLL92
  - name: Wolfpups
    tag: 2YG00LVP
  - name: Wolfden
    tag: 2J2P80CC
  - name: Wolfbetas
    tag: 9929JRUL
  - name: Wolfcubs
    tag: 9RP2Q9Q2
```
