### ISSUE TITLE
Team CMC Clan Family

### ISSUE THREAD

**Issue by ZeNeLLiE** [RoyaleAPI/cr-api-ux#47]
We have changed our clan name. Please use the updated config.

```yaml
name: Team CMC Clan Family
key: cmc
color: orange
emblem: Twin_Peaks_02
info:
  logo: /static/img/brands/logo/cmc.png
  description: >
    **Team CMC (short for Chan Mali Chan)** is a Singapore based family clan with all our clans
    within  the Top 100 locally.

    We pride ourselves in clashing hard (Monthly Tournaments, Intra-Family League) and clashing the
    right way (NO BM-ing allowed).

    Our players have done well in local competitions placing in local live tournaments!

    Chan Mali Chan hoi HOI~

  social:
    - website: https://www.teamcmc.pro
    - twitter: https://twitter.com/TeamCMCGG
    - facebook: https://www.facebook.com/TeamChanMaliChan/
clans:
  - name: CMC Blizzard
    tag: 98R8GU2R
  - name: CMC Blaze
    tag: 98R0JV0Q
  - name: CMC Tempest
    tag: P0UGY9Y0
  - name: CMC Whirlwind
    tag: 9L2UC9Y9
  - name: CMC Quake
    tag: 9RG9G98Q
```
