### ISSUE TITLE
[Family] Galaxies Family

### ISSUE THREAD

**Issue by arnopasta** [RoyaleAPI/cr-api-ux#470]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name:Galaxies Family clans
key:Galaxies
color:violet
emblem:Star_Shine_03.png
info:
  logo:
![galaxiesori2](https://user-images.githubusercontent.com/29351816/51477838-d5831580-1db3-11e9-8729-98206f38b545.png)

  description: >
   ** Galaxies** is a clan that Looks for generous and responsible members for war.We are a friendly clan looking to expand our family.The family is a fame , which as a member of Galaxies will hold the rights and status of Galaxies across all our family clans.**We are International** and so all members around globe are welcomed to our clans.

- **We maintain regular war admin and clean clan management**
- **We all show respect to each other and share our thoughts about clash royale**
- **We maintain high Donations and keep helping each others in need**

_Join any of  our clan to be a part of Galaxies Family,enjoy_



  social:
   
    - discord: http://discord.gg/XvmwEwD
    
clans:
  - name: Galaxies
    tag: RUVQRCY
  - name:Galaxies 2
    tag:PGPYLR2U  
  
```

**Comment by smlbiobot** [comment]
- note spacing

```yml
name: Galaxies Family clans
key: Galaxies
color: violet
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/galaxies.png

  description: >
    **Galaxies** is a clan that Looks for generous and responsible members for war. We are a friendly clan looking to expand our family. The family is a fame, which as a member of Galaxies will hold the rights and status of Galaxies across all our family clans. **We are International** and so all members around globe are welcomed to our clans.


    - **We maintain regular war admin and clean clan management**

    - **We all show respect to each other and share our thoughts about clash royale**

    - **We maintain high Donations and keep helping each others in need**


    _Join any of  our clan to be a part of Galaxies Family,enjoy_
  social:
    - discord: http://discord.gg/XvmwEwD

clans:
  - name: Galaxies
    tag: RUVQRCY
  - name: Galaxies 2
    tag: PGPYLR2U
```
