### ISSUE TITLE
ELITE family clan

### ISSUE THREAD

**Issue by Alex-LuuPro** [RoyaleAPI/cr-api-ux#471]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: ELITE
key: elite
color: red
emblem: flag_n_06
info:
  logo: 
  description: >
    **ELITE** is a high level clan with its feeder **Give Suffer Die**. Requirements for **ELITE* is 4900+ last season and more than 15 level 12+ cards. Also 0.50+ in W/L for War Day battles is required upon entry of **ELITE**. Others will be redirected to the feeder clan. 
  social:
    - discord: http://discord.gg/kHcpTVE
clans:
  - name: ELITE
    tag: YQ2G
  - name: Give Suffer Die
    tag: P28UR9CV
```

**Comment by smlbiobot** [comment]
- missing bold tags

```yml
name: ELITE
key: elite
color: red
emblem: flag_n_06
info:
  logo:
  description: >
    **ELITE** is a high level clan with its feeder **Give Suffer Die**. Requirements for **ELITE** is 4900+ last season and more than 15 level 12+ cards. Also 0.50+ in W/L for War Day battles is required upon entry of **ELITE**. Others will be redirected to the feeder clan.
  social:
    - discord: http://discord.gg/kHcpTVE
clans:
  - name: ELITE
    tag: YQ2G
  - name: Give Suffer Die
    tag: P28UR9CV
```
