### ISSUE TITLE
[Family] 300 

### ISSUE THREAD

**Issue by windias** [RoyaleAPI/cr-api-ux#473]
```yaml
name: 300
key: 300
color: black
emblem: flag_j_03
info:
  description: >
  International clan family with members from all over the world. Every CR lover is welcome no matter the language you speak as long as you behave friendly. Both competitive and casual play styles have a place in our family. 
  All our clans play Clan Wars continuously and always promise top rewards, with most elites in our top international clan 300 and top local clan 3000 Worlds. 

clans:
  - name: 300
    tag: 9GP88
  - name: 3000 Worlds
    tag: 22Y2RU9R
  - name: 3000 Rivers
    tag: 9Y9QLUV9
  - name: 3000 Oceans
    tag: 9R0RQPCQ
  - name: 3000 Skies
    tag: PGPJV9QU
```

**Comment by smlbiobot** [comment]
requires quotes for all-int strings

```yml
name: "300"
key: "300"
color: black
emblem: flag_j_03
info:
  description: >
    International clan family with members from all over the world. Every CR lover is welcome no matter the language you speak as long as you behave friendly. Both competitive and casual play styles have a place in our family.
    All our clans play Clan Wars continuously and always promise top rewards, with most elites in our top international clan 300 and top local clan 3000 Worlds.

clans:
  - name: 300
    tag: 9GP88
  - name: 3000 Worlds
    tag: 22Y2RU9R
  - name: 3000 Rivers
    tag: 9Y9QLUV9
  - name: 3000 Oceans
    tag: 9R0RQPCQ
  - name: 3000 Skies
    tag: PGPJV9QU
```
