### ISSUE TITLE
[Family] TRFF

### ISSUE THREAD

**Issue by NoHaxJustProgram** [RoyaleAPI/cr-api-ux#477]
```yaml
name: The Royal Flame Family
key: trff
color: blue
emblem:
info:
  logo: Flame_04
  description: >
    Welcome to The Royal Flame, we only have the best clashers in the kingdoms. Are you willing to join the flame?


  social:
    - discord: http://discord.gg/6Ks74vN
clans:
  - name: The Royal Flame
    tag: 9L2R0Q9V
```
