### ISSUE TITLE
Apex Predator Gaming [APG]™

### ISSUE THREAD

**Issue by J3H4M970N** [RoyaleAPI/cr-api-ux#478]
```yaml
name: Apex Predator Gaming [APG]™
key: APG
color: Blue
emblem: Crown_03.png
info:
  logo: https://imgur.com/a/ubKNr5l
  description: **Apex Predator Gaming** is a mobile-based gaming family. We are the home of almost three hundred competitive and casual gamers.

**Apex Predator Gaming** is committed to creating a flourishing community where all gamers can come together. We are active, dedicated and driven to be the best. **Come join the pride, greatness lies within!**
  social:
    - discord: http://discord.gg/sWbwqRy
    - youtube: https://m.youtube.com/channel/UC4VCvb6lVjIZNjmRyMQn8mA
    - email: thelions.clashroyale@gmail.com mailto: Admin
clans:
  - name: The Lions
    tag: 2Q2ULLQ
  - name: The Wolves
    tag: 9Q98JQCV
  - name: The Cosmos™
    tag: 9QUGUPUG




```
