### ISSUE TITLE
Clan Family Request

### ISSUE THREAD

**Issue by oscarwk** [RoyaleAPI/cr-api-ux#48]
```
name: 會友鏢局
key: CLASHROYALEHK
color: red
info:
  description: 
作為戰爭民族, 鼓勵大家瘋狂打友誼波, 踴躍捐精! HONG KONG LOCAL TOP 10+ CLAN! 香港部落, 設有WHATSAPP GROUP!! 現招收LV12城活躍玩家, 4400盃以下請先加盟會友鏢局分號/叁號/肆號
  social:
    - youtube: https://www.youtube.com/channel/UCFf-3KDqTK6NWybK2zHqj1w

clans:
  - name: 會友鏢局
    tag: LU02Q0V
  - name: 會友鏢局分號
    tag: 2LPR8GGV
  - name: 會友鏢局叁號
    tag: 2QRUL9RC
  - name: 會友鏢局肆號
    tag: 8U2GQL0G

```

**Comment by smlbiobot** [comment]
Implemented. Please note however that your key is not really a reflection of your clan name. Ideally, we ask that your `key` matches your actual name. Understandably, your name has historic significance that cannot be easily translated, but something like `security` would be a closer match than `clashroyalehk`

https://royaleapi.com/clan/family/clashroyalehk

```yaml
name: 會友鏢局
key: clashroyalehk
color: red
emblem: A_Char_Prince_03
info:
  description:
    作為戰爭民族, 鼓勵大家瘋狂打友誼波, 踴躍捐精! HONG KONG LOCAL TOP 10+ CLAN! 香港部落, 設有WHATSAPP GROUP!! 現招收LV12城活躍玩家, 4400盃以下請先加盟會友鏢局分號/叁號/肆號
  social:
    - youtube: https://www.youtube.com/channel/UCFf-3KDqTK6NWybK2zHqj1w
clans:
  - name: 會友鏢局
    tag: LU02Q0V
  - name: 會友鏢局分號
    tag: 2LPR8GGV
  - name: 會友鏢局叁號
    tag: 2QRUL9RC
  - name: 會友鏢局肆號
    tag: 8U2GQL0G
```
