### ISSUE TITLE
Clan Family Listing Request

### ISSUE THREAD

**Issue by doongmiin** [RoyaleAPI/cr-api-ux#481]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Scunion eSports Family
key: scunion
color: black
emblem: Clover_02
info:
  logo: https://drive.google.com/file/d/1JGSzp-eeErvvpIVuxv4GZgOwX9iqJSRX/view?usp=sharing
  description: >
    *scunion [skuhn-yuhn]: A term used in the late 1960s during the Vietnam War to signal the inflicting of distress, injury, or destruction // as in, "bring the scunion!" **Scunion eSports** is an eSports team competing in the International region of Clash Royale League. Since it began on September 11, 2017, our clans and members have been growing steadily. Our clan comprises members from many different places, different backgrounds, and different ages. We all share our love for the game, donate when possible, help in the Clan Wars when available, and help each other out. Join us, and let's bring the scunion! 


  social:
    - facebook: https://www.facebook.com/scunion.esports.14

clans:
  - name: Scunion eSports
    tag: 82CVUPU2
  - name: Scunion Elites
    tag: 9Y2PUUYV9

```
