### ISSUE TITLE
LawnFamily.yml

### ISSUE THREAD

**Issue by WazieMcDizzle** [RoyaleAPI/cr-api-ux#487]
```yaml
name: Lawn Family
key: lawn
color: green
emblem: Bamboo_04.png
info:
  description: >
    **The Lawn** is a family competetive war and trophhy pushing clans.
clans:
  - name: Get Off My Lawn
    tag: 89QQGQL  
  - name: Grow My Lawn
    tag: PLJ8P20
  - name: Trim My Lawn
    tag: 92PYCGJ0  
```
