### ISSUE TITLE
[Family] Born On Ice

### ISSUE THREAD

**Issue by bornonicefamily** [RoyaleAPI/cr-api-ux#493]
```yaml
name: Born On Ice
key: bornonice
color: teal
emblem: Fugi_03
info:
  logo: https://postimg.cc/rz8DdY8p
  description: >
    **Welcome to the Born On Ice Family!** We are dedicated clan members aged 19 and over and all ages, with competitive and casual clans to fit your needs.

    Participate, Donate, War

    *Join the Family. Become Born On Ice with us today. Apply in Discord.*
  social:
    - discord: http://discord.gg/H3ueGPS
    - instagram: https://instagram.com/bornonicefamily
    - email: mailto: bornonicefamily@gmail.com
clans:
  - name: Born On Ice
    tag: VGV0RP8
  - name: Livin' On Ice
    tag: 82JLJ2VP
```
