### ISSUE TITLE
HK-DIU Family config

### ISSUE THREAD

**Issue by skiing414** [RoyaleAPI/cr-api-ux#50]
```yaml
name: HK-DIU
key: hkdiu
color: olive
track: true
emblem: Gem_04
feature: true
info:
  description: >
    HK-DIU!純香港隊，冇微信，得Whatsapp!只收香港人，所有主隊隊員必須入Whatsapp Group! DIU!JER!ASS!LOL!GAP!WOW!LIN!HEA!GAU! www.HK-DIU.com
  social:
    - twitch: https://www.twitch.tv/darkmoon_hkdiu
    - youtube: https://www.youtube.com/channel/UCK9TBQsdTnsYX3e1sBaPoHQ
    - website: http://www.hk-diu.com/
clans:
  - name: HK-DIU
    tag: PCCQU
  - name: HK-JER
    tag: PG2JY29
  - name: HK-ASS
    tag: JGCPY92
  - name: HK-LOL
    tag: PP22J9J
  - name: HK-GAP
    tag: 200GYVJY
  - name: HK-WOW
    tag: QJQUC9P
  - name: HK-LIN
    tag: 2PLP8CPL
  - name: HK-HEA
    tag: 2YPPJVJ0
  - name: HK-GAU
    tag: 8GL82QV8
```

**Comment by skiing414** [comment]
Is it possible to update detail afterwards? E.G. May add clan logo / facebook detail afterwards. Millions Thanks!

**Comment by smlbiobot** [comment]
Yes, you can update detail afterwards. 

P.S. I am not too very comfortable about the name of the main clan coz… ya know… but since supercell doesn’t censor you, I will add as is… 🌚

**Comment by smlbiobot** [comment]
Implemented: https://royaleapi.com/clan/family/hkdiu/clans

**Comment by skiing414** [comment]
Millions Thanks🙈!!

**Comment by skiing414** [comment]
```yaml
name: HK-DIU
key: hkdiu
color: olive
track: true
emblem: Gem_04
feature: true
info:
  description: >
    HK-DIU!純香港隊，冇微信，得Whatsapp!只收香港人，所有主隊隊員必須入Whatsapp Group! DIU!JER!PAT!LOL!GAP!WOW!LIN!HEA!GAU! www.HK-DIU.com
  social:
    - twitch: https://www.twitch.tv/darkmoon_hkdiu
    - youtube: https://www.youtube.com/channel/UCK9TBQsdTnsYX3e1sBaPoHQ
    - website: http://www.hk-diu.com/
clans:
  - name: HK-DIU
    tag: PCCQU
  - name: HK-JER
    tag: PG2JY29
  - name: HK-PAT
    tag: JGCPY92
  - name: HK-LOL
    tag: PP22J9J
  - name: HK-GAP
    tag: 200GYVJY
  - name: HK-WOW
    tag: QJQUC9P
  - name: HK-LIN
    tag: 2PLP8CPL
  - name: HK-HEA
    tag: 2YPPJVJ0
  - name: HK-GAU
    tag: 8GL82QV8
```
