### ISSUE TITLE
SWEDEN BOYS Family Config

### ISSUE THREAD

**Issue by HuggeK** [RoyaleAPI/cr-api-ux#505]
```yaml
name: SWEDEN BOYS 
key: SB
color: blue
emblem: flag_j_03.png
info:
  description: >
**SWEDEN BOYS** är en klanfamilj i Sverige med klaner i top 10 & 50 skiktet. 
Klanfamiljen har funnits länge. 
Vi har en skön sammanhållning i & mellan klanerna och vi består av medlemmar i alla åldrar. 
Sweden boys 1 är lite mer för den mer aktiva och erfarna spelaren, både i doneringar och war-deltagande.
Sweden boys 2 är för aktiva spelare som inte satsar lika stenhårt som SB1. 
**Välkommen att gå med!**
  social:
    - website: http://swedenboys.home.blog
clans:
  - name: SWEDEN BOYS
    tag: 8LLQV00
  - name: SWEDEN BOYS 2
    tag: 929QQ2RC
  - name: SWEDEN BOYS 3
    tag: 908JVUCU
```
