### ISSUE TITLE
Flow Pandas

### ISSUE THREAD

**Issue by WolnyMotylek** [RoyaleAPI/cr-api-ux#506]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Flow Pandas
key: flow
color: black
emblem: YingYang_02.png
info:
  logo: https://gabrychfotografie.de/wp-content/uploads/2019/02/WhatsApp-Image-2019-02-14-at-12.25.27-520x317.jpg
  description: >
    Aus Public Enemy EL enstanden die 
**FLOW PANDAS**
Durch das Expandieren von Public Enemy enstand Public Enemy EL (Elite). Gemeinsam schafften wir es bis hin zur Legendären Arena als wir uns dazu entschlossen haben, einen neuen Namen für unsere Familie zu finden.
Ein neuer Name erfordert leider Opfer, welche wir gern in Kauf genommen haben. Nach dem Verzicht auf unsere (zum Ende hin) fast 3000 Pokale starten wir neu durch und suchen EUCH um ganz schnell wieder beim CW zu steigen!
Wir suchen stets ambitionierte und ehrgeizige Familienmitglieder, denen eine gute Kommunikation und Loyalität ebenso am Herzen liegen wie uns.
Wir bieten, neben WhatsApp (Offtopic & Topic Gruppen) und Discord, eine erfahrene Führung mit Struktur und einem, stets offenem, Ohr für Ideen und Änderungen.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/FLOW PANDAS
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://gabrychfotografie.de/
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Flow Pandas
    tag: P2GUC2L0
  - name:
    tag:
  - name:
    tag:
```
