### ISSUE TITLE
Update of Nova l India Family Page

### ISSUE THREAD

**Issue by NovaRyquaxera** [RoyaleAPI/cr-api-ux#51]
name: Nova l India Family
key: Nova l India
color: Purple
sort: Trophy & Competitive
emblem:Star_Shine_03
logo:/static/img/brands/logo/nova.svg

info: description: > Official Indian Branch of "Nova eSports Organization" 
Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.
Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. Rising Our Nation to Heights #NovaStrong 

Our Family social:
-twitter: http://twitter.com/NovaIndiaTeam
- discord: https://discord.gg/GS8NZ5M 
- email:NovaIndiaTeam@Gmail.com 
-youtube:https://www.youtube.com/channel/UCE_PBvnk1ibntLz9mm_Ceww

clans:

-Clan:Nova l India
Tag:#8GGC990V

-Clan:Nova l India 2
Tag:#8YRC9VYO

-Clan:Nova l India 3
Tag:#89QY99GY

-Clan:Nova l |N Yodha
Tag:#9RUG9LCP

-Clan:Nova l IND Xtrm
Tag:#9PQY0G8Y

-Clan:Nova l IND Hype
Tag:#8JYJ9JV9

-Clan:Nova l IND Gods
Tag:#9GYPGQYG

-Clan:Nova |N Yodha 2
Tag:#9PV9QVOU

**Comment by smlbiobot** [comment]
@NovaRyquaxera Can you follow the formatting here and update the file instead? The way you have written your config makes it hard for me to update without a lot of manual re-editing. Here‘s your current config:

```yaml
name: Nova l India Family
key: nova_india
color: purple
sort: trophy
emblem: Star_Shine_03
logo: /static/img/brands/logo/nova.svg
info:
  description: >
    Official  Indian Branch of "Nova eSports Organization"


    Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.


    Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. Rising Our Nation to Heights #NovaStrong
  social:
    - twitter: http://twitter.com/NovaIndiaTeam
    - discord: https://discord.gg/GS8NZ5M
    - email: mailto:NovaIndiaTeam@Gmail.com
clans:
  - name: Nova l India
    tag: 8GGC990V
  - name: Nova l India 2
    tag: 8YRC9VY0
  - name: Nova l India 3
    tag: 89QY99GY
  - name: Nova l IND ApeX
    tag: 92VVUVCL
  - name: Nova l IND Hype
    tag: 8JYJ9JV9
  - name: Nova l IND Xtrm
    tag: 9PQY0G8Y
  - name: Nova l IND DarK
    tag: 8UGL2Y92
  - name: Nova l IND Gods
    tag: 8GYPGQYG
```

**Comment by NovaRyquaxera** [comment]
name: Nova l India Family
key: nova_india
color: purple
sort: trophy
emblem: Star_Shine_03
logo: /static/img/brands/logo/nova.svg
info:
  description: >
    Official  Indian Branch of "Nova eSports Organization"


    Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.


    Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. Rising Our Nation to Heights #NovaStrong
  social:
    - twitter: http://twitter.com/NovaIndiaTeam
    - discord: https://discord.gg/GS8NZ5M
    - email: mailto:NovaIndiaTeam@Gmail.com
clans:
  - name: Nova l India
    tag: 8GGC990V
  - name: Nova l India 2
    tag: 8YRC9VY0
  - name: Nova l India 3
    tag: 89QY99GY
  - name: Nova I |N Yodha
    tag: 9RUG9LCP
  - name: Nova l IND Xtrm
    tag: 9PQY0G8Y
  - name: Nova l IND Hype
    tag: 8JYJ9JV9
  - name: Nova l IND Gods
    tag: 8GYPGQYG

**Comment by NovaRyquaxera** [comment]
Just a min I'll send u final thing

**Comment by smlbiobot** [comment]
ok please also escape your markup with the three backticks followed by the word `yaml`. This will prevent Github from turning your markup in the Markdown and keep all the spacing.

Here’s a screenshot on how to do it.

<img width="232" alt="screen shot 2018-04-04 at 6 25 35 pm" src="https://user-images.githubusercontent.com/25040297/38302551-afb760fe-3835-11e8-8f7a-9d33bb7af35f.png">

Backtick is the character to the left of the numeric `1` key on a standard US keyboard.

**Comment by smlbiobot** [comment]
For example, by escaping, my config shows up like this:

<img width="369" alt="screen shot 2018-04-04 at 6 27 43 pm" src="https://user-images.githubusercontent.com/25040297/38302628-f5b66ff0-3835-11e8-9a63-dffe70abd790.png">

while yours show up like this:

<img width="265" alt="screen shot 2018-04-04 at 6 27 52 pm" src="https://user-images.githubusercontent.com/25040297/38302639-ff4fa77a-3835-11e8-8edd-19243d295b88.png">

I hope that you can see the difference — thanks!

**Comment by NovaRyquaxera** [comment]
name: Nova l India Family
key: nova_india
color: purple
sort: trophy
emblem: Star_Shine_03
logo: /static/img/brands/logo/nova.svg
info:
  description: >
    Official  Indian Branch of "Nova eSports Organization"


    Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.


    Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. We are growing at a fast pace in both Ladder and Competitive Gaming.  Rising Our Nation to Heights #NovaStrong
  social:
    - twitter: http://twitter.com/NovaIndiaTeam
    - discord: https://discord.gg/GS8NZ5M
    - email: mailto:NovaIndiaTeam@Gmail.com
    - YouTube: https://www.youtube.com/channel/UCE_PBvnk1ibntLz9mm_Ceww
clans:
  - name: Nova l India
    tag: 8GGC990V
  - name: Nova l India 2
    tag: 8YRC9VY0
  - name: Nova l India 3
    tag: 89QY99GY
 - name: Nova I |N Yodha
    tag: 9RUG9LCP
  - name: Nova l IND Xtrm
    tag: 9PQY0G8Y
  - name: Nova l IND Hype
    tag: 8JYJ9JV9
  - name: Nova l IND Gods
    tag: 8GYPGQYG
  - name: Nova |N Yodha 2
    tag: 9PV9QVOU

**Comment by NovaRyquaxera** [comment]
Not showing yet like that😅

**Comment by NovaRyquaxera** [comment]
```yaml
name: Nova l India Family
key: nova_india
color: purple
sort: trophy
emblem: Star_Shine_03
logo: /static/img/brands/logo/nova.svg
info:
description: >
Official Indian Branch of "Nova eSports Organization"

Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.


Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. We are growing at a fast pace in both Ladder and Competitive Gaming.  Rising Our Nation to Heights #NovaStrong
social:
- twitter: http://twitter.com/NovaIndiaTeam
- discord: https://discord.gg/GS8NZ5M
- email: mailto:NovaIndiaTeam@Gmail.com
- YouTube: https://www.youtube.com/channel/UCE_PBvnk1ibntLz9mm_Ceww
clans:

name: Nova l India
tag: 8GGC990V
name: Nova l India 2
tag: 8YRC9VY0
name: Nova l India 3
tag: 89QY99GY
name: Nova I |N Yodha
tag: 9RUG9LCP
name: Nova l IND Xtrm
tag: 9PQY0G8Y
name: Nova l IND Hype
tag: 8JYJ9JV9
name: Nova l IND Gods
tag: 8GYPGQYG
name: Nova |N Yodha 2
tag: 9PV9QVOU

**Comment by NovaRyquaxera** [comment]
I Guess it's fine now

**Comment by smlbiobot** [comment]
```yaml
name: Nova l India Family
key: nova_india
color: purple
sort: trophy
emblem: Star_Shine_03
logo: /static/img/brands/logo/nova.svg
info:
  description: >
    Official Indian Branch of "Nova eSports Organization"
    

    Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.


    Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. We are growing at a fast pace in both Ladder and Competitive Gaming.  Rising Our Nation to Heights #NovaStrong
  social:
    - twitter: http://twitter.com/NovaIndiaTeam
    - discord: https://discord.gg/GS8NZ5M
    - email: mailto:NovaIndiaTeam@Gmail.com
    - youtube: https://www.youtube.com/channel/UCE_PBvnk1ibntLz9mm_Ceww
clans:
  - name: Nova l India
    tag: 8GGC990V
  - name: Nova l India 2
    tag: 8YRC9VY0
  - name: Nova l India 3
    tag: 89QY99GY
  - name: Nova I |N Yodha
    tag: 9RUG9LCP
  - name: Nova l IND Xtrm
    tag: 9PQY0G8Y
  - name: Nova l IND Hype
    tag: 8JYJ9JV9
  - name: Nova l IND Gods
    tag: 8GYPGQYG
  - name: Nova |N Yodha 2
    tag: 9PV9QVOU
```
