### ISSUE TITLE
[Family Update] [AT]Family

### ISSUE THREAD

**Issue by foxyboss** [RoyaleAPI/cr-api-ux#521]
```yaml
name: "[AT]Family"
key: at-family
color: black
emblem: A_Char_King_02
info:
  description: >
    **[AT]Family**


    Drei Clans definieren unsere Familieve:
  social:
    - website: https://at-family.github.io/at-retrobroz/
  clans:
    - name: "[AT]Sturmreiter"
      tag: 8V0JUL20
    - name: "[AT]retrobroz"
      tag: P20Q8Y9Q
```
