### ISSUE TITLE
Moon Ocean Family config

### ISSUE THREAD

**Issue by alicecyt** [RoyaleAPI/cr-api-ux#53]
```yaml
name: Moon Ocean
key: moonocean
color: violet
track: true
emblem: Moon_03
feature: true
info:
  description: >
    HK clan - Moon Ocean, Welcome all player who like Clash Royale~ Have Clan2 - moon river ~ Welcome to join Whatsapp group~
clans:
  - name: Moon Ocean
    tag: PRLR900
  - name: Moon River
    tag: 2YQJ8QV9
```
