### ISSUE TITLE
WANTED TO BE LISTED!THANKS

### ISSUE THREAD

**Issue by tudouWang** [RoyaleAPI/cr-api-ux#55]
```yaml
- name: 小蘑菇联盟
key: mushroom
color: red
emblem: A_Char_King_03
track: false
feature: true
sort: trophy
info:
  description: >
欢迎大家加入小蘑菇家族，部落群请加首领微信qxh121527，部落宝箱最低20冠，宝箱合格捐兵700长老，宝箱前三捐兵1200副首，安活跃度晋升职位，加微信注明 id和杯段！祝大家玩得愉快
clans:
  - name: 小蘑菇联盟
    tag: VGQRQG
  - name: 小蘑菇军团
    tag: 80JJLQ0L
  - name: 小蘑菇帝国
    tag: 20YP0JPJ
  - name: 流风回雪
    tag: 2LQG2PCP
  - name: 罗沫生尘
    tag: 9Y2GV82U
```

**Comment by smlbiobot** [comment]
http://royaleapi.com/clan/family/mushroom/clans

```yaml
name: 小蘑菇联盟
key: mushroom
color: red
emblem: A_Char_King_03
track: false
feature: true
sort: trophy
info:
  description: >
    欢迎大家加入小蘑菇家族，部落群请加首领微信qxh121527，部落宝箱最低20冠，宝箱合格捐兵700长老，宝箱前三捐兵1200副首，安活跃度晋升职位，加微信注明 id和杯段！祝大家玩得愉快
clans:
  - name: 小蘑菇联盟
    tag: VGQRQG
  - name: 小蘑菇军团
    tag: 80JJLQ0L
  - name: 小蘑菇帝国
    tag: 20YP0JPJ
  - name: 流风回雪
    tag: 2LQG2PCP
  - name: 罗沫生尘
    tag: 9Y2GV82U
```
