### ISSUE TITLE
Atualização Família FFL para BWS, mudança de cor, key, logo, descrição e adicionando clã a família

### ISSUE THREAD

**Issue by SethFalcor** [RoyaleAPI/cr-api-ux#553]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:Brazilian War Ship
key:BWS
color:green
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name:FriendsForLife
    tag:GYGY88
  - name:•ANIQUILADORES•
    tag:9JCJUP98
  - name:-ANIQUILADORES-
    tag:990YQ0
  - name:Brother's BR
    tag:2GUPG002
  - name:༄FFL࿐єχρєяιєи¢є
    tag:PUYJ0QV2
 
```
