### ISSUE TITLE
Update of 會友鏢局 Family Page

### ISSUE THREAD

**Issue by oscarwk** [RoyaleAPI/cr-api-ux#57]
https://github.com/RoyaleAPI/cr-api-ux/issues/48
Thank you for your advice! The clan name could not be translated easily. We will find a better translation for it. We would like to update the details for the clan, add a logo and change the description. Many thanks!!

```
name: 會友鏢局
key: clashroyalehk
color: red
emblem: A_Char_Prince_03
info:
logo: https://holland.pk/uptow/i4/c37e677f5cb2ce3dad9ba0d88d3bc907.jpeg
  description:
    **「會友鏢局」**- 香港部落, 設有Whatsapp Group供四會交流之用, 每個月亦會約戰其他公會進行友誼賽, 歡迎**好戰**/長期刷Challenge玩家加盟, 12勝以上優先考慮, 以禮待人 無禮即踢!!
  social:
    - youtube: https://www.youtube.com/channel/UCFf-3KDqTK6NWybK2zHqj1w
clans:
  - name: 會友鏢局
    tag: LU02Q0V
  - name: 會友鏢局分號
    tag: 2LPR8GGV
  - name: 會友鏢局叁號
    tag: 2QRUL9RC
  - name: 會友鏢局肆號
    tag: 8U2GQL0G
```

**Comment by smlbiobot** [comment]
Updated: https://royaleapi.com/clan/family/clashroyalehk/clans

Fixed some syntax for you:

```yaml
name: 會友鏢局
key: clashroyalehk
color: red
emblem: A_Char_Prince_03
info:
  logo: /static/img/brands/logo/clashroyalehk.jpg
  description: >
    **「會友鏢局」**- 香港部落, 設有Whatsapp Group供四會交流之用, 每個月亦會約戰其他公會進行友誼賽, 歡迎**好戰**/長期刷Challenge玩家加盟, 12勝以上優先考慮, 以禮待人 無禮即踢!!
  social:
    - youtube: https://www.youtube.com/channel/UCFf-3KDqTK6NWybK2zHqj1w
clans:
  - name: 會友鏢局
    tag: LU02Q0V
  - name: 會友鏢局分號
    tag: 2LPR8GGV
  - name: 會友鏢局叁號
    tag: 2QRUL9RC
  - name: 會友鏢局肆號
    tag: 8U2GQL0G
```
