### ISSUE TITLE
TW Clan Family

### ISSUE THREAD

**Issue by penny0107** [RoyaleAPI/cr-api-ux#58]
name: 皇室大聯盟
key: clashroyaletw
color: purple
info:
  description: >
皇室大聯盟、皇室啦啦隊、皇室樂活隊、皇室熱情隊、皇室活力隊、皇室寶寶隊。 設有Line群組請先加入LINEID：jereminelee

clans:
  - name: 皇室啦啦隊
    tag: 200R8RUU
  - name: 皇室樂活隊
    tag: 2G002UVC
  - name: 皇室熱情隊
    tag: 2GGC0Y92
  - name: 皇室活力隊
    tag: 2RGGC2YP
  - name: 皇室寶寶隊
    tag: 8U08VPCY

**Comment by smlbiobot** [comment]
Implemented https://royaleapi.com/clan/family/clashroyaletw/clans

please use this config in the future (remember to add backticks otherwise it won’t format)

```yaml
name: 皇室大聯盟
key: clashroyaletw
color: purple
info:
  description: >
    皇室大聯盟、皇室啦啦隊、皇室樂活隊、皇室熱情隊、皇室活力隊、皇室寶寶隊。 設有Line群組請先加入LINEID：jereminelee
clans:
  - name: 皇室啦啦隊
    tag: 200R8RUU
  - name: 皇室樂活隊
    tag: 2G002UVC
  - name: 皇室熱情隊
    tag: 2GGC0Y92
  - name: 皇室活力隊
    tag: 2RGGC2YP
  - name: 皇室寶寶隊
    tag: 8U08VPCY
```
