### ISSUE TITLE
FiJoYcE - Clan Family Request

### ISSUE THREAD

**Issue by teroroma** [RoyaleAPI/cr-api-ux#60]
Please add my clan to the Clan Family. Many Thanks. 

```yaml
name: FiJoYcE FoRcEs
key: fijoyce
color: red
track: true
emblem: flag_d_02
feature: true
info:
  logo: https://user-images.githubusercontent.com/38520092/38978962-7de30f9e-43eb-11e8-86ac-e8b4e6eaec22.png
  description: >
  歡迎加入「**FiJoYcE**」- 香港前20位部落 | Top 20 Hong Kong Clan. 
  【**YouTube.com/TeRrYxGaming**】- 歡迎訂閱皇室戰爭粵語頻道 | Please Subscribe my Channel (Cantonese).
  social:
- youtube: https://www.youtube.com/TeRrYxGaming
- twitch: https://twitch.tv/TeRrYxGaming
- facebook: https://www.facebook.com/TeRrYxGaming
clans:
- name: FiJoYcE FoRcEs
    tag: CCYJU
- name: FiJoYcE MiNionS
    tag: VG22JGG
```

**Comment by smlbiobot** [comment]
```yaml
name: FiJoYcE FoRcEs
key: fijoyce
color: red
track: true
emblem: flag_d_02
feature: true
info:
  logo: /static/img/brands/logo/fijoyce.png
  description: >
    歡迎加入「**FiJoYcE**」- 香港前20位部落 | Top 20 Hong Kong Clan.
    【**YouTube.com/TeRrYxGaming**】- 歡迎訂閱皇室戰爭粵語頻道 | Please Subscribe my Channel (Cantonese).
  social:
    - youtube: https://www.youtube.com/TeRrYxGaming
    - twitch: https://twitch.tv/TeRrYxGaming
    - facebook: https://www.facebook.com/TeRrYxGaming
clans:
  - name: FiJoYcE FoRcEs
    tag: CCYJU
  - name: FiJoYcE MiNionS
    tag: VG22JGG
```
