### ISSUE TITLE
request to get listed clan family

### ISSUE THREAD

**Issue by barrygor07** [RoyaleAPI/cr-api-ux#61]
name: 政政
key: momo
color: blue
emblem: A_Char_King_03
info:
  logo: https://holland.pk/uptow/i4/6f99ed6cf5876c9449e41448044c8baa.jpeg
  description: 歡迎加入政政大家庭，經常舉辦公會友誼賽~
  social:
    - twitch: https://www.twitch.tv/momo9323
    - youtube: https://www.youtube.com/channel/UCoZuczzuL3mptgzK4Nfx-gQ
    
clans:
  - name: 政政
    tag: 8CU08UQ
  - name: 政政<<fun萌>>
    tag: 29JVVV00
  - name: 政政<<同萌>>
    tag: 2CGCPLV2

**Comment by smlbiobot** [comment]
@barrygor07 someone already registered `clashroyalehk` — please pick something else. Maybe you should uses `momo` ? Soon I will make it so that you can’t register this username as it is highly unfair to others when your name has nothing to do with that.

**Comment by barrygor07** [comment]
momo is ok, thanks

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/momo/clans

```yaml
name: 政政
key: momo
color: blue
emblem: A_Char_King_03
info:
  logo: /static/img/brands/logo/momo.jpg
  description: 歡迎加入政政大家庭，經常舉辦公會友誼賽~
  social:
    - twitch: https://www.twitch.tv/momo9323
    - youtube: https://www.youtube.com/channel/UCoZuczzuL3mptgzK4Nfx-gQ
clans:
  - name: 政政
    tag: 8CU08UQ
  - name: 政政<<fun萌>>
    tag: 29JVVV00
  - name: 政政<<同萌>>
    tag: 2CGCPLV2
```
