### ISSUE TITLE
Request to get Guardians Family listed

### ISSUE THREAD

**Issue by alexiz10** [RoyaleAPI/cr-api-ux#63]
```
- name: Guardians
  key: guardians
  color: blue
  emblem: Sword_02
  info: 
    logo:
      https://drive.google.com/file/d/0B7wCWf7oXle4TmlIdFRLVVRlSzZ3cUFQc3VJMGExdEdYUzZ3/view?usp=drivesdk
    description:
      The Guardians family is made up of 3 trophy-pushing
      clans and 1 clan dedicated to our competitive team players.
      Our main clan, GuardiansGaming, is consistently in Mexico's
      top 200 clans. We enjoy having prized tournaments for our
      players every once in a while.
    social:
      https://twitter.com/GuardiansGM
      https://twitter.com/GuardiansAC
      https://discord.gg/WB9XhU3
  clans:
    - name: GuardiansGaming
      tag: 8QYYGLP2
    - name: GuardianAcademy
      tag: 8G8RQJ2Y
    - name: GuardiansRealms
      tag: 8JYCOVJV
    - name: GG Valhalla
      tag: 99PC9VRQ
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/guardians/clans

Corrected config:

```yaml
name: Guardians
key: guardians
color: blue
emblem: Sword_02
info:
  logo: /static/img/brands/logo/guardians.png
  description: >
    The Guardians family is made up of 3 trophy-pushing
    clans and 1 clan dedicated to our competitive team players.
    Our main clan, GuardiansGaming, is consistently in Mexico’s
    top 200 clans. We enjoy having prized tournaments for our
    players every once in a while.
  social:
    - twitter: https://twitter.com/GuardiansGM
    - twitter: https://twitter.com/GuardiansAC
    - discord: https://discord.gg/WB9XhU3
clans:
  - name: GuardiansGaming
    tag: 8QYYGLP2
  - name: GuardianAcademy
    tag: 8G8RQJ2Y
  - name: GuardiansRealms
    tag: 8JYC0VJV
  - name: GG Valhalla
    tag: 99PC9VRQ
```
