### ISSUE TITLE
Update Family Clan 

### ISSUE THREAD

**Issue by SOSkr** [RoyaleAPI/cr-api-ux#70]
```yaml
  - name: Team Condors
    key: condors
    color: orange
    emblem: Diamond_Star_01
    info:
      description: >
        "Team Condors" is a newly created family, which was founded with 3 leaders of different clans
        
        Our family despite being new we have a lot of experience in different games and with all the desire
        and will to be the best
      social:
        - twitter: http://twitter.com/condorsteam
        - discord: https://discord.gg/ybQ3QwJ
        - facebook: https://www.facebook.com/TeamCondors/
        - email: im.soskr@gmail.com
    clans:
      - name: Team Condors
        tag: 9JRR8G8P
      - name: Team Condors II
        tag: 9CVLRCPR

```
