### ISSUE TITLE
Milkyway family

### ISSUE THREAD

**Issue by HBR8** [RoyaleAPI/cr-api-ux#71]
name: MILKYWAY 
key: MILKYWAY
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: https://i.imgur.com/hNZdXib.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822

**Comment by smlbiobot** [comment]
implemented https://royaleapi.com/clan/family/milkyway/clans

```yaml
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822
```

**Comment by HBR8** [comment]
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822
 - name: M E R C U R Y
     tag: P90VQC8R

**Comment by smlbiobot** [comment]
I don’t understand this. Has this been changed?

**Comment by smlbiobot** [comment]
Also, can you please not just copy and paste the text and lose all the formatting? Ideally, edit this instead:

```yaml
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822


```

Would you prefer a file?

**Comment by HBR8** [comment]
Yeah we have deleted one clan which is mars 




Get Outlook for Android







On Tue, May 22, 2018 at 5:30 PM +0300, "SML" <notifications@github.com> wrote:












Also, can you please not just copy and paste the text and lose all the formatting? Ideally, edit this instead:
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822




Would you prefer a file?

**Comment by smlbiobot** [comment]
Please use a computer in the future.

```yml
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822



```

**Comment by HBR8** [comment]
name: MILKYWAY
key: MILKYWAY
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
logo: https://i.imgur.com/hNZdXib.jpg
description: >
We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
social:
- discord: https://discord.gg/jFKNJ8D
clans:

name: E A R T H
tag: 9VQ8V8YC
name: N E P T U N E
tag: P0JJ9RVJ
name: S A T U R N
tag: P2P9VR02
name: M A R S
tag: 9RURCVRR
name: P L A N E T - X
tag: 99RP2Y2V
name: J U P I T E R
tag: P829Q822
name: M A R S
tag: 9RURCVRR

**Comment by HBR8** [comment]
could you update the information please.

**Comment by smlbiobot** [comment]
@HBR8 We reserve the right to not keep on updating family config every week. We can’t devote all of our resources to update your info. Nearly all of the clan family that we have only update their info possibly once every 6-8 months. I have updated yours almost every week.

Please be patient as we have a lot of other things to do.

**Comment by smlbiobot** [comment]
Can you _please_ quote your yaml…

**Comment by smlbiobot** [comment]
```yaml
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822


```
