### ISSUE TITLE
Evolve Clan listing request

### ISSUE THREAD

**Issue by niktamere** [RoyaleAPI/cr-api-ux#72]
```yaml
name: Evolve™
key: evolve
color: red
emblem: Skull_06
info:
  logo: https://i.imgur.com/hXHg8js.png
  description: >
    **Evolve™ or die!!**
  social:
    - discord: https://discord.gg/aAjhpcm
    - twitter: https://twitter.com/evolvestars

clans:
  - name: Evolve™
    tag: 8G9YRQYL
  - name: Evolve™ 2
    tag: 8QL0JY0Q
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/evolve/clans

```yaml
name: Evolve™
key: evolve
color: red
emblem: Skull_06
info:
  logo: /static/img/brands/logo/evolve.png
  description: >
    **Evolve™ or die!!**
  social:
    - discord: https://discord.gg/aAjhpcm
    - twitter: https://twitter.com/evolvestars
clans:
  - name: Evolve™
    tag: 8G9YRQYL
  - name: Evolve™ 2
    tag: 8QL0JY0Q
```
