### ISSUE TITLE
Malta CR Clan Family

### ISSUE THREAD

**Issue by uXerty** [RoyaleAPI/cr-api-ux#73]
```yaml
name: Malta CR Clan Family
key: maltacr
color: red
track: true
emblem: Diamond_02
feature: true
sort: trophy
info:
  description: >
    **Malta CR Clan Family** is made up of 3 trophy-pushing clans.
    This clan family is made up mostly with some of the most skilled players in Malta.
    We have all 3 clans on the **local leaderboard** with **Malta CR** being **1st**, and our feeders **Malta CR 2** and **Malta CR 3** consistently being the top 10.
    We are accepting any Maltese and English speakers! Ejja minn hemm!
  social:
    - discord: http://discord.gg/TA5J3rc
clans:
  - name: Malta CR
    tag: 8QGVQ9P8
  - name: Malta CR 2
    tag: 8RRL9PGR
  - name: Malta CR 3
    tag: 8RPQJPUU
```
