### ISSUE TITLE
HKAFC - Clan Family Request

### ISSUE THREAD

**Issue by solblue** [RoyaleAPI/cr-api-ux#74]
Please add our clan to the clan families list, thanks!
```yaml
name: HKAFC
key: hkafc
color: red
track: true
emblem: YingYang_01
feature: true
sort: trophy
info:
  logo: https://i.imgur.com/yZYvdIM.jpg
  description: >
    Aaron阿王公會, 歡迎有禮活躍人士, 每週最少捐100卡兼12冠。有意加入可聯繫阿王Facebook粉絲專頁Nova l Aaron。Youtube頻道AaronGamingHK，歡迎訂閱追隨。
  social:
    - twitch: https://www.twitch.tv/nova_aaronhk
    - youtube: https://www.youtube.com/channel/UCKPTdvQF9YS5q3EFVuyM-rg
    - facebook: https://www.facebook.com/NovaAaronHK
clans:
  - name: HKAFC
    tag: 8PY9J0GY
  - name: HKAFC-2nd
    tag: 8PJVVLC8
  - name: HKAFC-3rd
    tag: 8C20GCP9
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/hkafc/clans

```yaml
name: HKAFC
key: hkafc
color: red
track: true
emblem: YingYang_01
feature: true
sort: trophy
info:
  logo: /static/img/brands/logo/hkafc.jpg
  description: >
    Aaron阿王公會, 歡迎有禮活躍人士, 每週最少捐100卡兼12冠。有意加入可聯繫阿王Facebook粉絲專頁Nova l Aaron。Youtube頻道AaronGamingHK，歡迎訂閱追隨。
  social:
    - twitch: https://www.twitch.tv/nova_aaronhk
    - youtube: https://www.youtube.com/channel/UCKPTdvQF9YS5q3EFVuyM-rg
    - facebook: https://www.facebook.com/NovaAaronHK
clans:
  - name: HKAFC
    tag: 8PY9J0GY
  - name: HKAFC-2nd
    tag: 8PJVVLC8
  - name: HKAFC-3rd
    tag: 8C20GCP9
```
