### ISSUE TITLE
Milkyway family update

### ISSUE THREAD

**Issue by HBR8** [RoyaleAPI/cr-api-ux#77]
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822
 - name: M E R C U R Y
     tag: P90VQC8R

**Comment by HBR8** [comment]
Sorry about wrong tag, the correct tag is #P9LJGJ8C

**Comment by smlbiobot** [comment]
```yaml
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
    - discord: https://discord.gg/jFKNJ8D
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: P L A N E T - X
    tag: 99RP2Y2V
  - name: J U P I T E R
    tag: P829Q822
  - name: M E R C U R Y
    tag: P9LJGJ8C


```
