### ISSUE TITLE
Militarium Clan Family Request

### ISSUE THREAD

**Issue by militariumgg** [RoyaleAPI/cr-api-ux#80]
```yaml
name: Militarium Family
key: militarium
color: red
emblem: Flame_03
info:
  logo: https://i.imgur.com/z0yc4ue.png
  description: >
    La familia Militarium consiste en 2 clanes que buscan alcanzar el TOP de ladder de República Dominicana y dominar la escena competitiva del país.

    Fundado el 02/02/2017, siendo un clan relativamente nuevo nos hemos mantenido en el top 20 del país.
    Nuestro objetivo es empujar al máximo a nuestros miembros y demostrar que somos capaces de alcanzar el TOP.
  social:
    - facebook: https://www.facebook.com/militariumgg
    - twitter: https://twitter.com/MilitariumGG
    - instagram: https://www.instagram.com/militariumgg/
    - discord: https://bit.ly/militarium-discord
    - twitch: https://www.twitch.tv/MilitariumGG
    - youtube: https://www.youtube.com/channel/UCLVt5GioffQC2lIgJhlBpVw
    - application: https://bit.ly/militarium-apply-form
    - email: mailto:militariumgg@gmail.com
clans:
  - name: Militarium
    tag: 9QCVCYV8
  - name: Militarium Acad
    tag: 2P80Q28C
```
