### ISSUE TITLE
#CR For Fun families request

### ISSUE THREAD

**Issue by Xelagn** [RoyaleAPI/cr-api-ux#82]
Please add our clans to the clan families list, thanks!

    name: #CR For Fun Family
    key: CRForFun
    color: Teal
    emblem: Tower_03
    sort: trophy
    info:
        logo: https://goo.gl/WnbJ9C
        description: 
            全台最大部落#CR For Fun持續招生中🔥 目前總共十三個部落為全台之最🔥
            不管你分數多少，只要你是活躍玩家，我們絕對都歡迎您❤
    clans:
      - name: #CR For Fun™
        tag: 9RULC0JU
      - name: #CR For Fun開那女孩
        tag: 9JG2928R
      - name: #CR For Fun下屠刀
        tag: 9GQG9Y2G
      - name: #CR For Fun暑假
        tag: 99RRCVJ0
      - name: #CR For Fun好玩
        tag: 20Y8R8L
      - name: #CR For Fun棄治療
        tag: 9G9PVVGJ
      - name: #CR For Fun鴿子
        tag: 9QV8Y20L
      - name: #CR For Fun眼天下
        tag: 9CQP28Y2
      - name: #CR For Fun風箏
        tag: P2VYU0JU
      - name: #CR For Fun馬過來
        tag: 9P2GJJYL
      - name: #CR For Fun好放滿'
        tag: 9V8URYC9
      - name: #CR For Fun生
        tag: 9Q888RVC
      - name: #CR For Fun輕鬆
        tag: 9QJU828U
    social:
        - youtube: https://www.youtube.com/user/b09703021/
        - facebook: https://goo.gl/qK567D

**Comment by smlbiobot** [comment]
Can’t add emoji in the description. Family name starting with `#` is problematic. You can keep the clan name as is. All the `#` signs in clan names need to be escaped so please use the updated config below when you need to update.

Live: https://royaleapi.com/clan/family/crforfun/clans

Updated config:
```yaml
name: "CR For Fun Family"
key: crforfun
color: teal
emblem: Tower_03
sort: trophy
info:
  logo: /static/img/brands/logo/crforfun.png
  description: >
    全台最大部落#CR For Fun持續招生中 - 目前總共十三個部落為全台之最 -
    不管你分數多少，只要你是活躍玩家，我們絕對都歡迎您❤
  social:
    - youtube: https://www.youtube.com/user/b09703021/
    - facebook: https://goo.gl/qK567D
clans:
  - name: "#CR For Fun™"
    tag: 9RULC0JU
  - name: "#CR For Fun開那女孩"
    tag: 9JG2928R
  - name: "#CR For Fun下屠刀"
    tag: 9GQG9Y2G
  - name: "#CR For Fun暑假"
    tag: 99RRCVJ0
  - name: "#CR For Fun好玩"
    tag: 20Y8R8L
  - name: "#CR For Fun棄治療"
    tag: 9G9PVVGJ
  - name: "#CR For Fun鴿子"
    tag: 9QV8Y20L
  - name: "#CR For Fun眼天下"
    tag: 9CQP28Y2
  - name: "#CR For Fun風箏"
    tag: P2VYU0JU
  - name: "#CR For Fun馬過來"
    tag: 9P2GJJYL
  - name: "#CR For Fun好放滿'"
    tag: 9V8URYC9
  - name: "#CR For Fun生"
    tag: 9Q888RVC
  - name: "#CR For Fun輕鬆"
    tag: 9QJU828U
```
