### ISSUE TITLE
Clan Family configuration

### ISSUE THREAD

**Issue by AAsuitedAA** [RoyaleAPI/cr-api-ux#83]
name: Omega eSports
key: omegaesports
color: blue
track: true
emblem: Star_Shine_01
feature: true
info:
  logo: http://www.omegaesports.net/wp-content/uploads/2018/02/omega_esports-e1519316331997.png
  description: >
    The Omega eSports its a international eSports organization. On Clash Royale there are more then 60 officials clans Omega! Here you can find only the mains, for full list you can vist out website! 
We have others competitive team with name "Omega" that participating to mains international competitions.
 #Omega_OP

  social:
    - facebook: https://www.facebook.com/OmegaeSportss/
    - twitter: https://twitter.com/omegaaesports
    - discord: https://discordapp.com/invite/7HaqZeK
    - telegram: https://www.t.me/omegaesports
    - website: http://www.omegaesports.net
    - email:  mailto_info@omegaesports.net

clans:
  -name: Omega™ ITLegends
  -tag: 8GUJ9J8G
  -name: Omega™ ITC
  -tag: 90G8Y8GP
  -name: Omega™ Mugiwara
  -tag: 90RR92PJ
  -name: Omega™ Napoles
  -tag: 8C98CGJR
  -name: Omega™ Eclipse
  -tag: 8RUPU2UR
  -name: Omega™ Fighters
  -tag: 8Q2JV0QV
  -name: Omega™ Insane
  -tag: 8VUU8RLJ
  -name: Egypt Omega™
  -tag: 8GULP98Q
  -name: Omega™ Panama
  -tag: 9C2VPYRU
  -name: Omega™Kinghts
  -tag: 998GGCQC
  -name: Omega™DREAM
  -tag: 992U9JQG
  -name: Omega™DKings
  -tag: 9CULVPCQ
  -name: Omega™ JO
  -tag: 9GQJ2G0G
  -name: Omega™ Hellas
  -tag: 9PR0Y2L9
  -name: Omega™ India 
  -tag: 9YPPJVQU
  -name: Omega™ India ♥️
  -tag: 9PYGCJ28
  -name: Omega GSD Spain
  -tag: 9P82PUCU
  -name: Omega™ Latam
  -tag: 9Y0PLURU
  -name: Omega™ Masters
  -tag: 9Y8Q0QVY
  -name: Omega™ Request
  -tag: 8C9UG2QG

**Comment by smlbiobot** [comment]
Can’t support that many clans in a family. We allow up to 20. Please break it up and send config again.

**Comment by smlbiobot** [comment]
You can, for example, split it into Omega 1 and Omega 2 — just something so as long as the families are separate. The site will try to load clan description from all of them at once, and as you can see, if it is this long, it will lead to excessive load times.

**Comment by AAsuitedAA** [comment]
I have edit the post with 20 clans

**Comment by smlbiobot** [comment]
This clan has 0 members and will be removed:


Egypt Omega™
#8GULP98Q

**Comment by smlbiobot** [comment]
telegram is not supported atm. We will consider adding it later.

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/omegaesports/clans

Please keep the following config for your records, which include error fixes:

```yaml
name: Omega eSports
key: omegaesports
color: blue
track: true
emblem: Star_Shine_01
feature: true
info:
  logo: /static/img/brands/logo/omegaesports.png
  description: >
    The Omega eSports its a international eSports organization. On Clash Royale there are more then 60 officials clans Omega! Here you can find only the mains, for full list you can vist out website!
    We have others competitive team with name "Omega" that participating to mains international competitions.
    #Omega_OP
  social:
    - facebook: https://www.facebook.com/OmegaeSportss/
    - twitter: https://twitter.com/omegaaesports
    - discord: https://discordapp.com/invite/7HaqZeK
    - website: http://www.omegaesports.net
    - email: mailto:info@omegaesports.net
clans:
  - name: Omega™ ITLegends
    tag: 8GUJ9J8G
  - name: Omega™ ITC
    tag: 90G8Y8GP
  - name: Omega™ Mugiwara
    tag: 90RR92PJ
  - name: Omega™ Napoles
    tag: 8C98CGJR
  - name: Omega™ Eclipse
    tag: 8RUPU2UR
  - name: Omega™ Fighters
    tag: 8Q2JV0QV
  - name: Omega™ Insane
    tag: 8VUU8RLJ
  - name: Egypt Omega™
    tag: 8GULP98Q
  - name: Omega™ Panama
    tag: 9C2VPYRU
  - name: Omega™Kinghts
    tag: 998GGCQC
  - name: Omega™DREAM
    tag: 992U9JQG
  - name: Omega™DKings
    tag: 9CULVPCQ
  - name: Omega™ JO
    tag: 9GQJ2G0G
  - name: Omega™ Hellas
    tag: 9PR0Y2L9
  - name: Omega™ India
    tag: 9YPPJVQU
  - name: Omega™ India ♥️
    tag: 9PYGCJ28
  - name: Omega GSD Spain
    tag: 9P82PUCU
  - name: Omega™ Latam
    tag: 9Y0PLURU
  - name: Omega™ Masters
    tag: 9Y8Q0QVY
  - name: Omega™ Request
    tag: 8C9UG2QG
```
