### ISSUE TITLE
family config for Banana Warriors

### ISSUE THREAD

**Issue by DaDa101** [RoyaleAPI/cr-api-ux#85]
```yaml
name: Banana Warriors
key: bw
color: yellow
emblem: Skull_01
sort: trophy
info:
  logo: https://bananenclan.de/wp-content/uploads/2018/05/bw-400x400.png
  description: >
    Die *Banana Warriors* - hervorgegangen aus den Elementar Bananen - bestehen aus mehreren Clans, die das ganze Pokalspektrum abdecken. Unter uns befinden sich auch einige erfolgreiche Turnier-Spieler und nicht zuletzt Streamer, die in ClashRoyal aktiv sind. Bei unseren Mitgliedern legen wir wert auf Aktivität im ClanWar und Freundlichkeit im Umgang mit Anderen.
  social:
    - discord: http://discord.gg/bananawarriors
    - twitch: https://www.twitch.tv/neonvimes
    - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
    - website: http://bananenclan.de
clans:
  - name: Platin Bananen
    tag: 8GUPGYVY
  - name: Xenon Bananen
    tag: 9YJLCRR0
  - name: Radium Bananen
    tag: 8Q8JRPQV
  - name: Neon Bananen
    tag: 8PRPP00J
  - name: Chrom Bananen
    tag: 8CLJQPR0
  - name: Dubnium Bananen
    tag: 92JRUYC8
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/bw/clans

**HOWEVER**

Some of the clans listed here overlaps with https://royaleapi.com/clan/family/banana/clans

Can you explain?

```yaml
name: Banana Warriors
key: bw
color: yellow
emblem: Skull_01
sort: trophy
info:
  logo: /static/img/brands/logo/banana_warriors.png
  description: >
    Die *Banana Warriors* - hervorgegangen aus den Elementar Bananen - bestehen aus mehreren Clans, die das ganze Pokalspektrum abdecken. Unter uns befinden sich auch einige erfolgreiche Turnier-Spieler und nicht zuletzt Streamer, die in ClashRoyal aktiv sind. Bei unseren Mitgliedern legen wir wert auf Aktivität im ClanWar und Freundlichkeit im Umgang mit Anderen.
  social:
    - discord: http://discord.gg/bananawarriors
    - twitch: https://www.twitch.tv/neonvimes
    - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
    - website: http://bananenclan.de
clans:
  - name: Platin Bananen
    tag: 8GUPGYVY
  - name: Xenon Bananen
    tag: 9YJLCRR0
  - name: Radium Bananen
    tag: 8Q8JRPQV
  - name: Neon Bananen
    tag: 8PRPP00J
  - name: Chrom Bananen
    tag: 8CLJQPR0
  - name: Dubnium Bananen
    tag: 92JRUYC8
```
