### ISSUE TITLE
Aktiv clan family

### ISSUE THREAD

**Issue by Anton3** [RoyaleAPI/cr-api-ux#88]
```yaml
name: Актив СНГ
key: aktiv
color: blue
track: true
emblem: Bolt_03
feature: true
vip: true
info:
  logo: https://i.imgur.com/WJP6CVU.jpg
  description: >
    **Актив СНГ** — семейство, состоящее из 5 кланов, которые борются за топ России.
    Основной клан держит топ-20 местных и занимает верхние строчки местного рейтинга КВ.
    Клан основан 27.03.2016 и является домом для участников CCGS, CRL, нескольких команд RRL.
    Неактивные игроки проходят мимо. Только Актив, только Хардкор!
  social:
    twitch: https://www.twitch.tv/vanco_youtube
    youtube: https://www.youtube.com/channel/UCcSeRO05Ju8vkkuWpV9Lrmw
  clans:
    - name: Актив СНГ
      tag: U0UR2L
    - name: Актив СНГ II
      tag: P29J208
    - name: Актив СНГ III
      tag: RPYJ8L2
    - name: Актив СНГ IV
      tag: 2V08CU8V
    - name: Актив СНГ V
      tag: 80J0R9R2
```

**Comment by Anton3** [comment]
Sorry for VIP, just copied from Reddit Alpha family. What does it even mean? Is it that I've donated?

**Comment by smlbiobot** [comment]
no. it doesn’t do a thing. It will be removed.

**Comment by smlbiobot** [comment]
http://royaleapi.com/clan/family/aktiv

Any field that you don’t see in the docs has been removed. This is your latest config. Please note that the `clans` field is a top-level field.


```yaml
name: Aктив СНГ
key: aktiv
color: blue
emblem: Bolt_03
info:
  logo: /static/img/brands/logo/aktiv.jpg
  description: >
    **Актив СНГ** — семейство, состоящее из 5 кланов, которые борются за топ России.
    Основной клан держит топ-20 местных и занимает верхние строчки местного рейтинга КВ.
    Клан основан 27.03.2016 и является домом для участников CCGS, CRL, нескольких команд RRL.
    Неактивные игроки проходят мимо. Только Актив, только Хардкор!
  social:
    - twitch: https://www.twitch.tv/vanco_youtube
    - youtube: https://www.youtube.com/channel/UCcSeRO05Ju8vkkuWpV9Lrmw
clans:
  - name: Актив СНГ
    tag: U0UR2L
  - name: Актив СНГ II
    tag: P29J208
  - name: Актив СНГ III
    tag: RPYJ8L2
  - name: Актив СНГ IV
    tag: 2V08CU8V
  - name: Актив СНГ V
    tag: 80J0R9R2
```
