### ISSUE TITLE
sylvanas Family clans

### ISSUE THREAD

**Issue by SamyBDZ** [RoyaleAPI/cr-api-ux#93]
name: Sylvanas Clan Family

key: Sylv

color: red

track: true

emblem: Star_Shine_03.png 

feature: true

vip: true

info:

  logo: https://gyazo.com/596e84abf20ec2d478ab4db5f90983cd
 
  description: >

    **Sylvanas Clans Family** es una familia de clanes creada en 2010  en España 

    con el objetivo de reunir jugadores de clash royal que vayan creciendo y nutran a nuestro

    clan competitivo denominado Elite , para en un futuro poder pensar en formar un equipo de Esports

    
    fundada por Tyrathan en Enero 2016.

  social:

    - twitter: https://twitter.com/SylvanasLegion

    - discord: https://discord.gg/z53Ab4r
    
    - twitch: 

    - reddit:

    - youtube: 

    - website:  

clans:

  - name: Sylvanas Elite

    tag: 9YC900G8

  - name: Sylvanas Legion

    tag: 8LYJ0UYC

  - name: Sylvanas L3gion

    tag: P2RYPY0Q

  #

**Comment by smlbiobot** [comment]
```yaml
name: Sylvanas Clan Family
key: Sylv
color: red
track: true
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/sylvanas.png
  description: >
    **Sylvanas Clans Family** es una familia de clanes creada en 2010  en España
    con el objetivo de reunir jugadores de clash royal que vayan creciendo y nutran a nuestro
    clan competitivo denominado Elite , para en un futuro poder pensar en formar un equipo de Esports
    fundada por Tyrathan en Enero 2016.
  social:
    - twitter: https://twitter.com/SylvanasLegion
    - discord: https://discord.gg/z53Ab4r
clans:
  - name: Sylvanas Elite
    tag: 9YC900G8
  - name: Sylvanas Legion
    tag: 8LYJ0UYC
  - name: Sylvanas L3gion
    tag: P2RYPY0Q
```
