### ISSUE TITLE
New clan family. Thx

### ISSUE THREAD

**Issue by Garyckw** [RoyaleAPI/cr-api-ux#94]
```yaml
name: 羔羊
key: gosheep
color: violet
track: true
emblem: Twin_Peaks_01
feature: true
info:
  description: >
    迷失的羔羊@@hk  hk local top 10
    未必係最強, 但一定係全港最團結, 最熱鬧既公會 
    歡迎凝聚力強, 活躍, 中意吹水, 中意同其他公會玩友誼賽既大家加入
    公會部落戰連開, 希望所有人打齊2日既部落戰~ 有興趣加入一個熱鬧既公會一齊打拼的話, 歡迎加入羔 
    羊既大家庭
    4個公會共用一個telegram group
    公會爆人, 分數差少少, 有心玩但申請唔到公會既,歡迎telegram我:nothisid
    另外coc,沉默的羔羊@@hk招收非速8,9,10本,歡迎新手老手加入~
social:
    - twitch: https://www.twitch.tv/tomtt
clans:
  - name: 迷失的羔羊@@hk
    tag: 9PRL28
  - name: 迷路的羔羊@@hk
    tag: 220UR8CV
  - name: 迷途的羔羊@@hk
    tag: 2LCU22YU
  - name: 迷踪的羔羊@@hk
    tag: 2Y0C2R00
```

**Comment by smlbiobot** [comment]
```yaml
name: 羔羊
key: gosheep
color: violet
emblem: Twin_Peaks_01
info:
  description: >
    迷失的羔羊@@hk  hk local top 10
    未必係最強, 但一定係全港最團結, 最熱鬧既公會
    歡迎凝聚力強, 活躍, 中意吹水, 中意同其他公會玩友誼賽既大家加入
    公會部落戰連開, 希望所有人打齊2日既部落戰~ 有興趣加入一個熱鬧既公會一齊打拼的話, 歡迎加入羔
    羊既大家庭
    4個公會共用一個telegram group
    公會爆人, 分數差少少, 有心玩但申請唔到公會既,歡迎telegram我:nothisid
    另外coc,沉默的羔羊@@hk招收非速8,9,10本,歡迎新手老手加入~
  social:
      - twitch: https://www.twitch.tv/tomtt
clans:
  - name: 迷失的羔羊@@hk
    tag: 9PRL28
  - name: 迷路的羔羊@@hk
    tag: 220UR8CV
  - name: 迷途的羔羊@@hk
    tag: 2LCU22YU
  - name: 迷踪的羔羊@@hk
    tag: 2Y0C2R00
```
