### ISSUE TITLE
Family: The Titans

### ISSUE THREAD

**Issue by NovaRyquaxera** [RoyaleAPI/cr-api-ux#95]
```yaml
name: The Titans 
key: titans
color: purple
sort: trophy
emblem: Star_Shine_03
logo: IMG-20180520-WA0009.jpg
info:
  description: >
    Official Indian Alliance Branch of "Nova eSports Organization"


    The Titans is a organization committed to empowering individuals & clashers through a supportive team environment. We look for talent in our nation and make them reach thier destiny through proper guidance and support.

Our clan is a union of top Indian clans empowering the whole Indian Community. We also have a Competitive team which basically participates in all APAC region leagues. Our family is highly diverse so we welcome players globally to join and contact us.


    
  social:
    - twitter: http://twitter.com/TheTitans_CR
    - discord: https://discord.gg/YJ5KFRM
    - email: mailto:TheTitansIndia@Gmail.com
    - youtube:https://www.youtube.com/channel/UCE_PBvnk1ibntLz9mm_Ceww


clans:
  - name: The Titans
    tag: 9CUGGLC9
  - name: The Titans Zonk
    tag: 9Y8J08Q2
  - name: The Titans Xtrm
    tag: P9JPUJ8J
  - name: The Titans Rage
    tag: 9ULGVUL9
  - name: The Titans Pros
    tag: 9Q892O98
  - name: TheTitans Yodha
    tag: 9VYGCRV2
  - name: The Titans Hype
    tag: 9CUV0VUJ

**Comment by smlbiobot** [comment]
@NovaRyquaxera Logo URL invalid. Please re-edit

**Comment by smlbiobot** [comment]
```yaml
name: The Titans
key: titans
color: purple
sort: trophy
emblem: Star_Shine_03
logo: /static/img/brands/logo/titans.jpg
info:
  description: >
    Official Indian Alliance Branch of "Nova eSports Organization"


    The Titans is a organization committed to empowering individuals & clashers through a supportive team environment. We look for talent in our nation and make them reach thier destiny through proper guidance and support.


    Our clan is a union of top Indian clans empowering the whole Indian Community. We also have a Competitive team which basically participates in all APAC region leagues. Our family is highly diverse so we welcome players globally to join and contact us.
  social:
    - twitter: http://twitter.com/TheTitans_CR
    - discord: https://discord.gg/YJ5KFRM
    - email: mailto:TheTitansIndia@Gmail.com
    - youtube: https://www.youtube.com/channel/UCE_PBvnk1ibntLz9mm_Ceww
clans:
  - name: The Titans
    tag: 9CUGGLC9
  - name: The Titans Zonk
    tag: 9Y8J08Q2
  - name: The Titans Xtrm
    tag: P9JPUJ8J
  - name: The Titans Rage
    tag: 9ULGVUL9
  - name: The Titans Pros
    tag: 9Q892O98
  - name: TheTitans Yodha
    tag: 9VYGCRV2
  - name: The Titans Hype
    tag: 9CUV0VUJ

```
