### ISSUE TITLE
注册暴躁世界家族

### ISSUE THREAD

**Issue by hzq8382785** [RoyaleAPI/cr-api-ux#96]
name: 暴躁世界家族
key: BZSJ
color: Black
emblem: Skull_06
info:
  logo: 
  description:
    **世界如此美妙,我却如此暴躁,这样不好不好。**
  social:
    - website: https://www.douyu.com/hzq8382785
    - email: mailto:hzq8382785@qq.com
clans:
  - name: 暴躁世界
    tag: 2GPC0VQ
  - name: 暴躁世界_陷阵营
    tag: 9R2P9029
  - name: 暴躁世界_小皮卡
    tag: Q2JV809
  - name: 暴躁世界_异次元
    tag: 28UV8JVQ
  - name: 暴躁世界_名人堂
    tag: GG8CQC9
  - name: 暴躁世界—云南
    tag: QL82JRJ

**Comment by smlbiobot** [comment]
https://royaleapi.com/clan/family/bzsj

```yaml
name: 暴躁世界家族
key: bzsj
color: Black
emblem: Skull_06
info:
  description: >
    **世界如此美妙,我却如此暴躁,这样不好不好。**
  social:
    - website: https://www.douyu.com/hzq8382785
    - email: mailto:hzq8382785@qq.com
clans:
  - name: 暴躁世界
    tag: 2GPC0VQ
  - name: 暴躁世界_陷阵营
    tag: 9R2P9029
  - name: 暴躁世界_小皮卡
    tag: Q2JV809
  - name: 暴躁世界_异次元
    tag: 28UV8JVQ
  - name: 暴躁世界_名人堂
    tag: GG8CQC9
  - name: 暴躁世界—云南
    tag: QL82JRJ
```
