### ISSUE TITLE
HK Protesters

### ISSUE THREAD

**Issue by NOxSolution** [RoyaleAPI/cr-api-ux#97]
```yaml
name: HK Protesters
key: HKP
color: red
track: true
emblem: flag_d_02
feature: true

info:
  description: >
   We are Hong Kongese!!! welcome to HK Protesters or branch HK Frontiers, HK Pioneers, HK Innovators. 
可入wtsapp gp. 有意請加TG: maiwing Crown Duel.
 social:
    - twitch: https://www.twitch.tv/hkprotesters
clans:
  - name: HK Protesters
    tag: 98UUGL
  - name: HK Frontiers
    tag: L88C28G
  - name: HK Pioneers
    tag: 2URRGJVG
  - name: HK Innovators
    tag: 8U2LV9Y2
  
…
```

**Comment by smlbiobot** [comment]
```yaml
name: HK Protesters
key: hkp
color: red
emblem: flag_d_02
info:
  description: >
    We are Hong Kongese!!! welcome to HK Protesters or branch HK Frontiers, HK Pioneers, HK Innovators.
    可入wtsapp gp. 有意請加TG: maiwing Crown Duel.
  social:
    - twitch: https://www.twitch.tv/hkprotesters
clans:
  - name: HK Protesters
    tag: 98UUGL
  - name: HK Frontiers
    tag: L88C28G
  - name: HK Pioneers
    tag: 2URRGJVG
  - name: HK Innovators
    tag: 8U2LV9Y2
```
