### ISSUE TITLE
Norwegians

### ISSUE THREAD

**Issue by olemartin** [RoyaleAPI/cr-api-ux#98]
```yaml
name: Norwegians
key: nor
color: red
track: true
emblem: heart_02
feature: true

info:
  description: >
    The Norwegians clan-family has the best and most active norwegian Clash Royale players.

 social:
    - discord: https://discord.io/norwegians
    - website: http://cr-norwegians.no/
clans:
  - name: Norwegians
    tag: YYGPC9
  - name: Norwegians 2
    tag: L2YC2VY
  - name: Norwegians 3
    tag: 229GLQJV
  - name: Norwegians Raw
    tag: 9PQ9RGL
```

**Comment by smlbiobot** [comment]
```yaml
name: Norwegians
key: nor
color: red
emblem: heart_02
info:
  description: >
    The Norwegians clan-family has the best and most active Norwegian Clash Royale players.
  social:
    - discord: https://discord.io/norwegians
    - website: http://cr-norwegians.no/
clans:
  - name: Norwegians
    tag: YYGPC9
  - name: Norwegians 2
    tag: L2YC2VY
  - name: Norwegians 3
    tag: 229GLQJV
  - name: Norwegians Raw
    tag: 9PQ9RGL
```
