### ISSUE TITLE
赤鱲角馬會

### ISSUE THREAD

**Issue by edgar0379** [RoyaleAPI/cr-api-ux#99]
```yam1
name: 赤鱲角馬會
key: 赤鱲角
color: blue
track: true
emblem: Freeze_01
feature: true
info:
  description: >
  機場朋友創會..歡迎其他行業一齊入黎玩..一齊吹水friendly..有wts group要入搵會長..慣性秒捐部落..設分會赤鱲角馬會·2·3會..歡迎各階段玩家..現招收活躍玩家 歷史4800+🏆 歡迎約戰.. 請聯絡TG:Edgar_0379
 social:
    - Telegram Id: Edgar_0379
clans:
  - name: 赤鱲角馬會
    tag: P02PG2Y
  - name: 赤鱲角馬會-2nd
    tag: 89PC02GP
  - name: 赤鱲角馬會-3RD
    tag: 89UURJ20
```

**Comment by edgar0379** [comment]
Sorry admins ... I dont too understand the format . If somethings wrong please comment below and  i will try to fix it.. Thanks!!!

**Comment by smlbiobot** [comment]
format is fine. We will add when we are able. thanks.

**Comment by edgar0379** [comment]
Thank you very much:)

**Comment by smlbiobot** [comment]
Config:
- key must be in English, lowercase. Renamed to clk
- Social links must be links. Using http://telegram.me/Edgar_0379

Updated config:

```yaml
name: 赤鱲角馬會
key: clk
color: blue
emblem: Freeze_01
info:
  description: >
    機場朋友創會..歡迎其他行業一齊入黎玩..一齊吹水friendly..有wts group要入搵會長..慣性秒捐部落..設分會赤鱲角馬會·2·3會..歡迎各階段玩家..現招收活躍玩家 歷史4800+🏆 歡迎約戰.. 請聯絡TG:Edgar_0379
  social:
    - telegram: http://telegram.me/Edgar_0379
clans:
  - name: 赤鱲角馬會
    tag: P02PG2Y
  - name: 赤鱲角馬會-2nd
    tag: 89PC02GP
  - name: 赤鱲角馬會-3RD
    tag: 89UURJ20
```
